### ISSUE TITLE
Quid de la langue de documentation?

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#1]
Voici pour le premier document concernant les skills des membres. 
la question se pose au sujet de la langue pour que ce soit le plus ouvert possible. Est-ce que pour github, on ne prendrai pas l'habitude de traduire en anglais? même si dans un premier tps, ça peut être une traduction google... 
https://github.com/openfab-lab/openfab/blob/master/team.md

**Comment by dezminator** [comment]
Je peux traduire vers l'anglais, du coup on aurait peut être besoin d'une traduction Néerlandaise et Allemande pour couvrir toutes les langues officielles de Belgique.

**Comment by nicolasdb** [comment]
Yes :+1: 
On peut. Of course. 
Mais il faudrait peut-être convenir d'un code pour dire que tel ou tel partie ne vas plus trop changer. 
Tant que c'est en réflexion, le texte peut changer assez fortement.
ça peut être un délimiteur ou simplement de se dire que si le doc n'évolue pas depuis 15j, la traduction peut se faire. 
Je vois peut-être déjà trop loin... qu'est-ce que t'en pense?

**Comment by dezminator** [comment]
On a toujours l'option de discuter avant de "merge" un pull request donc ça devrait aller, peut etre assigner des gens à la vérification de telle ou telle partie dans le github, pour éviter de se disperser.
