### ISSUE TITLE
Agenda general

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#103]
# Agenda pour avoir une vue global de ce qui ce passe dans OpenFab
ref to file.md or #issue :
## contexte
suite à #70: créer une page qui est lié au site et ou on peut voire tous les events, moment de travaille collectif dans un et même lieu
## objectif
créer une boucle: date -> Agenda -> Site

**Comment by nicolasdb** [comment]
Qu'est-ce qu'on a comme choix? 

- google? 
- framasoft kekchose?
-

**Comment by Ginsburg** [comment]
Est-ce qu'on ne peut pas tenter quelque chose de [ce genre](https://www.startupdigest.com/digests/brussels) ? Un Maker Digest ?

**Comment by nicolasdb** [comment]
pour les évènements commun on a déjà mis en place la page meetup fabcity brussels. C'est nous qui payons d'ailleurs... 

Pour l'agenda, y a aussi https://framablog.org/2016/10/07/framagenda-ne-partagez-plus-votre-planning-ni-vos-contacts-avec-la-nsa/
mais c'est similaire d'usage à google. Sauf que sans personne qui s'y connaisent bien pour paramettrer tout chez tout le monde, moi même, j'accumule le bordel dans les différents agenda perso, pro et pro contact. 

je pense ou j'espère qu'il serait plus simple de séparer un agenda commun de tout les comptes googles accumulés. 

à tester. Reste à voir comment l'intégrer sur une page qque part.

**Comment by Ginsburg** [comment]
Voilà, comme le suggérait Nicolas, un premier agenda en markdown pour commencer : https://github.com/openfab-lab/openfab/blob/master/_event/agenda-septembre.md

**Comment by nicolasdb** [comment]
bon ben, on est presque fin septembre. 
@Ginsburg  tu avais posté un event pour le bricole & picole pour finir?

ça serai bien un template d'agenda et une mise en avant sur le readme des activités. 
@softrevolter a programmé d'ailleurs un braincandy en Octobre. 
ça serai bien de commencer un agenda Octobre.

**Comment by nicolasdb** [comment]
ok, au final, un agenda est créé en google sheet et publié sur le site. 
Un changement dans google sheet est directement mis à jour en ligne. 

On pourrait partager un agenda google de la même manière mais c'est moins joli. 
Astuce pour modifier des évènements multiples:
https://bulkeditcalendarevents.wordpress.com/features/

**Comment by nicolasdb** [comment]
Un agenda google est partagé pour annoncer les permanences et est synchronisé avec le site web ainsi qu'un affichage e-ink en vitrine. Merci @doegox
