### ISSUE TITLE
Frigo vide, à plus de bière ;-(

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#106]
Frigo vide, à plus de bière ;-(

**Comment by nicolasdb** [comment]
ha! 
ouais, j'avais ce message sur mon clavier hier quand je suis venu bricoler en cachette. 
Probablement Loois en ramenant la jacqueline vendredi après la critical mass. (gros succès on dirait)

**Comment by Ginsburg** [comment]
Ça me fera l'occasion de gagner 1Desbières, ça me va :)

**Comment by Ginsburg** [comment]
Quand il n'y en a plus, il y en a encore !
