### ISSUE TITLE
Matériau + machine pour réaliser pochoir Karcher

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#109]
# Matériau pour réaliser pochoir Karcher
ref to file.md or #issue :

## contexte
On a reçu un appel de Point Culture qui veut réaliser des pochoirs pour faire des graffitis avec un Karcher comme sur cet exemple : http://tempsreel.nouvelobs.com/rue89/rue89-rue89-culture/20111011.RUE4876/pochoir-au-karcher-dans-les-rues-de-riga.html

## objectif
Trouver le bon matériau, la bonne machine. L'idée est de le pochoir puisse facilement être réutilisé. Leur idée est de faire ça en métal, ce qui ne me semble pas évident avec nos machines. Je pensais à du bois et pourquoi pas aller jusqu'à utiliser la CNC pour avoir de l'épaisseur, sinon découpeuse laser sur du plus fin (résistant au jet du Karcher ?)

Ils souhaiteraient une réponse lundi ou mardi. 

## proposition
Un petit test sur une chute pourrait les rassurer sur la faisabilité. Envoyer un mail lundi ou mardi avec nos recommandations et next steps.

**Comment by nicolasdb** [comment]
metal on ne sait pas faire. 
dans une vidéo que j'ai trouvé, ils en utilisent quand même bcp. 
https://www.youtube.com/watch?v=I1x8vzX4P_I

J'aurai tendance à dire qu'ils ont utilisé du pvc qui est souple, c'est plus solide que le plexi qui casse. 
dans l'exemple video, ils ont clairement utilisé du laser mais nous on ne peut pas couper dans le pvc. C'est toxique. Il existe des machines qui sont concues pour. 
On peut couper à la cnc par contre. 

le bois, laisse tomber, ça va boire, se défomrer, casser peut-être aussi. 
Reste le polypropylène, (comme la couverture atoma et du passeport) mais pour cet usage. ce sera peut-être trop souple.

**Comment by nicolasdb** [comment]
ha, faut alors trouver une plaque de pvc 1 ou 2 mm.

**Comment by Ginsburg** [comment]
Je ferme pour le moment, c'est en standby chez PointCulture.
#féedulogissurGitHub
