### ISSUE TITLE
Labels and procedural rethoric

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#11]
### Déclencheur (Action)
 - un problème, une opportunité, une tension, une question 
### Routine (Réaction)
 - création d'une "issue" sur github suivant une syntaxe et assignée à une catégorie. 
!!! tout "déclencheur" doit s'accompagner d'une proposition
Exemple: 

> il faudrait déterminer les catégories principales, 
> j'en propose 5, les 5 éléments.
> Mais si je fais le lien avec les méridiens, il y en aurai 6. 
> 5 paires d'organes Yin/yang + 1 pair circulation sanguine et circ. fluide/plasma/lymphe/etc... 
> Bois, métal, terre, feu et eau + ce qui pourrait correspondre à tout ce qui touche le "back-office" qui concerne tout les éléments.
### Récompense
le signalement d'un déclencheur 
- "mineur" + 1 crrr , = "je n'arrive pas à me connecter sur le NAS, je ne trouve pas d'info, ça serait bien de créer un tuto"
**Signalement d'un manque**
- "moyen" + 5 crrr = "réponse. En fait c'est tout simple, voilà le tuto est maintenant écrit ici" 
**Résolution d'un problème**
- "Majeur" + 10 crrr
**Documentation de son projet**

**Comment by nicolasdb** [comment]
# how to best use issues
https://guides.github.com/features/issues/

**Comment by softrevolter** [comment]
i love the term 'crrr' as the name for the tokens :) 
I will read more about the issues. It needs to be in the core of the gameplay, will think how it can be implemented

**Comment by nicolasdb** [comment]
proposition de définition par la pratique ici
https://github.com/openfab-lab/github-introduction-ws/issues/4

**Comment by nicolasdb** [comment]
J'ai prospecté avec Pascal (membre) les differents grandes classes d'insentive poussant qqu'un à s'engager dans un projet, une quête. 

- Financier:
  - j'ai les compétences, les badges,  je peux faire le job contre rémunération.
  - ça m'intéresse mais en échange d'un autre service (troc) ou échande de crrr
- Level UP:
  - je dois valider ma compétence, je fais le job afin d'obtenir mon badge (PROF: process d'expliquer à quelqu'un de nouveau pour valider sa propre compréhension)
  - je dois apprendre un nouveau skill, je participe au projet comme stagaire pour apprendre des autres (TRAINING: process d'apprendre avec quelqu'un qui sait)
- Fun: le projet est tellement super que je participe juste comme ça.
*mais ce n'est probablement pas très durable/fiable dans le tps sur du gros projet composé de tâches moins fun (parfois)*

je pense aussi à l'opportunité d’utiliser du matos hors du commun, matériaux, etc... mais ça s'apparente au level up Training....

**Comment by softrevolter** [comment]
donc comme dit dans issue #16 

Voici la boucle que moi j'avais en tête

il y a un problème a resoudre dans le large terme du mot (quelque chose a faire pour le fablab, a construire, a réparer. De la plus petite mission a la plus longue quête)

Quelqu'un peut alors dire: eh mais c'est mission intel et mettre le lien vers la mission.
Si la mission n'existe pas il peut y avoir deux possibilité: Créer la mission ou juste répondre si le problème est immédiatement résolut.
Donc voici la boucle:

-> créer un issue = 1 D3 trow
-> montrer le chemin vers la mission pour réussir le issue = 1 D3 trow
-> résoudre immédiatement la issue dans la discussion = 1D6 trow
-> créer la mission = 1D6 trow
-> créer la mission et la solution (documenter) = 2D6 trow

**Comment by nicolasdb** [comment]
Après réflexion et test pratique de petites missions voici ce que je propose :


Boucle 1:
- une issue = 1crrr
- réponse documentée dans un fichier.md = 5 crrr
Condition: S'assigner l'issue permet de signaler qui s'en occupe et qui reçoit les 5 crrr. *Assignation pour 24h* après, si pas de fichier.md, qqun d'autre peut prendre la main. 
- clôture de l'issue

Les missions : 
Peuvent être de classe
- mineure, 
pas de skill, <30min, pas de documentation. La description est une résultante de la boucle 1. = 1d6, probabilité 1/6
- majeure,
  - ~1 skill ou pas... 
  - > 30 min 
  - documentation
  - définition de la valeur ? Fiche projet = Boucle 2? 

- Une​ quête se compose de plusieurs missions majeures. 

- une épopée, ... Sera chantée par les générations futures.

Potentiellement accessible à tous mais seul le passeport permet de sauvegarder les crrr et les skill acquis. -> **SuperUser**

**MetaUser**
Min 20 skills ?
Boucle 3: validation de compétences ?
Monétisation crrr/€
Droit d'écriture au wiki?
