### ISSUE TITLE
Matériau + machine pour réaliser pochoir pour graffer pochette vinyle

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#110]
# Matériau + machine pour réaliser pochoir pour graffer pochette vinyle
ref to file.md or #issue :

## contexte
Aujourd'hui c'est la journée du pochoir ! On a une autre demande "pochoir" (#109)

## objectif
Matériau résistant, fin, réutilisable.

## proposition
Le souhait est de tester sur du plexi, fin mais rigide, résistant --> découpeuse laser.
Ça se passe comment avec ce matériau ? C'est dans la [liste](https://www.pololu.com/docs/0J24/3) de ce qui est "gravable" en tout cas. 
Test demain.

**Comment by nicolasdb** [comment]
idem, plexi, ça brise. 

le PP polypropylène est parfait pour ça. Les plaques noires 0.8mm au bureau

**Comment by Ginsburg** [comment]
Finalement ça passera par de la sériegraphie chez http://www.38quainotredame.com/.
