### ISSUE TITLE
organicity

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#116]
ref to file.md or #issue :
## contexte
tout à l'heure, c'est organicity.
## objectif
J'essaye de réunir ici quelques trucs qui pourrait servir cet aprem comme exemple.

## proposition
Alors, notre fusée est à 3 étages et il faut les 3 pour que ça décolle.

1. le catalogue *(faire quoi?)*
La présentation des réalisations avec une documentation à 2 niveaux au moins.
    - Une info "client" avec ce que c'est, ce que ça coute et en combien de tps on peut le produire.
    - Une info "maker" avec le tuto, quelles machines, combien de tps, quel matière, quantité etc... et les compétences requises pour le produire.
Les réalisations peuvent être un design produit, un stage, une formation, une expertise,... on y choisit son menu "à la carte"
1. [le passeport](https://github.com/openfab-lab/passeportMaker) *(par qui?)*
Pour y réunir l'évolution du maker. On y retrouve principalement:
    - qui il est
    - La liste des [badges compétences](https://github.com/openfab-lab/pack-openbadge-fablab) qu'il a acquit et l'expérience accumulée.
    - une puce NFC permet l'activation de fonctionnalités étendues au travers d'une identification numérique
L'usage du passeport maker permet l'accès à des lieux, à des machines mais aussi active une mobilité dans le réseau que ce soit localement ou internationalement. On y matérialise la confiance qu'une communauté porte à l'égard d'un de ses membres et est reconnue dans d'autres communautés par la confiance entre les communautés partageant l'usage du passeport maker.
1. [la gamification](https://github.com/openfab-lab/gamification-fablab) *(comment?)*
C'est le fuel de la fusée, c'est les règles du jeux pour 
    - obtenir son passeport, 
    - acquérir des compétences via les badges
    - documenter
    - travailler ensemble
    - pouvoir bénéficier du catalogue. (soit pour y ajouter du nouveau contenu, soit pour la production du contenu)
    - facturer sur base de prestation
## ressources
- dashboard for data visualisation
https://github.com/openfab-lab/openfab/issues/33
https://github.com/keen/dashboards

**Comment by nicolasdb** [comment]
https://opensource.guide/

**Comment by nicolasdb** [comment]
Projet VULCA
https://www.youtube.com/watch?v=Y2CJH72j1VY
http://www.program-vulca.eu/

**Comment by nicolasdb** [comment]
@dezminator 

ok then. y a plus qu'à... 
RDV chez CIN le 22 c'est ça?

**Comment by dezminator** [comment]
Oui c'est bien ça, je crois que ce sera encore à DigitYser.
Entre temps j'ai contacté Bert, le responsable du projet openbadges, il dit qu'il est présent au meetup des Civic Labs Brussels qui ont lieu à BeCentrale, je vais essayer de l'y rencontrer pour lui expliquer le projet en détails.

**Comment by nicolasdb** [comment]
Remise jeudi soir. 
On attend une relecture de PA et Alain. 
Y a encore des brols techniques à mentionner, comme quelles techno ou data on aurai besoin d'organicity. 
rien. 
et les interactions entre partenaires lors de l'expérience.

**Comment by nicolasdb** [comment]
on a perdu l'appel. 
Pas de €€€€ pour nous

je clos cette issue

**Comment by softrevolter** [comment]
il faudra trouver pourquoi aucun appel bruxellois n'as eu l'offre, on a pas le niveau ou quoi?

**Comment by nicolasdb** [comment]
aucun? personne n'est sélectionné des propositions passées par CIN?

**Comment by dezminator** [comment]
Je persiste à croire qu'ils n'ont pas lu les candidatures. Je ne suis pas
d'accord avec le verdict qu'on a reçu, parce qu'il ne s'applique pas à
notre projet.
Je serais curieux de voir ce que les autres projets ont eu comme réponses.
Je doute que ce soient des réponses relatives aux projets "jugés".

IT Entrepreneur / Maker / Photographer
Mobile BE: (+32) 0465 60 74 41 / SN: (+221) 77 440 52 94
Twitter <https://twitter.com/dezminator>
Instagram <https://www.instagram.com/dezminator/>

**Comment by softrevolter** [comment]
tu veux partager ce que le dossier openfab à reçu comme critique?

**Comment by nicolasdb** [comment]
easy:

> Thank you for submitting your experiment to OrganiCity’s second and final Open Call.
> We have been pleased to see that the number and quality of the submitted applications has been very high, but due to a limited budget, we unfortunately can only fund a few experiments.
> We regret to inform you that your application, has not been selected for funding.
> Please find the evaluators' score and feedback for your application below.
> 
> We hope that you will find other opportunities to realise your ideas.
>  
> Best wishes,
> The OrganiCity team
> 
> ===
> 
> Average score: 1.2
> 
> The experiment is unrelated to the Organicity scope, since it lacks link to urban data, IoT and the city. The experiment would not use the Organicity environment and the sustainability plans are vague.
> 
> ===​

**Comment by nicolasdb** [comment]
alors, aucune idée de la valeur de ce score. 
1.2/10? 1.2/20? 
1.2/2? 
Bonne ou super mauvaise note? :)

**Comment by softrevolter** [comment]
bon ce que lis là c'est que: ou leur inscription est mal foutu et il faut avoir un 'inside man' pour comprendre comment écrire le dossier. Ou il y avait pas un bon coach dans l'organisation général du organiCity journée pour décrypter ce qu'il fallait écrire. 
Car ok, si Urban Data était le plus important il fallait écrire le dossier d'une certaine manière, mais dire que c'est pas IoT c'est ne pas avoir lu le dossier...
