### ISSUE TITLE
Cleaning

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#118]
# Cleaning
ref to file.md or #issue : https://github.com/openfab-lab/openfab/blob/master/_space/Task/Cleaning-buro274.md
## contexte
C'était sale.
## objectif
Faut que ce soit propre.
## proposition
Cleaning
## ressources
Un aspi
Un balais
Une serpillière
Du savon
De l'eau

## Resultats
C'est propre, plus ou moins, pas encore mon badge fée du logis !

**Comment by nicolasdb** [comment]
yeah!

2 D6 pour toi :)
Le badge fée du logis est encore à faire. 

je pense utiliser quelque chose comme ça 
![img](https://github.com/openfab-lab/pack-openbadge-fablab/blob/master/unsorted/janitor_cleaner_by_apatrimonio.png?raw=true)
