### ISSUE TITLE
Class 101

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#12]
Can this also not be the same as what i have in mind with the missions

User

Documentation 101 = Mission 1.0.1, Documentation 102 = Mission 1.0.2
3D printing 201 = Mission 2.0.1, Documentation202 = Mission 2.0.2

Can we accept this logic?

**Comment by nicolasdb** [comment]
I'm ok with that. 
👍

**Comment by nicolasdb** [comment]
@softrevolter où se trouve la définition de cette logique?

**Comment by softrevolter** [comment]
it's written here now: [https://github.com/openfab-lab/openfab/blob/master/Gamification/Missions/Overview.md](url)
