### ISSUE TITLE
Cours en ligne : les bases du Game Design

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#121]
# Cours en ligne : les bases du Game Design
ref : https://learn.canvas.net/courses/3

## contexte 
Je me questionnais au sujet de la gamification et plus particulièrement quels sont les éléments constituants d'un jeu pour pouvoir s'en servir de cadre pour ne rien oublier dans notre "ludification" de l'expérience FabLab.

## objectif
Être sûr de ne pas passer à côté d'éléments importants.

## ressources
Le [cours](https://learn.canvas.net/courses/3) dont je parle.
Un [document annexe](http://www.cs.northwestern.edu/~hunicke/MDA.pdf) au cours, un papier académique sur le "Framework MDA".

### Les éléments d'un jeu
Je suis tombé sur cette liste assez intéressante ([ici](https://learn.canvas.net/courses/3/pages/level-3-dot-1-atomic-elements-of-games?module_item_id=44529)), chaque élément est détaillé, c'est plus ou moins évident mais c'est toujours intéressant de s'y arrêter quelques instants et transposer ça au FabLab :
    [Players](https://learn.canvas.net/courses/3/pages/level-3-dot-1-1-players)
    [Objectives (goals)](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-2-objectives-goals)
    [Rules](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-3-rules) : un des points les plus intéressants, plus ou moins du bon sens mais les règles d'un jeu sont divisées en 3 parties : "setup" (ce qui est à faire au début du jeu, pour pouvoir commencer), "progression of play" (pendant le jeu) et "resolution" (comment se finit le jeu, quel résultat).
    [Resources and Resource Management](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-4-resources-and-resource-management)
    [Game State](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-5-game-state)
    [Information](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-6-information)
    [Sequencing](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-7-sequencing)
    [Player Interaction](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-8-player-interaction)
    [Theme (Narrative, Backstory, Setting)](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-9-theme-narrative-backstory-setting)
    [Games as Systems](https://learn.canvas.net/courses/3/wiki/level-3-dot-1-10-games-as-systems)

### Le Framework MDA
C'est une approche pour décomposer la relation entre l'expérience de jeu et les règles. On part de l'aesthetics qu'on veut faire vivre et on redescend aux règles, ce sur quoi on peut vraiment influer.
![image](https://user-images.githubusercontent.com/7775797/29710105-45a15c06-898f-11e7-8feb-2488b8f736b8.png)
![image5124](https://user-images.githubusercontent.com/7775797/29710302-fd59f1f0-898f-11e7-816e-7b0cc70829b8.png)

Source : Le [fameux doc annexe](http://www.cs.northwestern.edu/~hunicke/MDA.pdf) juste au-dessus

**Comment by nicolasdb** [comment]
yes, 
j'ai mis plusieurs bouquins sur le game dev dans la bibliothèque locale.
\\MEDIAHUB\media\Books

**Comment by Ginsburg** [comment]
En soit, je clôture, pas besoin d'en discuter, je retournerai ici si besoin.
