### ISSUE TITLE
Créer un meetup B&P Aquaponie

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#123]
# Créer un meetup B&P Aquaponie
#70  : meetup en lien avec cette issue
## contexte
22 sept, Bricole et picole spécial aqua/hydroponie de 20 à 22h.
## objectif
Faire un meetup
## proposition
#23 On a l'accès au meetup maintenant ?
Je peux me charger de le créer dans la semaine.

**Comment by nicolasdb** [comment]
https://www.meetup.com/FabCity/

dès que j'ai ton ID meetup, je t'ajoute comme co-organisateur des évènements

**Comment by Ginsburg** [comment]
Juste Paul Le Coz + le lien de mon profil : https://www.meetup.com/fr-FR/FabCity/members/227730031/

Ça suffit ?

**Comment by nicolasdb** [comment]
yes,  tu devrai avoir les droits de créer un évènement maintenant

**Comment by Ginsburg** [comment]
Voici un [texte de présentation](https://github.com/openfab-lab/openfab/blob/master/_event/bricole-picole/presentation.md), j'ai pris ce que j'ai trouvé à droite à gauche et essayer d'adapter et mettre un ton un peu plus fun (mais bon, je crois pas avoir mon badge humour, encore une fois).

**Comment by nicolasdb** [comment]
Bien, ben c'était cool.

Massimo et Victor était content, 
il y avait peu de monde (7 je pense) mais c'était qualitatif et c'est ce qui leur a plut. 
Quand il y a trop de monde, on ne rentre pas assez dans le sujet.

Je clos cette issue.
