### ISSUE TITLE
Adapter visuel B&P

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#124]
# Visuel B&P
En lien avec la création du meetup #123 & #70 
## contexte
Avoir un petit visuel, ça peut être cool ! (et je continue à explorer le découpage de tâches via ZenHub)
## objectif
Faire un visuel.
## proposition
On a déjà des visuels de @zuperninja si je ne dis pas de bêtise, où dois les retrouver pour l'adapter à ce nouveau B&P ?

**Comment by nicolasdb** [comment]
faut que je cherche, j'avais fait une nouvelle version pour le B&P de Mai.
C'est sur le NAS: 
\\MEDIAHUB\OpenfabNAS\000WORK\1 la griffe\Visuel\Event

**Comment by Ginsburg** [comment]
Trouvé

**Comment by zuperninja** [comment]
Parfait ! Car c'est perdu dans les méandres de mes backup

**Comment by Ginsburg** [comment]
Voilà ce que ça peut donner : ![b p 22sept17](https://user-images.githubusercontent.com/7775797/29864217-4c4cf84e-8d72-11e7-8ec7-be85b1a1ca97.png)

Ça convient ?

**Comment by nicolasdb** [comment]
j'ai répondu dans #123
