### ISSUE TITLE
Événement : La rentrée ?

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#125]
# La rentrée
ref to file.md or #issue : #22 

## contexte
On commence à avoir quelques événements en Septembre, ne faut-il pas un événement spécial : "La rentrée" ? pour lancer les nouveautés, la nouvelle saison ?

## objectif
Annoncer la nouvelle gestion des membres, les différences entre "user", "super user", "meta user", ...

## proposition
On se greffe à un événement déjà prévu comme les portes ouvertes ou le b&p aquaponie ? Ou un tout nouvel événement, rien que pour ça, qui potentiellement pourra intéresser tous les membres et les réunir sur un temps plus court que les portes ouvertes ?

J'aime bien l'idée qu'il y a un événement dédié, seul soucis, ça fait un truc de plus à organiser.

**Comment by nicolasdb** [comment]
yeup, c'est vrai que ça fait bcp pour septembre. Octobre?
Est-ce qu'on relancerai aussi un BrainCandy?

**Comment by Ginsburg** [comment]
[Agenda de septembre](https://github.com/openfab-lab/openfab/blob/e7c1d9ce01f940fee7f03b13f851f2575eb42281/_event/agenda-septembre.md)

Je remets ici l'agenda de septembre qui peut nous aider dans la décision et surtout à voir que c'est bien rempli.

**Comment by nicolasdb** [comment]
houuuuuu, et comme évènement, on lancerai pas le *001 de lancédédé?

**Comment by softrevolter** [comment]
j'aimerais bien faire un Braincandy à Fermenthings, je peut: thème: homebrewing, cooking and hacking
