### ISSUE TITLE
label - modif de nom

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#127]
ref to file.md or #issue :
## contexte
Actuellement, j'ai tendance à utiliser 
- BUG/help
- Making
- et backoffice.

## proposition
Est-ce que dans le tas, on modifierai pas l'une des catégories par job/client? Le noir? c'est la catégorie la moins fun :p

**Comment by Ginsburg** [comment]
Est-ce qu'on ne peut pas jouer avec les noms donnés sur les boards de ZenHub pour faire le lien ?
Je pense surtout à "Done" (même sur ZenHub), "En cours" (In Progress), "À faire" (Icebox et Backlog), "Stuck" (Review/QA ?)

Enfin, c'est peut-être trop tôt pour faire une harmonisation de la sorte mais ça peut être intéressant pour réellement mettre en avant une méthodologie de project management propre à OpenFab.

**Comment by nicolasdb** [comment]
mais on a déjà ces labels là, les status en blancs. Tu veux les renommer aussi en fait?
Je parlais des labels de catégories.

**Comment by Ginsburg** [comment]
Je pensais que tu parlais d'un changement complet. Juste pour avoir une harmonisation et ne pas avoir 2 termes différents pour dire la même chose.

**Comment by nicolasdb** [comment]
l'harmonisation ne fait sens que pour ceux qui ont zenhub. 
mais je veux bien, autant faire des essais tant qu'on est pas bcp, plus facile.

**Comment by nicolasdb** [comment]
Zenhub est assez cool à utiliser. 
J'ai renommé 2 labels de catégories. 
Mais les collonnes de zenhub et les labels de status rentre un peu en concurrence. à voir comment faire plus de sens. N'oublions pas que la conséquence d'utiliser zenhub en mode gestion projet, perturbe pas mal l'inbox classique. Bcp d'issues sont des tâches assignées et ça ne fait pas bcp de sens pour quelqu'un qui n'utilise pas zenhub. 
On continue de tester.
