### ISSUE TITLE
Plus que 2 bières

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#128]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
2 c'est proche de 0
## objectif
24 c'est moins proche de 0
## proposition
Je peux aller chercher des bières demain au Delhaize.

**Comment by nicolasdb** [comment]
Punaise, t'es trop fort. 

![tenor](https://user-images.githubusercontent.com/12049360/29831833-a7327702-8ce6-11e7-9d5e-2e0c60775b08.gif)
