### ISSUE TITLE
Réunir toutes les informations Artisan 2.0

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#132]
- [ ] ref to file .md or pullRequest #: https://github.com/openfab-lab/openfab/blob/master/Missions/artisan%202.0.md 
*(à remplir quand l'issue est résolue)*
## contexte
Si je dois faire la coordination ou participer à celle-ci à distance, autant commencer par avoir un endroit unique avec le maximum d'infos pour pouvoir recouper tout ça en tâches simples et assignables.

## proposition
Un markdown avec tout dedans !

**Comment by nicolasdb** [comment]
je pense que c'est réunis dans #156 

Je clos celle ci.
