### ISSUE TITLE
Management projet Artisan 2.0

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#133]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
En lien avec #132, comment gérer Artisan 2.0 via GitHub ?

## objectif
Découper le projet pour le gérer efficacement.

## proposition
Comment fait-on pour le découpage du projet ?
Est-ce qu'on ne ferait pas une branche pour la globalité du projet + milestone pour chaque échéance, ça permet de gérer chaque session de workshop indépendamment, bien prévoir la logistique de chaque.

En gros branche "artisan" + 4 milestones pour session 1, session 2, session 3 puis hackathon.

Ça permet un premier découpage en bloc, après faut descendre au niveau issue, tâche. Je vais tenter de voir ce que ça peut donner.

Après, je sais pas trop si on tente les epic issue de zenhub.

**Comment by nicolasdb** [comment]
yes
on a causé de tout ça ce midi avec @DewiBrunet 

Je vais essayer de lister le résultat et pouvoir en tirer des tâches, des milestones et on peut, oui, tenter une issue epic pour artisant2.0, ça fait sens. L'intérêt de zenhub est aussi de lister les tâches et de tester les liens de dépendance entre elle 

Alors,
agenda:
- 16/17 sept . mini workshop teaser. 
  - lieu: OF   
  - on a besoin de liste d'inscription pour que les gens motivé après un teaser puisse déjà s'inscrire aux 3 dates suivantes. need: dates (ok), places (?) et lieu (?)
L'inscription au stage doit être confirmé par un paiement de 5 à 10€ qui finance un repas sur le tps de midi. Le reste du stage est gratuit mais les couts du repas garantis la venue des inscrits. 
need: prévoir un petit repas, on peut peut-être négocier quelque chose avec refresh, je pense qu'ils font des plats à emporter à 9€ mais ne sont pas ouvert le week-end.... on sait jamais. _https://www.facebook.com/refreshcommunity/_ contact: Laurent Dennemont
- 30sept et 1 oct. stage J1 et 2
  - lieu: ?   dépend du besoin d'équipement, nombre de pers. peut-être une question de zone "contrat de quartier"? demander confirmation à Usrsula _uadelsdorfer@ixelles.irisnet.be_ ou Isabelle _ilegrain@ixelles.irisnet.be_ 
    - soit OF, soit Baya (le nid, rue kercks), soit Communa (la serre, rue Gray)
      need: prendre contact avec l'un ou l'autre en fonction du choix.
    - nbre de place? quantité de matériaux et coût?
- 7/8 Oct: Dewi absent
- 14/15 Oct: stage J3 et 4
  - idem
- 21/21 Oct: stage J5 et 6
  - idem

- 20/24 Nov: 4jours de stage en mode hackathon. 
4 à 5 groupes de 5 pers. 
la proposition est de le faire chez Communa, rue gray. et de budgétiser x heures d'utilisation atelier bois chez Baya au nid et utilisation numérique à OF, Les équipes s'organisent pour répartir leur usage, gestion tps machine. 

nico absent 23-24 nov. >CHIC à stdenis.

**Bonus,** l'ideal serait de faire participer des artistes et artisants du quartier. ou encore des profs d'écoles sup.
todo: faire une liste des personnes de contact potentiels. 
Je pense déjà à "ErreurNotFound" dans le group openfab. Il est dans un atelier partagé au 23/25 rue du sceptre. 
Ursula m'a donné une liste de profs qu'on peut contacter et leur proposer le projet. Moi, j'en connais pas mais Dewi et AnneSophie et d'autres en sauront plus dans ce cas.
Il faut aussi penser à des "rewards" pour le hackaton. 
  - voir avec les profs si une note pourrait compter dans leur cursus
  - abo 2mois chez OF ou du tps machine. 
  - visibilité lors du recup day

- présentation publique le 25 Nov. lors du festival Recup'day  
https://www.facebook.com/events/1179395958819519/  
annonce de l'année dernière, pas encore vu pour cette année.

point de vue com, il va falloir faire le lien entre tout ça et mettre en avant les externalités positives. 
point de vue gestion, il ya là un bel exercice zenhub pour définir les dépenses et voir par quoi commencer. 
On s'est dit que contacter les profs ne devraient plus tarder. 
Pour ça: need: petit texte de présentation et comment ça s'organise et ce qu'il en ressortira?
idem pour sonder le potentiel d'utiliser le lieu de Communa et sous quel condition? Mais ils demanderons certainement directement "c'est pour combien de personne"

Ha et donc, dans tout ça, il ya  le budget. lien avec #114 
le but est de là aussi tester la gamification. 
il y a un budget total, un cout minimum dont j'ai mentionné les montants. 
Il reste 2 inconnues, le cout matériaux et de location lieu.  (ref: Baya a demandé pour le B&P 12€/h)
Ce qu'il reste peut être assigné à la coordination. 
Mais je pense aussi à la souplesse que peut apporter la gamificiation =
une tâche = routine + récompense.  
On apporte sur la table un montant € mais on en parlait avec Dewi, il peut préférer recevoir des Crrr pour pouvoir bosser sur la laser après que de faire une facture et être taxé dessus. 

Comment faire? 
On liste toutes les tâches, et lorsqu'on les assigne, chacun précise ce qu'il/elle attend en retour (badge animation, cartes DD, crrr, euro* [*metaUser]) et on fait le compte de ce qu'il reste comme budget à réallouer?

**Comment by nicolasdb** [comment]
sorry, c'était un peu long mais pas facile de tout mentionner.

**Comment by Ginsburg** [comment]
Long mais nécessaire, je peux reporter ça sur le document [Artisan 2.0](https://github.com/openfab-lab/openfab/blob/2b36591101c5d41dfb48ab4d2f0e0d7ce2b29399/Missions/artisan%202.0.md) pour avoir toute l'information facilement trouvable en 1 seul et même endroit, sauf si on considère que ça peut rester sur ton message.

**Comment by nicolasdb** [comment]
ha oui, si, t'as l'air d'avoir bien organisé les info, ce sera plus clair.
Et j'ai mis l'issue en Epic, maintenant, chaque tache associée s'ajoute à une liste qui se met à jours en fonction des issues open/closed.
Ce qu'il faut maintenant, c'est organiser les tâches et leur dépendance et les assigner,  1 pers. /tâche

**Comment by nicolasdb** [comment]
On en est où là? 
je me suis focalisé sur la prod de Minga. y a plus qu'à produire.

**Comment by Ginsburg** [comment]
De retour de Berlin, je vais pouvoir réavancer sur le sujet.

**Comment by nicolasdb** [comment]
génial,
Bien Berlin? 

De notre côté, je trouve qu'on a bien avancé avec @DewiBrunet sur les présentoirs, on essaye de valider le principe de budget et de rétribution à 2. 
On suit le tps que l'on passe et j'ai essayé des tâches dans zenhub, chronométrée via togll et tout ça. 
Ensuite, on se répartit les bénef au prorata du tps qu'on a passé chaqu'un.
Continuons de tester ces méthodes avec toi sur cet appel à projet.

**Comment by DewiBrunet** [comment]
Salut,

Le temps file et le 1er workshop Artisan 2.0 est dans 10 jours^^
J'ai revu tout ce qui a été documenté (bonne occasion d'essayer Zenhub aussi!).
C'est cool si @Ginsburg peut être sur le management, ça me permet de me donner à fond sur le contenu :) 

Je vais donc me consacrer les prochains jours sur :
- Définir le contenu/lieu/budget du 1er workshop (...et les suivants si possible).
- Ecrire un texte teaser pour la communication.
- Produire quelques visuels.
- Réunir une liste de contacts/réseaux d’intéressés (on a eu 5 emails de gens intéressés durant les portes ouvertes).

Vous voyez d'autres choses urgentes à faire?
Est-ce qu'on se fixe une deadline pour la communication? (qui reste un point essentiel si on veut avoir des participants^^).

Bien à vous depuis la planète pliage,
Dewi

**Comment by Ginsburg** [comment]
Hello @DewiBrunet, on peut s’appeler demain après 17h ? J'avoue qu'entre la recherche de boulot/autres missions et le retour au cadre lillois, bosser seul chez moi, j'ai pas réussi à me mettre à ça et j'en suis désolé. Je rattrape le tir cette semaine ! Du coup, un coup de fil pour faire le point sur la situation m'aiderait bien si tu as le temps ! Je vais plancher sur la communication demain.

**Comment by DewiBrunet** [comment]
Salut, oui aucun soucis pour s’appeler ce soir à 17h, on peux même se faire un skype.
Par ailleurs @Ginsburg, @nicolasdb, je viens de créer l'issue 158 : description des workshops + photos.
C'est encore trop long pour la com mais j'espère que c'est compréhensible et qu'il y a toutes les info...
https://github.com/openfab-lab/openfab/issues/158

**Comment by nicolasdb** [comment]
oui, c'est pas mal. 
J'aime bien les photos, c'est joli, ça donnera envie je pense.
