### ISSUE TITLE
Vélo M2 @OpenFab

### ISSUE THREAD

**Issue by milenasonneveld** [openfab-lab/openfab#134]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Vélo M2 joins OpenFab as a gilde. 
## objectif
Realising the flow for hiring the Vélo M2 project.
[Planning a People Pedal Powered Event .pdf](https://github.com/openfab-lab/openfab/files/1274584/Planning.a.People.Pedal.Powered.Event.pdf)
## proposition
1. Organisational workflow
2. Autonomous system
3. Documentation OSH
4. Return on investment
5. Community
6. Monkey-proof
7. Realizing projects
## ressources
Yannick, Milena, Florent, some days a week.
First working system of energy platform on cargo bike, powered by ordinary bicycles on stands, for generating renewable energy for open-air cinéma, mobile fablab, coffee bar and promo stand.
Crowdfunding campaign wit GinGo.

## Resultats
The story of a person interested by the project, comes one day to an event or a discovery day, learns how to set up the system and how to drive the bike, then organises an event independently.
### rewards
A benevélo T-shirt, vrijwilligersvergoeding (€32 for the event)

**Comment by nicolasdb** [comment]
cool, I have printed twice the pdf, it could be usefull to talk about velom² during les portes ouvertes

**Comment by nicolasdb** [comment]
ok, vieux dossier ça. sept 2017, je ferme.
