### ISSUE TITLE
Milena @OpenFab

### ISSUE THREAD

**Issue by milenasonneveld** [openfab-lab/openfab#135]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Milena vervoegt OpenFab als deel van de gilde van Vélo M2.
## objectif
Vélo M2 uitleenbureau maken.
picoprojector project realiseren.
## proposition
Vélo M2 repository with organisaties workflow, finishend of proto, OSH documentation, events organising, opening en resolving issues, making the system monkey proof, preparing for futur projects.
Picobeamer powered by 1 bicycle, with sound, raspberry based, portable on a bike trailer.
## ressources
Skills - electromechanical engineering, renewable energy, project management, ultimaker 3D printing.
2 days a week

## Resultats
Making the People Pedal Power concept of Vélo M2 accessible to a larger public.
Discovering Mali during the winter months jan-march 2018 with the picoprojector. 
### rewards
Joy !

**Comment by nicolasdb** [comment]
Welcome :)
I'll add this in english, sorry for my dutch is so poor.
I have start a branch to work on the guild concept.
https://github.com/openfab-lab/openfab/blob/guildOF/_space/guildes-openfab.md

Last but not least, this is a "reminder" on the workflow we all should follow to work on this github.
https://guides.github.com/introduction/flow/
