### ISSUE TITLE
ElectroDude

### ISSUE THREAD

**Issue by DCElectroMaker** [openfab-lab/openfab#137]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## Presentation:
Cem DOGDU
## Capabilities:
-Electronic
-Robotic
-PCB etching
-3D Print
## Github:
https://github.com/DCElectroMaker
## Facebook:
Coming soon

**Comment by nicolasdb** [comment]
PCB **etching** not eatching ^^ :p
