### ISSUE TITLE
Jouons sur les mots

### ISSUE THREAD

**Issue by DCElectroMaker** [openfab-lab/openfab#138]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte

construction du readme 

## objectif

Précision sur les projets des membres et d'OpenFab

## proposition

dans la section **MAKE** où sont cités notemment la jacqueline et le projet aquaponics remplacer **MAKE** par **Members projects** ou **collaborations**

**Comment by nicolasdb** [comment]
Les dossiers avaient, il y a longtps, été créér sur base d'une analyse reprennant 5 grand channels d'activité pour le fablab. 

![image](https://user-images.githubusercontent.com/12049360/52636452-e8799900-2ecc-11e9-88c4-51a4aff5844b.png)

aujourd'hui, on a bien évolué, le concept de team remplace +- ces 5 cat. 

La suite et changement de structure sera propagé et discutée sur le repo RTFM.

**Comment by nicolasdb** [comment]
Issue moved to [openfab-lab/rtfm #15](https://github.com/openfab-lab/rtfm/issues/15) via [**ZenHub**](https://www.zenhub.com/)
