### ISSUE TITLE
[Concours Robot]

### ISSUE THREAD

**Issue by DCElectroMaker** [openfab-lab/openfab#147]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte

Salut à tous,
Voilà déjà un petit bout de temps que l'idée d'organiser un concours de robot. J'ai déjà pas mal d'idées sur le plan technique mais il me reste encore pas mal de zones d'ombres sur le plan organisationnel.

## objectif

Créer un groupe de travail pour l'organisation.

## proposition
Si vous êtes intéressé:  
1) Signalez vous ici ou sur facebook (cf. groupe de l'openFab  [Concours Robot])
2) J'ai déjà commencé un doc en ligne modifiable en guise de brainstorming, n'hésitez pas à le compléter ;) (Le lien autorise les modifications)  
https://docs.google.com/document/d/15qOn1lWaMz7aVX4Fzw6mBoZY81TlVHM-oVfv2sz8JpU/edit?usp=sharing

**Comment by nicolasdb** [comment]
bon, on est pas prêt pour organiser des concours. 
Personne ne réagit aujourd'hui à ces annonces là, idem pour les makerfaire. 
Je pense que c'est lié à un communication qui loupe les motivateurs adaptés à notre communauté. 
Qui sont quoi? ce n'est pas encore clair.
