### ISSUE TITLE
horaire d'ouverture non synchronisée

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#148]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
msg via facebook
> Bonjour, je cherche des infos sur les heures d'ouverture. Le site mentionne en semine de 9h à 18h, votre page FB de 9h à 17h et sur google, je vois des heures d'ouverture le week-end. Pouvez-vous me donner les heures d'ouverture exactes? Un grand merci.

## objectif
unifier les horaires
## proposition

Je propose de corriger et remettre à 9-18h sur facebook mais je sais pas comment faire pour google, c'est où? qqun peut aider?

**Comment by zuperninja** [comment]
C'est mon adresse syntonie qui a les droits de modification. J'ai ouvert à contact et Nicolas. 
Il faut aller dans Google MyBusiness -> Accueil -> Modifier (le bouton bleu en haut à droite près des infos)

**Comment by nicolasdb** [comment]
et tu as fais la modif ou pas?

**Comment by nicolasdb** [comment]
ok, j'ai trouvé et c'est modifié. 
il y avait samedi et dimanche en trop. :p
