### ISSUE TITLE
Liste contacts Artisan 2.0

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#156]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
### individuels

- info@juliencarretero.com (designer connu, professeur à ENSAV La Cambre)
- anastaoia.Dupont@gmail.com
- charlotte.garda@yahoo.fr
- e.vanwambeke@gmail.com
- brigitte.raoult@skynet.be

### réseaux à cibler

- contacts OpenFab : Baya, Communa, 
- PointCulture (liste de 40000 contacts d'après Bertrand)
- contacts Dewi : Faculté d'architecture La Cambre-Horta, Ecole secondaire Saint-Luc Bruxelles, origamistes belges...
- contacts Anne-Sophie : 

## Artistes/artisants/profs interessés pour co-animer les workshops
- ErreurNotFound
- Liste profs de Ursula

**Comment by nicolasdb** [comment]
j'ai reçu tout ça de Ursula

> Bonjour Nicolas,
> 
> Voici ce que j'ai en stock pour le moment.
> 
>     **Directeur de l'école des arts d'Ixelles** : 
> 
> Directeur : Jacques
> info@ecoledesarts.be
> zackvdh@gmail.com
> 
>     Directeur Saint-Luc  Secondaire
> 
> Directrice : Mme. Axelle Galand
> 
> a.galand@stluc-bruxelles-sec.be
> 
> Directrice adjointe : Mme. Marie-Laure Mouffe
> ml.mouffe@stluc-bruxelles-sec.be
> 
> Responsable discipline :
> Stéphanie Bétrancourt
> stephanie.betrancourt@gmail.com
> 
>     Direction Saint -Luc supérieur
> 
> Direction
> Directeur : Marc Streker + cv
> Directrice adjointe : Danielle Leenaerts + cv
> 
> Conseil et accompagnement pédagogique + coordination qualité
> Cécile Dujardin
> tél. : +32 (0)2 533 08 88
> 
>     Edmond Peters : Via Marco de Quartier Libre
> 
>     Contact élèves de la Cambre
> 
> infolacombine@gmail.com
> 
> 
>     Artisans 
> 
> artisan    Juan Vandepute        0488/76.78.98    
> artisan    Damien Moreaux        0470/54.99.27   
> artisan    Laetitia De Nève        0479/31.68.03    
> artisan (meuble)    Sophie Usuwiel    sophieusuwiel@gmail.com    0479 58 17 13     
> Belge Une Fois    Natacha    natacha@belgeunefois.com    0494/23.61.58    
> Créations végétales    Sandrine de Borman        02-646 43 04    
> Ebeniste     Jean-Pierre Nys    nysjeanpierre@gmail.com    02/640.73.33 - 0470/03.98.03    
> Officina créativa        info@officinacreativa78.eu
> Recy K    Nicolas Lambillon    Nicolas.Lambillon@arp-gan.be
> Tournevie    Olivier Beys    Olivier@tournevie.be    02/340.09.61 - 0473/77.06.24
> Tout-en-recup    Ognev Vlaminck    ognev@maximalisme.be    0478/20.94.09  
>

**Comment by Ginsburg** [comment]
J'ai aussi envie de partager à Bon Jour Bruxelles, ils ont pas mal de créatifs d'après Silvia.
Et pourquoi pas auprès de [LesDebrouillardes](https://www.facebook.com/LesDebrouillardes/).

**Comment by DewiBrunet** [comment]
Isabelle de la commune, fera passer une pub sur ses réseaux. Faut préparer le petit texte avec les info et une photo. + les liens complémentaire. ilegrain@ixelles.irisnet.be
Anne d'habitat et rénovation. Ils ont aussi une mailing liste de gens du quartier. C'est elle qui me demandait pour septembre. cqdm.hr@misc.irisnet.be
et les heureux nouveaux aussi sont demandeur de news à transmettre à leur communauté.
lheureuxnouveau@gmail.com

**Comment by Ginsburg** [comment]
Ceux pour qui il n'y a que le numéro de tel, je peux essayer de les appeler ?

**Comment by Ginsburg** [comment]
J'ai aussi publié sur Bruxelles for rêveurs- Brussels forever, un groupe autour de l'insolite, la créativité, ...
Je vais faire sur OuiShare quand je serai accepté sur le groupe.
J'en ai un autre qui s'appelle Artiste, artisan, créateur, ici votre espace pub (toute la belgique j'ai l'impression, mais bon, il y a un peu de monde dessus)
Un dernier qui est juste sur les événements de Bruxelles, pas super quali mais bon, ça demande pas trop de temps.

**Comment by Ginsburg** [comment]
- artisan Juan Vandepute 0488/76.78.98 (pas de réponse)
- artisan Damien Moreaux 0470/54.99.27 (pas dispo mais j'ai son mail : dmn.moreau@gmail.com)
- artisan Laetitia De Nève 0479/31.68.03 (pas de réponse pour le moment)
- Créations végétales Sandrine de Borman 02-646 43 04 (pas de réponse)
- Alexandra Garin - PointCulture (pas de réponse)

**Comment by DewiBrunet** [comment]
Mmmh pas sur que le tel soit hyper efficace... mais cool tes partages sur Fb :) 
@Ginsburg tu saurais dire ce soir (et jeudi/vendredi soir) combien sont inscrits? (ou donner l'accès au weezevent)

**Comment by Ginsburg** [comment]
Comme ce sont des artisans du quartier, ce sont possiblement les plus intéressés, ça n'est pas trop chronophage :)

J'ai mis vos adresses pour que vous receviez les notifications en cas d'inscription mais c'est vrai que comme il n'y en a toujours pas eu, vous ne pouvez pas suivre le nombre d'inscrit.

Je vous donne les identifiants du compte par message privé.

**Comment by nicolasdb** [comment]
Suite à un coup de téléphone d'Anne d'habitat et rénovation (et c'est une personne pas con du tout) qui préparait la newsletter, et elle me dit que l'idée d'un stage d'1 jour proposé 2x sur le week-end, n'est pas clair pour bcp de gens tel qu'on en parle.

Je relis l'event du coup, 

> Infos pratiques, première session de workshops :
> - Date : début 10h, soit samedi 31/09/17, soit dimanche 01/10/17

Est-ce que ça ne laisse pas un doute sur est-ce que c'est un stage dont la date n'est pas encore fixée?
Est-ce qu'il ne faudrait pas créer des events séparé avec une date très spécifique, sans parler de choix dans les titres mais ajouter un lien qui signale que d'autres dates sont possibles aussi. ? lien vers les autres events.

Dans la billetterie, c'est plus clair, il y a la sélection dans l'agenda.  Pas besoin de créer plusieurs billetterie donc.

**Comment by nicolasdb** [comment]
huhu, je relis un peu les échanges. 
Ouais, le téléphone c'est hasbeen

**Comment by Ginsburg** [comment]
Je sais pas pourquoi je ne peux pas modifier le texte de l'événement, il y a un message d'erreur.
Sur l'événement, il y a les 2 séances qui apparaissent en bas tout de même mais c'est vrai que c'est pas super clair.

**Comment by nicolasdb** [comment]
j'ai modifié l'adresse mail d'Isabelle Legrain isabelle.legrain@ixelles.brussels
il y a déjà un fichier .md avec les contacts validé?
J'ai un autre mail qui retourne une erreur. mais je sais déjà plus avec qui... à surveiller.

**Comment by Ginsburg** [comment]
J'ai fait une liste là : https://github.com/openfab-lab/artisan2.0/blob/master/Communication/Liste-de-diffusion.md

**Comment by Ginsburg** [comment]
This issue was moved to openfab-lab/artisan2.0#13
