### ISSUE TITLE
Contenu workshops (texte et visuels)

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#158]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Il faut décrire le contenu des workshops Artisan 2.0.

## objectif
Créer un texte pour la communication (avec des photos).

## proposition
**Artisan 2.0 description**

Dans le cadre du contrat de quartier Maelbeek, une série de workshops sur le thème « artisan 2.0 » sont proposés. Les workshops sont mis en place par l’OpenFab, écosystème 100% indépendant qui mutualise les capacités de chacun pour être catalyseur d’innovation et de créativité. L’autogestion, le croisement des disciplines et la recherche par expérimentation sont essentiels dans ce FabLab. Les workshops seront encadrés par Nicolas De Barquin, FabLab manager, Dewi Brunet, artiste plieur et Paul Le Coz, chef de projet.

Artisan 2.0 vise à partager des passions et des savoir-faire manuels en mettant à disposition les opportunités offertes par les outils numériques.

Le pliage sera le fil conducteur de cette série de workshops. La pratique du pliage (notamment l’origami) permet de créer des volumes-surfaces repliables aux potentiels incroyables : bijoux, nœud papillon, capuche repliable, robe, costume, parapluie, lampe, cloison, paroi insonorisée, abri portable, décors…
 
![dsc03567](https://user-images.githubusercontent.com/25649502/30801240-f11c9080-a1e2-11e7-9430-613e42f5c9fe.JPG)

Le pliage nécessite une extrême précision et rigueur. Heureusement, les outils numériques disponibles aujourd’hui sont d’une grande aide pour faciliter la pratique et aller plus loin dans les applications. La découpe-laser est un outil simple à manipuler qui permet de découper, graver, préparer des formes avec une précision parfaite. Idéale pour créer des « moules à prépliage » pour origamis ou des « métiers à plisser » pour plier du textile. La robotique avec Arduino permettrait de créer des origamis réagissant à différents stimuli pour s’allumer, se replier, prendre vie.

Venez participez aux ateliers Artisan 2.0 pour apprendre le pliage de papier, de textile, de carton… ; s’essayer aux outils numériques et découvrir l’univers des FabLabs. Tout le monde peut participer à la nouvelle révolution industrielle, il suffit de vouloir faire, be a maker !

3 séries d'ateliers thématiques par week-end.
Inscription à la journée, de 10 à 17h.
10€/Jour comprenant le repas du midi.
Inscription limitée à 8 participants par jours (ou à 10 si 2 animateurs ou à + si autre part ?)

Samedi 30 Septembre et Dimanche 1 Octobre
Samedi 14 et Dimanche 15 Octobre
Samedi 20 et Dimanche 21 Octobre
+ Hackaton 4 jours du 20 au 24 Novembre 

Contact et versement : nicolas@openfab.be

![visu 4x2](https://user-images.githubusercontent.com/25649502/30801143-941571ae-a1e2-11e7-818c-b52a8f07cc02.jpg)

**Teaser workshop 30 sept-01 nov** :

Workshops Artisan 2.0 par OpenFab

Artisan 2.0 vise à partager des passions et des savoir-faire manuels en mettant à disposition des outils numériques. Le pliage est le fil conducteur de cette série de workshops.

Venez apprendre des techniques d’origami pour plisser du tissu. Le plissage permet de créer des textiles à mémoire de formes pour diverses utilisations : bijoux, nœud papillon, capuche repliable, robe, costume, lampe, cloison, paroi insonorisée …

Le matin sera consacré à une initiation à l'art du pliage et du plissage (les outils, les techniques).
L'après-midi sera l'occasion de développer vos projets.

Venez avec vos idées, sinon nous en avons plein en fonction de vos envies ;)
Un matériel de base sera offert et libre à chacun de ramener d’autres tissus.

Venez participez aux ateliers Artisan 2.0 pour apprendre le pliage, s’essayer aux outils numériques et découvrir l’univers des FabLabs. Tout le monde peut participer à la nouvelle révolution industrielle, il suffit de vouloir faire, be a maker !

![visu 1 2](https://user-images.githubusercontent.com/25649502/30801165-a35214c4-a1e2-11e7-9f14-e6de2951d13f.jpg)

## références

[OSME] (International Conference on Origami in Science, Mathematics, and Education)(http://www.langorigami.com/article/origami-conferences)

Videos :
[Between the Folds](https://www.vanessagould.com/between-the-folds): documentaire sur l'origami et ses liens avec l'art, les sciences et l'éducation
Robert J. Lang's TEDTalk "[The math and magic of origami](https://www.ted.com/talks/robert_lang_folds_way_new_origami )".

**Comment by Ginsburg** [comment]
Vraiment bien, la seule chose que je suis pas sûr d'avoir compris c'est le côté même workshop sur les 2 jours. Je ne sais d'ailleurs pas trop comment l'exprimer clairement.

**Comment by Ginsburg** [comment]
J'en profite pour le passer sur Meetup aussi pour toucher le groupe ou pas la peine ?

**Comment by nicolasdb** [comment]
attention donc!
le concept est en fait super simple. 
C'est un workshop d'**un seul** jour. 
mais il y a le choix entre samedi et dimanche lors de 3 week-end. Total 6 jours individuel de stage.

Est-ce que les gens peuvent faire plusieurs jours? je ne sais pas. je ne pense pas, sauf s'il y a de la place.... 
à poser comme question à Isabelle de la commune.
