### ISSUE TITLE
Poubelle à verre pleine

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#16]
La poubelle à verre déborde, comment ça se passe pour les dégager? 

Je propose de m'en occuper.

J'ai créé un post dans le dossier Event, étant un évènement, une action. Bien ou bien?
https://github.com/openfab-lab/openfab/blob/master/Events/Trash-Glass.md

**Comment by nicolasdb** [comment]
Voilà, c'est vidé.
J'ai créé un post dans le dossier Event, étant un évènement, une action. Bien ou bien?
https://github.com/openfab-lab/openfab/blob/master/Events/Trash-Glass.md

**Comment by softrevolter** [comment]
Voici la boucle que moi j'avais en tête

il y a un problème a resoudre dans le large terme du mot (quelque chose a faire pour le fablab, a construire, a réparer. De la plus petite mission a la plus longue quête) 

Quelqu'un peut alors dire: eh mais c'est mission intel et mettre le lien vers la mission. 
Si la mission n'existe pas il peut y avoir deux possibilité: Créer la mission ou juste répondre si le problème est immédiatement résolut. 
Donc voici la boucle:

-> créer un issue = 1 D3 trow 
-> montrer le chemin vers la mission pour réussir le issue = 1 D3 trow
-> résoudre immédiatement la issue dans la discussion = 1D6 trow
-> créer la mission = 1D6 trow
-> créer la mission et la solution (documenter) = 2D6 trow

**Comment by nicolasdb** [comment]
pourquoi tu as remis la tache dans la TODO?

**Comment by softrevolter** [comment]
@nicolasdb je voulais tester comment ça marche, tu as reçu une notification?

**Comment by nicolasdb** [comment]
je reçois en tout cas les notifications sur les issues. J'ai pas fait attention pour le changement de collonne DONE to TODO

**Comment by nicolasdb** [comment]
ok, bon donc cette tâche est résolue.
this fix #16

**Comment by nicolasdb** [comment]
flute, ça marche pas comme ça. c'est dans les commits que ça doit se placer. 
https://guides.github.com/features/issues/#notifications
