### ISSUE TITLE
Presentation - Yago

### ISSUE THREAD

**Issue by BoomCorp** [openfab-lab/openfab#160]
# Presentation - Yago

## Context

Hey! I'm a spanish sound engineer. I record and edit sound for film but what brings me to Open Fab is my passion for making stuff and mainly my portable boombox project. I've been building portable bluetooth speakers into suitcases and other unusual housings for a while and I believe Open Fab can help grow and improve my project

## Objective

I'm hoping to benefit from Open Fab's community by interacting with its members, learning and sharing skills and ideas that could help improve my projects or bring new opportunities to the table.

## Proposition

For the moment I'm discovering both the facilities and the community and I still have to find out how to fit my project into Open Fab.

And here I am attempting to become a Super User.
I can allready feel the powers...

**Comment by nicolasdb** [comment]
yeah, welcome

You can star the repo jacqueline. There is not yet a lot but we all need to start somewhere ;)
https://github.com/openfab-lab/la-jacqueline

And I have start a branch to work on the guild concept. 
It's more for the "Guild Master" but still good to know. 
https://github.com/openfab-lab/openfab/blob/guildOF/_space/guildes-openfab.md

Last but not least, this is a "reminder" on the workflow we all should follow to work on this github.
https://guides.github.com/introduction/flow/
