### ISSUE TITLE
Artisan 2.0 - S1 - Event Fb

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#161]
- [ ] ref to file .md or pullRequest #:  
- Event Fb : https://www.facebook.com/events/1087093074759920/
## proposition
Utiliser #158 pour faire un texte format event Fb + création de l'event en privé pour modification.
Je me suis permis pas mal d'adaptations, sûrement les vieilles habitudes et un peu de benchmark pour voir comment font les autres.

**Comment by Ginsburg** [comment]
Évent Fb :

Visuel : 
#163 

Nom de l’évènement : 
Workshop # 1 Artisan 2.0 par OpenFab

Lieu : 
OpenFab

Date/Heure : 
30/09/2017 - 10h
01/10/2017 - 17h

Description : 
INFOS PRATIQUES :
- Date : début 10h, soit samedi 31/09/17, soit dimanche 01/10/17
- Inscription obligatoire : 
- Prix : 10€
- Participants : 8 maximum

---

Artisan 2.0 vise à partager des passions et des savoir-faire manuels en mettant à disposition des outils numériques. Artisan 2.0 est l'occasion d'explorer les possibilités que peut apporter la technologie aux techniques traditionnelles artisanales. Comment réaliser ses projets plus efficacement ?

Journée en 2 parties : 
- matin : découvrez le travail de Dewi Brunet, artiste plieur et artisan 2.0, au travers d'une initiation à l'art du pliage et du plissage. Vous apprendrez des techniques d’origami pour plisser du tissu  Le plissage permet de créer des textiles à mémoire de formes pour diverses utilisations : bijoux, nœud papillon, capuche repliable, robe, costume, lampe, cloison, paroi insonorisée … Un matériel de base sera offert et libre à chacun de ramener d’autres tissus.

- après-midi : devenez artisan 2.0 en développant vos projets, découvrez comment les outils numériques peuvent vous venir en aide. Venez avec vos idées, sinon nous en avons plein en fonction de vos envies ;)

---

Venez participer aux ateliers Artisan 2.0 pour apprendre le pliage, vous essayer aux outils numériques et découvrir l’univers des FabLabs. Tout le monde peut participer à la nouvelle révolution industrielle, il suffit de vouloir faire, be a maker !

Artisan 2.0 c'est aussi 2 autres sessions de workshops pour aller plus loin : 
- 14/15 octobre
- 21/22 octobre
+ 20/24 novembre : un format 4 jours (hackathon) pour tenter vos projets. Plus d'infos à venir sur la page OpenFab !

Artisan 2.0 a lieu dans le cadre du contrat de quartier Maelbeek de la commune d'Ixelles.

**Comment by Ginsburg** [comment]
L'événement est en privé avec le visuel actuel, je le passerai en public si ça convient : https://www.facebook.com/events/1087093074759920/
Je ne peux pas mettre OpenFab en organisateur par contre, @nicolasdb tu dois être le seul à pouvoir faire ça : 
- en dupliquant l'événement, le passant en public 
<img width="933" alt="capture d ecran 2017-09-25 a 23 02 26" src="https://user-images.githubusercontent.com/7775797/30830998-2fa89c5a-a246-11e7-909e-43ef1dac3af9.png"> 

- puis en choisisant OpenFab comme organisateur 
<img width="983" alt="capture d ecran 2017-09-25 a 23 09 03" src="https://user-images.githubusercontent.com/7775797/30831113-9451d2d4-a246-11e7-9f7a-5021f4e4661c.png">

**Comment by Ginsburg** [comment]
J'en profite pour le passer sur Meetup aussi pour toucher le groupe ou pas la peine ?

**Comment by nicolasdb** [comment]
sisi, mais attention au total de réservation, faut bien centraliser pour ne pas dépasser le nombre d'inscrit/jour. meetup à son propre système d'inscription, faut pas que les gens mélangent et qu'on leur renvoie une confirmation d'inscription. un truc du genre.

+ 3 mailing list à ne pas oublier. 
- Isabelle de la commune, fera passer une pub sur ses réseaux. Faut préparer le petit texte avec les info et une photo. + les liens complémentaire.  ilegrain@ixelles.irisnet.be 
- Anne d'habitat et rénovation. Ils ont aussi une mailing liste de gens du quartier. C'est elle qui me demandait pour septembre. cqdm.hr@misc.irisnet.be
- et les heureux nouveaux aussi sont demandeur de news à transmettre à leur communauté.
lheureuxnouveau@gmail.com

**Comment by Ginsburg** [comment]
Du coup, voilà le meetup, j'attends que tout soit bien validé et je le partage aussi. https://www.meetup.com/fr-FR/FabCity/events/243673249/?eventId=243673249

**Comment by nicolasdb** [comment]
note concernant les logos partenaires, voici ce que m'avais répondu Isabelle pour le B&P de Juin: 

> Hello,
> De notre côté, il faut effectivement mentionner :
> - dans le cadre du Contrat de Quartier Durable Maelbeek
> - avec le soutien du Collège des Bourgmestre et Échevins de la Commune d'Ixelles et de la région de Bruxelles-Capitale.
> Dans la convention, tu as l'ensemble des mentions précisées.
> Pour moi, le soutien de Baya n'est pas nécessaire. Il s'agit d'un local "atelier partagé", mis à disposition par la Commune, dans le même cadre ;-)
> On se voit demain soir !
 
logo au choix en fonction du graphisme.
![cqd_sign2013_bil_ndg](https://user-images.githubusercontent.com/12049360/30857906-dea9b0f0-a2bd-11e7-866c-429aed42cdda.png)
![cqd_sign2013_bil_rgb](https://user-images.githubusercontent.com/12049360/30857907-deaa0014-a2bd-11e7-9fe0-310e560c970f.png)
![cqd_sign2013_fr_ndg](https://user-images.githubusercontent.com/12049360/30857911-deae3382-a2bd-11e7-97aa-34b34f9ffa3a.png)
![cqd_sign2013_fr_rgb](https://user-images.githubusercontent.com/12049360/30857909-deac9ff4-a2bd-11e7-8968-f214e68babd8.png)
![logoxl-horizontal-cmjn](https://user-images.githubusercontent.com/12049360/30857908-deabe834-a2bd-11e7-921d-ecc20b8ac804.jpg)
![logoxl-horizontal-fond-cmjn](https://user-images.githubusercontent.com/12049360/30857910-dead8612-a2bd-11e7-85ff-753de9af156b.jpg)
![logoxl-horizontal-fond-noir](https://user-images.githubusercontent.com/12049360/30857913-dec1db76-a2bd-11e7-80a5-184563efdb1e.jpg)
![logoxl-horizontal-noir](https://user-images.githubusercontent.com/12049360/30857912-debef618-a2bd-11e7-99a2-8dec912fad1b.jpg)

**Comment by DewiBrunet** [comment]
L'event est créé : http://bit.ly/2y5ZoCj 
On peux fermer cette issue et l'a mettre en md du coup? (j'ai envie de test ça^^)

**Comment by Ginsburg** [comment]
@DewiBrunet libre à toi :)

**Comment by nicolasdb** [comment]
attention, 
n'oublie pas de mentionner le lien vers le fichier .md en haut du premier post.  (est-ce que tout le monde à le droit d'éditer les posts? moi oui :p )

Reward +5crrr pour le .md

**Comment by DewiBrunet** [comment]
Désolé de réouvrir ça mais ca me parait plus facile de repartir d'ici pour les prochaines session de workshops.

**Comment by Ginsburg** [comment]
This issue was moved to openfab-lab/artisan2.0#12
