### ISSUE TITLE
Artisan 2.0 - S1 - Billetterie

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#162]
- [ ] ref to file .md or pullRequest #: 
- Billetterie en ligne : https://www.weezevent.com/artisan2-0
## proposition
Création d'un événement sur Weezevent (solution connue, moins chère qu'Eventbrite, que j'ai déjà utilisé) : 0,99€ par billet, ça reste un coût mais comme le temps presse, je vais opter pour ça, à la limite je prends ce sur-coût sur moi, je verrai si moins cher pour la prochaine session.
## ressources
@nicolasdb : il va juste me manquer les coordonnées bancaires d'OpenFab pour que les inscriptions y soient reversées.

**Comment by Ginsburg** [comment]
Voilà la billetterie en ligne : https://www.weezevent.com/artisan2-0

**Comment by nicolasdb** [comment]
les coordonnées sont ici
http://openfab.be/adhesion

il faut juste mentionner autre chose comme communication. 
genre: artisan20

**Comment by Ginsburg** [comment]
Finalement je vais pas fermer l'issue tout de suite, juste envie d'avoir votre retour avant.

On continue sur Weezevent ?
On demande plus d'infos grâce au formulaire ? 
- Lieu de vie ? Demander s'ils habitent le quartier de Maelbeek (est-ce que c'est bien identifié ? on peut donner les lieux qui entourent le quartier) ?
- Préférences alimentaires ?

**Comment by DewiBrunet** [comment]
Je penses que c'était bien Weezevent et facile pour gérer 2 journées séparées non? (seul hic faut payer mais ça va non?)
Si on peux demander plus d'info c'est mieux : nom de la rue où vous habitez et avez-vous des préférences alimentaires.

**Comment by Ginsburg** [comment]
This issue was moved to openfab-lab/artisan2.0#11
