### ISSUE TITLE
Artisan 2.0 - S1 - Visuel

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#163]
- [ ] ref to file .md or pullRequest #: 
- Visuel retenu : https://user-images.githubusercontent.com/7775797/30859228-0756d7bc-a2c3-11e7-9786-078fa268bd2a.png
## proposition
Refaire un visuel sur la base de celui des B&P en ajoutant un bandeau avec les logos de la commune, d'OpenFab (autres ?)

**Comment by Ginsburg** [comment]
Voilà le visuel, il est éditable en ligne directement par [ici](https://www.canva.com/design/DACiE4JnfRM/share?role=EDITOR&token=34_oMuhCPNlIp6XhOdiA8Q&utm_content=DACiE4JnfRM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton). J'ai préféré prendre ce visuel car il montre le côté techno derrière même si ce n'est pas la découpeuse laser. J'ai du tout reprendre de zéro car le visuel b&p n'est que sur le NAS donc le visuel de background sort de google image et ne correspond pas à celui habituel, le changement peut se faire très facilement.

**Comment by Ginsburg** [comment]
Vu avec Dewi pour un visuel plus axé sur le textile 
![artisan 2 0 1](https://user-images.githubusercontent.com/7775797/30857025-8c0439f4-a2ba-11e7-8386-ecdadbbbecbb.png)

**Comment by DewiBrunet** [comment]
J'ai proposé ça plutôt (pour avoir le côté "fait machine" et "fait main")
![untitled-1 copy](https://user-images.githubusercontent.com/25649502/30859009-37c59e7a-a2c2-11e7-9ad0-041851fc831f.jpg)

**Comment by Ginsburg** [comment]
![artisan 2 0](https://user-images.githubusercontent.com/7775797/30859103-8a14d218-a2c2-11e7-906d-a6c44113679c.png)

**Comment by Ginsburg** [comment]
Du coup, j'ai fait avec celle qui tu m'avais envoyé sur Fb avec la main et le textile inversé mais sinon ça donne ça : 
![artisan 2 0 1](https://user-images.githubusercontent.com/7775797/30859228-0756d7bc-a2c3-11e7-9786-078fa268bd2a.png)

**Comment by DewiBrunet** [comment]
Super, je valide!

**Comment by Ginsburg** [comment]
On prend le temps de refaire un visuel avec ceux sur le NAS ou alors je repars de celui-là ?
Je pensais ajouter "Workshop02" pour le prochain, peut-être avant le "thème", pour marquer l'idée que c'est tout un projet et pas un événement isolé.

**Comment by DewiBrunet** [comment]
Je penses qu'il faudrait refaire un visuel si on change de contenu (à priori une serre).
Je propose d’acheter un petit géranium et d’aller prendre une photo à l’entre-deux pont avec la serre ou dans le quartier sur une plante de rue.

Pour les sessions j'aurais mis à droite de "Artisan 2.0" un "hashtag2" (*!èµù$ c'est quoi le code pour mettre le hashtag sans lien?).

**Comment by DewiBrunet** [comment]
Voila les images que je propose, à choisir les 2 meilleures. 

![dsc03595](https://user-images.githubusercontent.com/25649502/31178091-51d64934-a918-11e7-8d3a-29f1afb94b8f.JPG)
![dsc03599](https://user-images.githubusercontent.com/25649502/31178092-51dc703e-a918-11e7-8147-2a8b6a31453c.JPG)
![dsc03605](https://user-images.githubusercontent.com/25649502/31178093-51f1cf7e-a918-11e7-9b1c-1165d15b156a.JPG)

**Comment by Ginsburg** [comment]
This issue was moved to openfab-lab/artisan2.0#10
