### ISSUE TITLE
Artisan 2.0 - S1 - Communication mail

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#164]
- [ ] ref to file .md or pullRequest #: 
- Une liste de diffusion ici : https://github.com/openfab-lab/artisan2.0/blob/master/Communication/Liste-de-diffusion.md
- Le mailchimp ici : http://mailchi.mp/33faf64d28ed/viens-dcouvrir-lartisanat-20-lors-dun-workshop-97001
## proposition
Écrire un texte tout prêt à être envoyé
Un envoi massif avec l'adresse d'OpenFab ?

**Comment by Ginsburg** [comment]
On peut le visualiser ici : http://mailchi.mp/7e5d41081086/viens-dcouvrir-lartisanat-20-lors-dun-workshop

On pourrait demander aux contacts de la liste de le transférer en leur ajoutant un petit texte d'intro du genre : 

"Bonjour xxx,

Dans le cadre du contrat de quartier Maelbeek, une série de workshops sur le thème « artisan 2.0 » sont proposés. Les workshops sont mis en place par l’OpenFab, FabLab 100% indépendant qui mutualise les capacités de chacun pour être catalyseur d’innovation et de créativité. Ces temps permettront une réflexion autour de l'apport de la technologie, des outils numériques pour l'artisanat, la fabrication, la création, ...

Étant donné, ... [petite phrase de contexte en fonction de la personne ciblée], nous nous sommes dits que l'événement pourrait t'intéresser, ou que tu pourrais partager la suite de ce mail à ton réseau, ...

La première session aura lieu dès ce weekend, 2 créneaux sont possibles : soit le samedi, soit le dimanche de 10h à 16h. Toutes les informations pratiques se trouvent dans la suite du mail, le lien d'inscription, ... Attention, il n'y a que 8 places !

Merci par avance,
xxx"

**Comment by nicolasdb** [comment]
ha ben, je viens juste d'ajouter les mails de contacts pour envoyer sur les mailings listes du quartier.

**Comment by DewiBrunet** [comment]
Les mails ont été envoyé aux 18 contacts de https://github.com/openfab-lab/openfab/issues/156 + 2 mails de diffusion.
Pas hésiter à transférer le mail à d'autres intéressés/diffuseurs potentiels ;)

**Comment by Ginsburg** [comment]
Ceux pour qui il n'y a que le numéro de téléphone, je peux essayer de les appeler ?

**Comment by DewiBrunet** [comment]
Je viens de relancer par mail les 5 personnes qui étaient intéressés lors des portes ouvertes.

**Comment by nicolasdb** [comment]
j'y pense, Camille était intéressée aussi mais on ne lui en a jamais reparlé cette semaine :p 
camillevierin@gmail.com

**Comment by Ginsburg** [comment]
Le mailchimp marchait bien ou plus simple ?

**Comment by DewiBrunet** [comment]
c'était bien, faut juste faire quelques modifs sur le texte.

**Comment by Ginsburg** [comment]
This issue was moved to openfab-lab/artisan2.0#9
