### ISSUE TITLE
Artisan 2.0 - S1 - Repas

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#165]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## proposition
J'appelle demain Refresh (contact: Laurent Dennemont), voir si possible WE + prix (voir si prix de groupe) + voir quand il faut avoir nombre précis d'inscrits.
Ensuite :
- soit si c'est possible et prix convient : Refresh
- soit rechercher équivalent Refresh
- soit imaginer repas faisable rapidement (buffet CIN ? salades variées), --> prévoir achats + préparation (vendredi ?)

**Comment by nicolasdb** [comment]
ce qu'on peut aussi faire, de plus convivial, c'est de commander chez l'heureux nouveau quelques panier bio et cuisiner quelque chose ensemble.
On disait avec anne sophie que commencer avec une intro théorique soutenu de quelques exemples puis enchainer sur le repas, permettrait d'avoir se moment convivial pour poser des questions et papoter sur les idées sans perdre de tps. 
Ensuite, on reprend début d'aprem avec l'atelier pratique ayant épuré toute les questions et probablement de bonnes idées pour démarrer. 

http://www.lheureuxnouveau.be/
j'ai un compte chez eux, on peut faire son shopping en ligne et ils livrent le vendredi matin chez nous.

**Comment by Ginsburg** [comment]
J'ai un peu adapté le texte pour faire une 4ème partie dans la journée pour coller à cette idée : 

"Journée en 4 parties : 
- matin : découvrez le travail de Dewi Brunet, artiste plieur et artisan 2.0 qui mêle technique traditionnelle et technologie pour aller plus loin dans son travail.

- midi : et si on cuisinait ? un temps de convivialité, discussion autour d'un bon repas : quels sont vos projets ? comment pourrait-on utiliser la technologie dans vos projets ? comment le FabLab peut vous aider ?

- début d'après-midi : essayez-vous à l'artisanat 2.0 et apprendrez des techniques d’origami pour plisser du tissu ce qui vous permettra de créer des textiles à mémoire de formes pour diverses utilisations : bijoux, nœud papillon, capuche repliable, robe, costume, lampe, cloison, paroi insonorisée … Un matériel de base sera offert et libre à chacun de ramener d’autres tissus.

- fin d'après-midi : devenez artisan 2.0 en développant vos projets, découvrez comment les outils numériques peuvent vous venir en aide. Venez avec vos idées, sinon nous en avons plein en fonction de vos envies ;)"

Du coup, j'ai presque envie de reculer l'heure de démarrage pour avoir un 10h30 ce qui donnerait une timeline du genre, tout à fait à titre indicatif : 

| Heure   |      Activité      |
|----------|:-------------:|
| 10h30 - 10h45 |  arrivée des participants | 
| 10h45 - 11h15 |    intro par Dewi   | 
| 11h15 - 11h45 | préparation repas |
| 11h45 - 13h00 | repas / échanges |
| 13h00 - 14h30 | apprendre les techniques origami  |
| 14h30 - 16h00 | exploration pour projets persos  |

**Comment by DewiBrunet** [comment]
Bonne idée de cuisiner, ce sera moins cher et plus convivial! J'ai juste peur que ça nous bloque trop de temps mais à nous de choisir la recette - vous avez déjà une idée?

Journée en 4 parties c'est bien, ça fait plus pro, je laisserai 10h par contre (et si les gens arrivent en retard non soucis, ce sera la partie théorique).

**Comment by nicolasdb** [comment]
oui, faut trouver une idée et faire la liste des courses. 
J'avais oublié que c'était déjà ce week-end, c'est trop tard pour l'heureux nouveau

**Comment by Ginsburg** [comment]
Pour ça, je peux faire des courses ce soir et amener ça demain à Bruxelles. Une idée de repas sympa à préparer ? 
Mais est-ce qu'on essaye pas de réunir tout le monde le dimanche où il y a 2 inscriptions contre 1 le samedi ?

**Comment by DewiBrunet** [comment]
Nico proposait de faire des courses demain matin (on sais jamais p-e qu'il y aura des participants imprévus^^). A priori ce serait poisson/riz.

Je penses que c'est pas pro de demander aux participants de changer de jour. Et c'est pas un soucis, on va pouvoir tester des trucs, prendre le temps d'améliorer d'un jour à l'autre...

Tu viendrais demain du coup? (tu peux faire semblant d'être un participant pour tester ;p)

**Comment by Ginsburg** [comment]
Comment faire pour les prochains ? C'était très bien comme ça mais est-ce que @nicolasdb peut être là à chaque fois ? Ou alors préparation en amont voire commande de plat déjà préparé ?

**Comment by Ginsburg** [comment]
This issue was moved to openfab-lab/artisan2.0#8
