### ISSUE TITLE
Benevélo weekend / Vélo M² 10-12/11

### ISSUE THREAD

**Issue by milenasonneveld** [openfab-lab/openfab#173]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*

## contexte
Notre projet Vélo M2 à comme but de promouvoir l'utilisation du vélo cargo dans l'espace publique comme moyen de transport et de faire sentir son propre énergie renouvelable par les vélos générateurs. Depuis 2015 nous avons fait plus de 30 actions et événements en Belgique, France, Suisse et Hollande. Nous arrivons au moment où nous avons une expérience solide des évènements qu’on veut partager avec des personnes qui veulent s’impliquer et s’approprier le projet. Et c'est la que vous intervenez: les benevélos.

## objectif
L'idée est de vous introduire au monde de Vélo M2: cinéma en plein-air, fablab mobile, action dans l'espace public, vélo cargo, énergie renouvelable. Tout vous sera introduit pendant ce weekend d’émerveillement à OpenFab, qui est notre partner in crime pour la réalisation de nouvelles concepts.

## proposition
-- Programme --

Date: 10 - 12 Novembre
Inscription: info@velom2.be

Vendredi:

**Pour tout.e.s**
19h - 20h : Drink de bienvenu et faire connaissance 
20 - 23h : Braincandy sur la thématique de la transition écologique (le braincandy est un moment de partage de chaîne et vidéo Youtube autour d'une thématique)

Samedi:

10h - 11h : Petit déjeuner collectif offert par le projet Vélo M2
**Pour les intéressé.e.s dans le plateforme**
11h - 13h : Session 1 - introduction au multitude de fonctionnalités de Vélo M2 et le potentiel des prochaines années. 
13h - 14h : Manger ensemble
**Pour les intéressé.e.s dans les évènements**
14h - 18h : Session 1 - apprendre à rouler un vélo cargo,
Session 2 - mettre en place un cinéma ambulant, 
Session 3 - faire une impression 3D avec sa propre énergie généré.
**Pour tout.e.s**
19h - 22h :  Cinéma Sauvage - action dans l'espace public : projection du film “Paths Of Glory” sur la place de la liberté.
22 - 23h : Remise des badges des Benevélo’s.

Dimanche:

**Pour les intéressé.e.s makers**
11h - 14h: Session de co-creation - introduction à la technologie qui fait tourner Vélo M2, apporter son amélioration ou réparation créative des modules de Vélo M2.
14h - 16h: Session de vision - sur la suite des actions.
**Pour tout.e.s**
16h - 18h: Drink de fin de weekend !

Pratique:

Adresse de Open Fab : Avenue de la Couronne 274, 1050 Ixelles
Numéro de contact durant le weekend : Milena 0497253918
Nourriture : on vous offre le petit déjeuner le samedi et une boisson les soirs, les pintjes sont à €1,5.
Dormir : pour les personnes qui n’ont pas d’hébergement à Bruxelles, nous pouvons arranger des couch et matelas pour la nuit de vendredi à samedi et la nuit de samedi à dimanche.

## ressources
Florent et Milena se mobilisent pour organiser le weekend.
Qui d'autre ?

## Resultats
Concrètement tout participant peut obtenir un badge 'apprenti PPP' (People Pedal Power).

### rewards
Tout aide pour l'organisation est bienvenue ! On distribue des cartes de bières/thé :
- pour assistance au bar 
- pour organiser un petit-déjeuner ou repas végétarien
Nico donne des points :
- pour nous introduire au lasercutter !

**Comment by milenasonneveld** [comment]
@softrevolter can you handle the film for the 11th ?

**Comment by milenasonneveld** [comment]
@nicolasdb comment l'annoncer sur Meetup ?

**Comment by nicolasdb** [comment]
ok, déso pour le silence radio. Octobermake c'est avéré plus chargé que prévus, très positif. 

pour meetup, faut que je retrouve mes codes d'accès mais @softrevolter et @Ginsburg ont déjà les droits pour ajouter un event ou ajouter une personne dans les organisateurs. 
donc first step:
- [ ] organiser le contenu avec une image, (ou plus, c'est quoi les limitations meetup?)
- [ ] ajout sur meetup. par quelqu'un qui a accès. ou te donner les accès. 


Seconde remarque:
pour délivrer un badge, il faut d'abord le définir :)
J'ai commencé un template de ce type, mais ce template est lui même encore à améliorer. ^^
https://github.com/openfab-lab/pack-openbadge-fablab/blob/master/badge-src/badge-template.md

Je n'ai pas encore pris le tps de creuser mais il faut préparer le terrain pour se rapprocher des standards de définition d'openbadge. 

![image](https://user-images.githubusercontent.com/12049360/32163071-65492566-bd5b-11e7-8ff4-f08d60feca30.png)

**Comment by nicolasdb** [comment]
Evenement cloturé. 
Issue cloturée.
