### ISSUE TITLE
Beers needed 

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#176]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
j'ai soif mais il y a plus de bière :'(

## objectif
Acheter des bières

## proposition
Aller à l'échoppe du coin pour s'approvisionner (en profiter pour racheter du sucre et du liquide vaisselle).
On garde les tickets de caisse quelque part pour la compta?

**Comment by nicolasdb** [comment]
j'avais documenté ça il y a longtps et le fichier avait disparu. 
Le voilà restauré.
