### ISSUE TITLE
Infini Fab , un fablab en devenir

### ISSUE THREAD

**Issue by Jorgininho** [openfab-lab/openfab#177]
## contexte
Debut Décembre je m'en viens à bxl pour que l'on discute ensemble entre futur collègues :)
## objectif
revoir ensemble le github, la gamification, le projet vulca
-edit-
Definir une structure documentaire pour permettre d'alimenter un catalogue de produit

**Comment by Jorgininho** [comment]
Le fond du travail de ce catalogue consiste à creer un template qui imposera un format et une structure documentaire pour s'assurer que le produit peut etre reproductible ou bien realisé dans different fablab

**Comment by Jorgininho** [comment]
https://github.com/Jorgininho/Fablab-Catalogue

**Comment by looisjl** [comment]
Hello, on a prévu avec @milenasonneveld et @BoomCorp de mettre en place une nouvelle manière de structurer/documenter un projet de fabrication avec Github et autres outils. On se voit vendredi matin chez OpenFab si tu es dispo participe avec nous? Ta note est intéressante, je réfléchis à qqch de similaire.

**Comment by nicolasdb** [comment]
yeah, 
:D

**Comment by Jorgininho** [comment]
yess, maleheuresement vendredi matin je suis pas dispo :/ 
Un moment la semaine prochaine peut-etre ? @looisjl

**Comment by Jorgininho** [comment]
L'idée c'est finalement de s'inspirer de ce qui se fait au niveau des secteurs "Qualité" de grand groupe industriel. Ces systèmes de qualités leurs permettent de reproduire un même poduit à different endroit et par differente personne. 
Le point de départ, à mes yeux, sur cette reflexion est de s'interroger sur le cycle de vie d'un produit. 
Dans l'industrie, le cycle de vie utilisé pour un produit est le cycle en V
![image](https://user-images.githubusercontent.com/10775713/33378808-51551c36-d516-11e7-881c-809e3ffdc6ed.png)
ça peut etre une base pour s'inspirer sachant que l'on peut grandement réduire la 2eme branche du V qui se concentre sur du test et de la validation (utile quand on fait de la production de masse).
J'ai imaginé ci-dessous un cycle de vie d'un projet afin de determiner comment structurer le template du catalogue.

DIY Project Lifecycle |   |  
-- | -- | --
STEPS | SUPPORT | Presentation in Catalog
Idea / Concept of the product | Text Document | Template document- Intro to present the need- Presentation of the concept- Person implicated in the conception- Project of inspiration
Modeling of the concept | Specific technical files | Template for a list of the technical files used, each files shall be tagged.Therefore a list of tags shall be proposed with the catalog template.
Schematics of principles | Specific technical filesOr Text document | Template for a list of the technical files used, each files shall be tagged.Therefore a list of tags shall be proposed with the catalog template.For Text documentation, a template to present:- the theories used- the reasoning- the results
Manufacturing / Machining | Specific technical files | Template for a list of the technical files used, each files shall be tagged.Therefore a list of tags shall be proposed with the catalog template.
Assembly | Specific technical filesOr Text document (manual) | Template for a list of the technical files used, each files shall be tagged.Therefore a list of tags shall be proposed with the catalog template.For Text documentation, a template to present:- The material needed - The competences (taaags!!)- A template step (number/description/results)
Test & Validation | Text & Images | A template document to present the final product for helping the sharing of it

**Comment by Jorgininho** [comment]
Comme mentionné ci-dessus, Concernant le stockage des fichiers techniques, le seul template que l'on peut mettre en place c'est un listing de ces fichiers.
En plus de ces listing on pourrait proposer des tags (taaaags!
![image](https://user-images.githubusercontent.com/10775713/33382641-90add994-d521-11e7-9a7d-87a19203c539.png))

Ce tableau sera bien plus grand que ce que je vous présente aujourd'hui puisqu'ici il faudrait pouvoir taguer toutes les étapes d'un projet ainsi que tout les fichiers.

Name | Type | Description
-- | -- | --
Fusion360 | Soft | use of Fusion360 Software
3DModeling | Competence | competences in 3D Modelisation
CNC | Machine | use of a CNC Machine
CNC-Conf | Competence | configuration of a CNC machine
Lasersaur | Machine | Use of the Lasersaur
Lasercut | Competence | Use of a lasercut machine
Anet A10 | Machine | Use of Anet A10 3D printer
3DPrinting | Competence | Use of a 3D printer
Cura | Soft | Use of the Cura slicer
Manual screwing | Competence | Use of manual screwing assembly
Manual sewing | Competence | Use of manual sewing assembly
Electronic Soldering | Competence | Use of electronic soldering
screw driver | Machine |  
saw | Machine |

**Comment by milenasonneveld** [comment]
@looisjl we can try to implement directly the documentation with the proposition above !

**Comment by Jorgininho** [comment]
@milenasonneveld I reworked a bit the template for the catalogue, would be great if I could see that with you this week at the openfab, will you be available like one hour ?
I'm not sure its ready to document your project (it is supposed to be able to document all projects) so your input is welcome :)

**Comment by milenasonneveld** [comment]
Hi This week will be more difficult, are you there next week ?

--
Milena Sonneveld

M • info@velom2.be
T • +32 (0) 497 253 918
[image: http://www.velom2.be] <http://www.velom2.be>
Project Vélo M² <http://www.velom2.be> - feeling renewable energy

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/43474218-8810ad70-94f2-11e8-89e0-005929757fb9.png)

@Jorgininho 
Je sais plus où on en était mais j'ai simplifié à 8 le nombre de domaines pour débuter. 
Les gens viennent d'abord pour: 
- laser
- 3D print
- Textile (souvent en lien avec le laser...)

Ensuite, t'as besoin de compétence en
- CAD et CAM (les logiciels)
Puis l'électronique (les leds, la soudure, arduino, etc...). il y a moins de gens qui viennent que pour ça. 

En dernier. C'est l'informatique. Tout ce qui touche réseau, adresse IP, installer un OS ou le configurer. 
C'est déjà un peu plus avancé, pour des bricoles sur base de rasberry. 


Ensuite, 2 domaines important mais pour lesquels les gens ne viennent pas. 
Ils sont en support et à un moment donné sont obligatoires lorsqu'on veut donner un cours. 
- le 101. C'est les basics and safety. Bien savoir comment réagir en cas d'accident, comment se protéger et surtout éviter les accidents. \+ les bases des outils, savoir mesurer au pied à coulisse, comment on se sert d'une pince à bec, un taraud ou encore les astuces pour forer droit et les types de têtes de vis dedjeuuu. 


ou pour pouvoir rentrer dans une team
- github, . Afin de pouvoir rapidement intégrer une équipe et faciliter le travail à plusieurs. 


Les autres domaines, comme la CNC, ça vient plus tard, dans les niveau supérieur. C'est plus compliqué et faut déjà CAD/CAM et une habitude du laser ou de l'impression 3D c'est pas mal. 
Le reste, on verra en fonction des besoins. 

Sur ce, je clos cette issue. Elle a pas bougé depuis 8 mois. 
bisous.
