### ISSUE TITLE
Timelord - bidule physique pour changer de task

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#188]
- [ ] ref to file .md or pullRequest #: .................................................  
https://github.com/nicolasdb/nicolasdb.github.io/issues/21

## contexte
J'essaye de gagner mes points de TimeLord et même si je le fait un peu, par période via Toggl. J'aimerai m'améliorer.
Comme d'habitude, prendre une nouvelle habitude, c'est pas facile et c'est plein de petites embuches qui sont très efficaces pour ne pas que t'y arrive. ddjeu.
## objectif
J'avais trouvé ceci:
![image](https://user-images.githubusercontent.com/12049360/34565173-0b05db8e-f15a-11e7-8a00-1c680d93bb4f.png)
https://timeular.com/

Mais c'est quand même un peu cher et ça vient avec un logiciel dont une version pro est en supplément... mouais.

du coup.
Si quelqu'un ça motive ou si vous avez des idées. 
Je continue le sujet sur mon site.

**Comment by Jorgininho** [comment]
Tu m'avais parlé d'un cube avec pour chaque face une tâche précise
peut etre utiliser ces capteurs
https://www.amazon.fr/gp/product/B075GPMBH4/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=4527896-21&camp=1642&creative=6746&linkCode=as2&creativeASIN=B075GPMBH4&linkId=4a361f346deb5c9d479cd63bcc9995ac
avec un arduino qui stock le timing pour chaque tâche, quand tu fais de la laser, tu le met la face "laser", pour le capteur indique à l'arduino que c'est la face "laser", et ça compte le temps où cette face est visible :)
bref ça demande un peu de développement, en tout cas de chouette capteur qui me font envie (hmmmm le mercure^^)

**Comment by nicolasdb** [comment]
oui, j'a trouvé des pistes, j'en parle plus en détails sur mon post
https://nicolasdb.github.io/post/time-tracking/
Au final, mon bloquage est surtout niveau connection API toggl

**Comment by Jorgininho** [comment]
API toggle ?
tiens cette video qui m'y a fait penser 
https://www.youtube.com/watch?v=Z7Sc4MJ8RPM
32 fonctions !!

**Comment by Jorgininho** [comment]
Tiens en gardant ce truc en tête et voulant faire mumuse avec mon arduino j'ai fais un 1er proto qui pourrait t'interresser
![20180223_170621](https://user-images.githubusercontent.com/10775713/36603837-589f0904-18bc-11e8-8a22-ea419ef9f25e.jpg)
![20180223_170633](https://user-images.githubusercontent.com/10775713/36603838-58b45994-18bc-11e8-8ee0-045dba584eb0.jpg)
En gros tu as le choix pour mesurer le temps sur 10 tâches (0 à 9). Tu selectionnes la tâches que tu fais puis tu appui sur le bouton, quand la LED est verte, ça décompte du temps sur la tache selectionnée. Tu rappui pour arreter le décompte.

C'est pas aussi sexy qu'un machin qui par wifi va changer directement sur toggle (encore qu'il devrait avoir moyen dans une version plus poussée), ici il faudrait à côté avoir une petite fiche pour te dire à quelle tâches correspond le numéro.
Qu'en penses tu ?

**Comment by nicolasdb** [comment]
c'est classe. 
J'aimais mieux l'idée d'une série de bouton plutôt qu'une sélection rotative mais c'est pareil niveau code. 
C'est cool. 

Tiens, regarde ça

**Comment by Jorgininho** [comment]
ben une boite avec des boutons :)
Là je me demandais si t'avais le module carte SD pour les arduino ?
Parce que là j'essayes d'envoyer les timing via l'USB, mais c'est pas évident :/

**Comment by Jorgininho** [comment]
yop, bon ben j'ai cramé mon afficheur 7 segments -_-
C'est con j'avançais bien, enfin je vais partir pour un truc qui affiche 4 chiffres, le 1er indquera la tache en cours et les 3 chiffres restants le temps accumulés en minutes. Et je selectionnerais la tache avec le potar (tu pourras rajouter des boutons sans soucis :p )
à ce stade le temps sera stocker dans une variable sur l'arduino, donc reset quand tu tron OFF/ON. Du coup je pensais utiliser un module avec une carte SD pour stocker le timing dans un fichier Excel.
Le côté API interface avec Togl me parrait une usine à gaz, je partirait plutôt sur ce genre de solution dans un 1er temps : 
https://support.toggl.com/csv-import/
Une fois ça en place, je pense que je ferait mumuse avec des puces rfid pour remplacer l'afficheur et le potentiometre :)
