### ISSUE TITLE
opportunity - mobilier VW combi à développer

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#189]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Mon copain Roland, il vend des combi VW type 2 qu'il ramène des USA. 
http://www.rolandsbusfarm.com/
![image](https://user-images.githubusercontent.com/12049360/34606955-a5c1d2ce-f211-11e7-9092-086471490b9c.png)

Il aurait encore bien de la demande pour des meubles customs pour l'aménagement intérieur de ces vieux bus. 
## objectif
Si quelqu'un est chaud, c'est une débouchée potentielle à développer. Il sera ravi de trouver des clients.
un bus clean roulant se vend entre 10 et 15k€. 
Il a des demandes de restauration complète et custom qui peuvent monter à 30k€ le bus. 
C'est un domaine de niche où il y a encore de quoi faire.

## proposition
Openfab peut aider pour
- la mise en contact, 
- l'usage machine
- conseil pour le design
- un bus est à disposition rue du Sceptre
- l'encadrement structurel 

Ceci en échange d'un deal win-win à convenir, soit % soit autre chose à convenir.

**Comment by Jorgininho** [comment]
C'est quoi le deal? Faire de le design interieur des combi ? En sous traitance avec ton pote rolland?

**Comment by nicolasdb** [comment]
Ouais, design et production des éléments en cnc ou laser. 
Ils pourraient de leur côté faire la promo et les installations dans les bus. 
C'est un vieux dossier donc faut proposer quelque chose et en reparler.
