### ISSUE TITLE
Soirée/évent "lancer Dédé"

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#19]
Comment gérer l'assignation des crrr provenant des lancé de dé en récompense des actions.
Pourquoi pas organiser de manière régulière un moment festif où l'on lance les dés qu'on a remporté précédemment. 
- Ça crée un moment de rencontre, 
- Il y a reconnaissance des actions remplies, 
- C'est plus fun d'être ensemble pour les lancer, et d'assister aux epic fails mais aussi aux epic wins. 
- occasion aussi de voir les projets en cours 
- motive les membres à passer Super User.
- automatise même peut-être l'organisation de cet événement puisque ce sera sous traité en issues et en nombre de lancé de dé. 
- et ultimement ça évitera la fraude parce que les lancé seront public. 

Haaaa j'ai hâte d'y être.

**Comment by nicolasdb** [comment]
Valeur des tâches et relation avec LancerDéDé
https://github.com/openfab-lab/openfab/wiki/Procedures

**Comment by nicolasdb** [comment]
c'est intéressant ce graph sur la probabilité des résultats suivant le nombre de dé qu'on lance. 
https://fr.wikipedia.org/wiki/D%C3%A9#/media/File:Probabilite_nd6.png

Idéal pour les tâches supérieures où une valeur moyenne à quand même plus de probabilité d'être obtenue mais n'empèche pas un EpicFail ou un EpicWin  🎲

**Comment by nicolasdb** [comment]
c'est intéressant ce graph sur la probabilité des résultats suivant le nombre de dé qu'on lance. 
![image](https://user-images.githubusercontent.com/12049360/204021233-996ba866-4424-440f-9a90-9f4ac433740b.png)


Idéal pour les tâches supérieures où une valeur moyenne à quand même plus de probabilité d'être obtenue mais n'empèche pas un EpicFail ou un EpicWin  🎲  

![gif](https://media.giphy.com/media/5LVUDTb6S6fgQ/giphy.gif )

**Comment by nicolasdb** [comment]
Reste aussi à définir comment fait-on pour enregistrer l'info des tâches accomplies.
Je pense souvent aux tombola, les gens achètent des tickets qui donnent une chance d'un gain qui est tiré au sort lors d'un évènement. **LANCERDéDé**

Donc, par exemple, lorsque j'ai trié et sortis les poubelles, je pense que ça serai facile de collecter une carte reprenant la valeur de la tâche. Dans ce cas, 1D3 (no skills, no time.... well, là j'ai mis 30min parce que j'écris ceci et j'ai téléchargé, imprimé et afficher les infos de tri et les jours de sortie) 
Bref, en attendant un truc tout numérique, un ticket à jouer lors du LANCERdédé, ça serai simple je pense.

Bon, faut faire des cartes valeurs. Qui s'y collent?

**Comment by softrevolter** [comment]
Ceci à eté ajouté à TODO Gestion Buro274 pour la partie: 
**Création de Carte valeurs** demandé par @nicolasdb

**Comment by nicolasdb** [comment]
# holalalalalala, j'ai eu une idée!
![d-lxwvvt1wak6qvd4wbqrlanlhst9f9wh3nj0fp-fh1fzbxolh1ucje2_-dxucsk1ffglgnnhjfb_cw41xh5jsrujd06gaivinfr5lcxqffbxnvn2sq2bpdwfct0mhaxusrrhepb6vk66g0rnxh7jelfqkm6rnjfobmryusapishq_pcatsm508js8zdfoiyfdjpgnbzk_tz_zujpzy](https://user-images.githubusercontent.com/12049360/27146314-386ebaee-5139-11e7-817e-6de2678c0bcd.jpg)

Non mais attend... 
Donc, on reprend les cartes mana de Magic. 
On a donc nos 5 catégories:
- Plaine
- Forêt
- Montagne
- Marais
- île
*Faudra voir pour notre 6ème cat pour le backoffice.*

Pour les plaines, j'ai peut-être 5 ou 6 illustrations différentes. Pas compté pour le reste, j'en ai plein.
1 Illustration par valeur de dé, suivant les quantités disponibles. Bcp = D3, rare = D40 (j'en sais rien, j'invente)
J'ai des étiquettes qui sont pil poil la largeur. c'est du 63.5x38.2mm mais il existe du 63.5x33.9 qui seront peut-être mieux... à voir. 

On remplit une mission, on obtient des cartes mana/Dé 
Une mission 3d6= 3 cartes D6 (levelUp: de la catégorie de la mission )
![white-mana-symbol](https://user-images.githubusercontent.com/12049360/27147158-0d5accbe-513c-11e7-9063-b60d04e96563.png)

Allez, je remplis le fichier.md

**Comment by nicolasdb** [comment]
Bon c'est pas clair celle ci; elle mélange déjà plusieurs sujet. 
Je la réouvre pour son sujet principal, organiser un évènement récurant pour lancerdédé.
Du coup, je lui ai assigné le type:Backoffice.
Bien ou bien? C'est une case événementiel... c'est un peu du backoffice non?

**Comment by nicolasdb** [comment]
J'ai lancé un appel à la communauté facebook.

Et c'est aussi inclu  en TODO dans le projet Gestion buro274

Du coup, je clos cette issue, elle n'a qu'à revenir si rien ne se passe. La soirée devra se créer si nous voulons gagner des crédits. :)
