### ISSUE TITLE
laser - tarif prépayé

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#190]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
suite au changement de tarif, 
nouvelle politique de prix, nouvelle façon de compter. 
Pour éviter de courir après les membres APRES les jobs, vérifier qui a payé, qui n'a pas encore payé et combien. 
pour éviter d'oublier de chronométrer. 
## objectif
- Organiser différemment la gestion d'utilisation laser
- Introduire la logique d'activation de la machine via une "clé" par la suite, ce sera le passeport maker et le badge laser qui donnera accès.
- prépayer plutôt que de faire crédit et récupérer les dettes.
- Activer la communauté des utilisateurs. 
## proposition

![image](https://user-images.githubusercontent.com/12049360/34883120-f78bfe70-f7b8-11e7-8f11-f2d19582ffe4.png)

Il serait cool d'avoir une encoche où glisser la carte et que toutes les X minutes, une encoche soit emportée (grignotée). 
Si un capteur lumineux n'est pas obstrué par une encoche encore présente,
il y a détection d'une encoche valide, et activation de la machine via un relai. 
Une engrenage peut-être une visse-sans-fin qui entraînerai à la fois la carte via les encoches déjà découpée et arracherai l'encoche vierge. 
Ce, avec une rotation équivalent à une encoche toutes les X minutes. 

![image](https://user-images.githubusercontent.com/12049360/34884213-5beb97a6-f7bc-11e7-870e-390a21e6ad46.png)

Les cartes sont prédécoupées par laser. 
La machine contrôlée par arduino, les pièces imprimées 3D suffiraient. 

## ressources
Achat de disque "engrenage" = carte prépayée. 
10 encoches détachable
1 encoche = 1 unité à définir suivant le prix d'achat.
*Actuellement, j'vais introduit 40€ pour la carte dont l'unité d'encoche valait 5€, = 30 min de laser*
En regardant la liste des utilisations laser, la moyenne haute des utilisations est de 1h.
- Si on compte par tranche de 5 min, 
```
10 encoches x 5 min = 1 valable pour 50 min.
40€/h, 40/60x50 = 33,33€ la carte. 
```
- Si on compte par tranche de 10 min, 
```
10 encoches x 10 min = 1 valable pour 100 min.
40€/h, 40/60x100 = 66,66€ la carte. 
```
- Si on compte par tranche de 15 min, 
```
10 encoches x 15 min = 1 valable pour 150 min.
40€/h, 40/60x150 = 100,00€ la carte. 
```

## Resultats

Une machine fonctionnelle. 
Une upgrade possible vers le passeport ou une combinaison des 2. Passport pour validation RFID du badge laser + conso prépayée.
### rewards
Badge 3D (correspondant au soft) + badge ElectroMéca ( à définir)
100 crrr + 2 Dé20

**Comment by DewiBrunet** [comment]
On a le matos? (capteur lumineux, relai, visse-sans-fin, arduino...)
On a le skill? (programme pour activer la machine avec une carte prépayée/passeport)

Niveau valeur de la carte c'est bizarre d'avoir 50/100/150 min. Je pense qu'il faut que ce soit pour 1h sachant que c'est la moyenne haute des utilisations. Du coup ce serait une carte prépayée à 40€. Faut juste adapter les encoches (2? 4? 6?).

Faudra aussi prévoir une solution si un job fait genre 200 minutes.

![prepare-the-laser](https://user-images.githubusercontent.com/25649502/37493173-5292fcee-28a4-11e8-9664-e96d6053e8bd.jpg)

**Comment by nicolasdb** [comment]
oui, on a les skills, c'est en soi pas très compliqué. 
Les engrenages peuvent s'imprimer, l'électronique, c'est basique. juste un capteur qui active un relai.

les 50/100/150 c'etait juste pour me faire une idée des différences. Je ne pense pas qu'il faut proposer 3 tarifs. 

Par contre, depuis la proposition, le principal problème est "quid lorsqu'un job est plus long que prévu", la laser s'arrête? est-ce qu'on peut charger une carte neuve?

Je pencherai actuellement plus pour une sorte de clé d'activation que tu ne reçois qu'avec le badge ou que tu te fabrique comme challenge validant que tu sais utiliser la laser. 
Si tu n'as pas le badge, tu n'as pas la clé d'activation et donc, tu dois trouver un mentor qui peut te guider et utiliser sa clé. 

Reste la question des cartes prépayées, ça pourrait être un boitier à part, non relié à l'alimentation de la machine. Ce serai plus souple. 
je sais pas.....

**Comment by nicolasdb** [comment]
ok, 
donc on laisse tombé tout ça, ça arrivera bien une fois passé au numérique. 

Par contre. 
Objectif en attendant: 
- [ ] Une nouvelle feuille de timing avec
   - [ ] soit c'est payé en cash, encaissé et indiqué "payé en cash"
   - [ ] soit c'est payé en crrr, +1 génial et on indique "nicely done"
   - [ ] soit c'est par virement, on édite alors une facture et indique le numéro de facture "OF-Bxxx"
- [ ] une checklist facturation toujours ouverte sur l'ordi laser dans le coin.
= level up +1 en devis vente pour le responsable atelier.

Comme ça on sait exactement quel est le statut de chaque période d'usage.

ok?

**Comment by nicolasdb** [comment]
Good, @Anou92 est en charge de surveiller les comptes laser. 

Un carnet a été dédié à la compta laser, pour plus jouer avec des feuilles volantes. 
![image](https://user-images.githubusercontent.com/12049360/45104865-3bd40800-b133-11e8-9769-32a96d3c6f01.png)

et dedans, pareil
![image](https://user-images.githubusercontent.com/12049360/45104965-7d64b300-b133-11e8-97fc-3895fc376437.png)

## MAIS
il manque tjs le statut: 
- [ ] soit c'est payé en cash, encaissé et indiqué "payé en cash"
- [ ] soit c'est payé en crrr, +1 génial et on indique "nicely done"
- [ ] soit c'est par virement, on édite alors une facture et indique le numéro de facture "OF-Bxxx" (avec V si payé)

Sans ça. Nous n'avons tjs pas de clarification quand à la méthode choisie de payement, ni son statut. 
Ce n'est pas grave si ce n'est pas payé tout de suite, mais il faut communiquer la décision. 

_On va définir aussi que la formation est bien inclue/gratuite dans les 20crrr._

**Comment by Anou92** [comment]
yes demain je passe au fablab et je vais compléter les statuts

**Comment by nicolasdb** [comment]
ok, ça marche plus ou moins bien. 

J'ai _re_-commencé une doc sur le RTFM https://github.com/openfab-lab/rtfm/issues/4
Je me rend compte que j'avais déjà fait tout ça ici. -soupir-

La nouvelle habitude à prendre.  https://github.com/openfab-lab/rtfm/issues/2#issuecomment-469655550
---
- Où est-ce qu'on range le PQ? >RTFM
- C'est quoi les status de l'asso? >RTFM
- Comment j'encode ma note de frais? >RTFM
- Elle coute combien la maes au frigo? >RTFM!
- c'est quoi ce RTFM? > RTFM!!!

![image](https://user-images.githubusercontent.com/12049360/54599829-c333f980-4a3b-11e9-97cd-128fa89a8bce.png)
![image](https://user-images.githubusercontent.com/12049360/54599872-dfd03180-4a3b-11e9-8bed-47f68cf757a1.png)
![image](https://user-images.githubusercontent.com/12049360/54600075-46ede600-4a3c-11e9-8557-66aa9f637741.png)
