### ISSUE TITLE
TADA

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#196]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte

> Bonjour, 
> 
> L'OpenFab m’a été renseigné par Tanguy Vandelrinden de DigitYser. 
> Je travaille dans une association, Toekomstatelierdelavenir.com 
> 
> A TADA nous proposons à des bénévoles de venir partager leur passion avec nos enfants le temps d’un samedi!   
> 
> En bref, à TADA nous aidons des enfants issus de milieux défavorisés à découvrir différents métiers et à travers cela, à mieux se connaître eux-mêmes. Ils viennent chez TADA tous les samedis pendant 3 ans sur base volontaire! C’est l’occasion d’un échange enrichissant puisque les intervenants animent des ateliers interactifs en étant complètement encadrés par notre équipe pédagogique.
> Le 17 mars 2018, les élèves de TADA clôtureront leur cursus d'ICT. 
> 
> Nous clôturons toujours les sessions par une excursion. C’est l’occasion pour nos élèves de mettre en pratique tout ce qu’ils ont appris pendant les 3 samedis précédents et d’être plongés dans un univers inspirant! 
> 
> Cela vous tenterait-il d’accueillir nos élèves au sein de l’Openfab? 
> 
> N’hésitez pas à me contacter par téléphone si cela vous intéresse! (0499/542.533) 
> 
> Merci pour votre retour,

**Comment by DewiBrunet** [comment]
Est-ce que c'est trop tard pour donner suite positive?
C'est un bon crash test je pense mais faut voir qui peux s'en charger (je suis pas dispo perso le 17...)

proposition en lien avec l'issue 197 https://github.com/openfab-lab/openfab/issues/197

**Comment by nicolasdb** [comment]
ho, c'est déjà le 17. 
Moi non plus, on en revient à la disponibilité des ressources humaines.

**Comment by DewiBrunet** [comment]
mmmh, donc : 
- on donne réponse négative?
- on poste sur le groupe pour voir si quelqu'un est intéressé?
- on propose de reporter à plus tard?

**Comment by nicolasdb** [comment]
- oui
- non
- tu peux proposer, le fabmob est encore jeune, on est pas encore bien organisé mais faut garder la porte ouverte.

**Comment by DewiBrunet** [comment]
This issue was moved to openfab-lab/FabMob#2
