### ISSUE TITLE
workshop fabmob

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#197]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte

> X m'a donné vos coordonnées pour éventuellement organiser un atelier-visite et découvrir votre projet de fabrication numérique. On aimerait avoir aussi la possibilité de tester pratiquement un des vos machines.
> 
> L'atelier serait pour un groupe de 8, maximum 10 jeunes (12-18 ans), en présence de deux animateurs, pendant la deuxième semaine de vacances de Pâque (lundi, mardi ou mercredi). Je vous invite à me communiquer votre disponibilité, le prix et la durée de l'activité.
> 
> J'attends vos nouvelles et je vous remercie pour votre attention.

## proposition

> J'ai bien reçu votre message, nous avons un évènement en prépa Dimanche, je ne suis pas très disponible mais je vous apporte une réponse pour début de semaine.
> 
> En rapide,
> votre demande correspond au cadre de notre projet fablabmobile et pourrait du coup être gratuit.
> 
> Bon week-end. 

## ressources
@DewiBrunet

**Comment by DewiBrunet** [comment]
**Ma proposition** :

Le matin (9h-12h)
1)	Accueil, présentation du lieu et des particularités d’OpenFab
2)	Explication (avec exemples, interactions) de ce qu’est un fablab, l’opensource…
3)	Présentation des machines par des exemples de la communauté OpenFab

L’après-midi (13h-16h)

Atelier découpe laser (ou autre, mais la laser me semble le plus facile pour une première), par groupe de 2 ou 3.
Les fichiers et la matière seront déjà préparés, mais les enfants pourront customiser l’objet et le reproduire pour chacun.
Une première phase servira à expliquer l’exercice puis l’animateur passera pour assister les groupes au fur et à mesure.
Idées de workshops:
-	Mini maquette à assembler
-	Boite avec son nom
-	Support smartphone
-	Porte clé

**Niveau organisation :**
- Adaptable pour un groupe de 10 max, enfants à partir de 7 ans ou adultes.
- Nécessite deux animateurs : un référent (superUser avec badge animation/laser/3D ?), payé 350€ et un suppléant (User) , payé 200€
- Nécessite de « bloquer » OpenFab et aménager/ranger pour organiser l’espace
- S’assurer des questions de sécurité
- Organiser le repas ?

**Les questions que je me pose**  :
-	Une journée c’est trop ? Peut-être que certains attendent une demi-journée…
-	A quel point faut-il laisser la liberté pour le workshop ? (genre laisser choisir la matière ou l’objet à faire ou bien imposer le même pour tous ?).
-	Niveau tarif, on est sûr que fablab mobile peux payer un animateur + un suppléant ? Quelles sont les contreparties derrière ? (documentation…)
-	Si on ne passe pas par fablab mobile, on reste sur les mêmes tarifs ? On prévoit des gains en crédits/dé/badge ?

**Comment by nicolasdb** [comment]
cool. 

> - Une journée c’est trop ? Peut-être que certains attendent une demi-journée…
> - A quel point faut-il laisser la liberté pour le workshop ? (genre laisser choisir la matière ou l’objet à faire ou bien imposer le même pour tous ?).
Pour ces 2 questions, je me dis qu'on pourrait voir un workshop comme 2 étapes qui s'enchainent
1. un module qui peut se suffire à lui même, d'une demi journée. 
2. une suite d'une demi journée, (expension pack) pour approfondir le sujet ou rentrer plus dans la pratique. 
ça donne la liberté de s'adapter au temps qui est disponible/demandé.
Et pour pas que ça parte dans tout les sens, on en revient au catalogue. Il faut pouvoir proposer ou imposer un choix limité. 
C'est plus simple pour le client (trop de choix, tue le choix) et c'est plus simple pour nous de proposer des workshop qu'on maîtrise. 
à nous de choisir, au cas par cas, si on prend sur nous de développer un nouveau contenu. Qui sera biensur ajouté au catalogue. 
Ce qui nous amène à lister ce qu'on sait déjà faire et l'optimiser d'un point de vue contenu et d'un point de vue communication.

> - Niveau tarif, on est sûr que fablab mobile peux payer un animateur + un suppléant ? Quelles sont les contreparties derrière ? (documentation…)
Oui, c'est budgétisé comme ça. 2 animateurs/workshop. 
Pour les conditions, contreparties, ça doit être définit et clarifié à la prochaine réunion.

> - Si on ne passe pas par fablab mobile, on reste sur les mêmes tarifs ? On prévoit des gains en crédits/dé/badge ?
Pour moi, c'est important d'avoir une cohérence dans les tarifs. Que ce soit Innoviris qui paye via fabmob ou un autre client, qui bénéficie peut-être d'autres subsides pour ça. 
Le coût réel est de toutes façons le même. La question est qui paye pour ça.

**Comment by DewiBrunet** [comment]
Ok top même si je doute qu'en 1/2 journée on puisse faire introduction + atelier...
Enfin ce qui reste à définir donc c'est le catalogue?
Je pense qu'il faudrait définir au minimum 3 ateliers (laser/3D/Arduino) facile & rapide à faire mais adaptable puis estimer le temps/matériel/rentabilité de chacun.

**Comment by nicolasdb** [comment]
oui, faire un template et "standardiser" l'information relative à chaque. 
Et surtout sur qui on peut compter pour s'en occuper. Si on propose un truc, il faut pouvoir l'activer facilement. 
On peut préciser aussi un minimum de tps avant activation. par ex: réservez min 3 semaines avant la date souhaitée. 

J'aime bien l'idée d'une intro 1/2 + atelier 1/2. mais voit peut-être plus ça comme pour le fabmob aussi. 
1/2 sensibilisation, (intro/demo) 1/2 atelier (approfondissement).

**Comment by DewiBrunet** [comment]
J'aimerai créer un fichier md pour documenter un template pour ce genre de demande et écrire un mail type qui devra juste être copié collé - est-ce qu'on a un repository fablabmob caché quelque part?

Et petit détail con mais j'arrive plus à retrouver le mail de cette demande pour y répondre... si on garde anonyme le nom, pourrait on indiquer la date/sujet du mail?

**Comment by DewiBrunet** [comment]
This issue was moved to openfab-lab/FabMob#1

**Comment by DewiBrunet** [comment]
Je sais pas si c'est bien de faire comme ça mais j'ai bougé l'issue dans le repository FabMob : 
 https://github.com/openfab-lab/FabMob/issues/1

Pour faire cette manip, easy avec https://github-issue-mover.appspot.com/
