### ISSUE TITLE
Réunion vision OpenFab

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#198]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Suite au CA, il a été mentionné d'organiser une réunion d'intelligence collective sur la vision.
Mayliss s'est proposé pour s'en charger mais :

"_Pour ma part, je ne serai pas en capacité de faciliter un tel workshop d'ici le mois d'avril.
Par contre, pour avancer ( et ne pas reculer le début de l'organisation) deux choses pourrait être utile:
- la première: lister les personnes (membres et autres) qui devraient idéalement participer à un tel workshop. Je pense principalement à des membres actifs et aux probable membres du CA.
- la deuxième: trouver une date, un moment qui convient au plus grand nombre: idéalement 4 heures minimum._ "

## objectif
1) lister les participants
2) caler une date - le plus tôt le mieux!

## proposition
**1) Lister les participants**

Participants essentiels : 
- Nicolas de Barquin
- Dewi Brunet
- Jean-Louis D'Hondt 
- Odile Collin
- Wiertz Arnaud
- Xavier Van Den Bossche 
- Lionel slusny
- Milena Sonneveld
- Anne-Camille Gilbert

Participants souhaitables:
- Le plus le mieux? On fait un appel sur le groupe Facebook? Oui

**2) Caler une date**
Un week-end d'avril, de 14h à 18h :
https://doodle.com/poll/wpiy5984n2hnfdxb

Peut-être rajouter qu'on offre des bières/un repas pour faire venir les gens?
Dès que c'est bon, on peux poster ça sur le groupe Facebook?

**Comment by nicolasdb** [comment]
Bon, tjs à la dèche sur le sujet. 

le doodle a été remplis, 
peu de succès par rapport à la quantité de personnes concernées. 
Et surtout, l'organisation des événements et leur communication est tjs prise à la bourre, ça suit pas et on se retrouve tjs 3 jours avant les dates sans avoir rien confirmer ni organiser. 

la dernière décision prise, c'est de 
- faire une réunion avec ceux qui était libre. 
- établir une sorte de formulaire, plus facile à remplir pour tous, ce qui permet de récolter plus de réponses avant d'en faire une rencontre IRL
- organiser une aprem d'intelligence collective sur base des formulaires avec un groupe plus réduit. 

J'y vois encore plusieurs problèmes:
- il faut une personne qui puisse se charger du suivit de ça. 
Dewi et moi, on est largué, c'est pas notre kif et on a plein d'autres trucs en même tps. Ce qui fait qu'on est pris par les autres priorités et le résultat est tjs le même (mentionné plus haut)

How to contribute?
- une seule tache:  planifier et faire le suivi, tenir au courant les personnes concernées pour les dates, lieux, etc...

**Comment by nicolasdb** [comment]
voir le slack @vision
