### ISSUE TITLE
laser - documentation - HowTo

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#199]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
faut tout le tps répéter et c'est frustrant pour celui qui répète et celui qui trouve pas. 
## objectif
rassembler la doc qui a été faite, et traîne un peu partout au fil des ages. 
## ressources
- http://www.profs.ch/flwiki/LaserCutter
traduit google sur https://github.com/openfab-lab/toolsDocs/blob/master/Lasersaur/lasersaur.txt
- setup calibration 
https://github.com/openfab-lab/toolsDocs/tree/master/Lasersaur
- usage inkscape 
https://github.com/openfab-lab/openfab/blob/master/_space/machines/laser/preparation-fichier.md

**Comment by Jorgininho** [comment]
hey je peux la semaine prochaine ?
je veux du rewards! :)

**Comment by nicolasdb** [comment]
Dewi a commencé qque chose. Il sera certainement content d'avoir de l'aide. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DewiBrunet** [comment]
:) cool, salut @Jorgininho !

On a de la doc en effet (à compléter) mais je pense qu'il manque surtout une sorte de wiki simple pour un non initié. Je pensais faire une documentation sur github et un livret et/ou des fiches à coller sur la laser du genre : 
- règles du jeu
- l'outil, les matières
- préparer son fichier
- mise en route du job
- FAQ
- Combo vitesse puissance

On peut en parler cette semaine! (je suis la tous les jours sauf mardi)

**Comment by Jorgininho** [comment]
yop, j'ai regardé la doc que tu as donné nico, c'est bien, on a beaucoup de détails sur la préparation des fichiers, c'est important mais à mon avis c'est pas le genre de documentation que je m'imaginais.

Je suis bien d'accord avec ton analyse et les differents thème de doc que tu proposes dewi. 
- L'aspect préparation des fichiers peut etre assez complexe car c'est la porte d'entrée avant la découpe. Ma recommandation c'est qu'elle reste sous la forme de wiki sur le GIT.

- Au niveau de l'aspect préparation de la machine (comment l'allumé ? la préparer? ) j'ai pas trouver grand chose sur tes liens nico :( . A mon avis c'est ce genre de doc qui peut etre dispo à côté de la mahine en restant assez succins.

- Les combo vitesse puissance pourrait tenir aussi dans un tableau à disposition à côté de la laser 

- L'aspect gaming n'est pas lié uniquement à la lasersaur, si vous voulez pas trop la multiplier il faudrait la rendre assez generique. Peut-etre elle pourrait tenir sur une page et à dispo cette fois dans le fablab ?

on en parle demain dans tout les cas :)

**Comment by Jorgininho** [comment]
yop j'ai fais une 1ere ébauche de ce qui pourrait etre la fiche pour lancer la laser
https://drive.google.com/open?id=1DZxhB-YPOGmwYTVYKCXOsxvpqd_Vl_Hg
Demain je suis pas certain d'etre là :)

**Comment by nicolasdb** [comment]
https://github.com/openfab-lab/toolsDocs/blob/master/Laser/Lasersaur/Readme.md

documentation réalisée par @Lisa-oraa 

Je clos cette issue.
