### ISSUE TITLE
Picto monétaire CRRR?

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#20]
ça serait cool d'avoir un picto. 
Partant plus de la sonorité de la monnaie que de ses lettres crrr. 

Je propose un beerstorming à ce sujet.

**Comment by nicolasdb** [comment]
idée de navid. 
composantes: La griffe (logo) et il faut les barres comme dans $ et €

**Comment by zuperninja** [comment]
Quand Nico m'a dit que c'était crrr avec 3 R, j'ai direct pensé au pirate et aux blagues des[ sites web traduit en pirate.](https://www.google.fr/?hl=xx-pirate&gws_rd=cr&ei=4MI1WajgBcKQUc68reAI) Je voyais bien la[ bouche de Finn ](https://images-mm.s3.amazonaws.com/Adventure_Time_Finn_Faces_Blue_Shirt_POP.jpg)dans Adventure Time faire ça. 
Pif paf pouf : [1ere idée picto](https://github.com/zuperninja/zuperninja.github.io/blob/master/crrr.svg)
Et on dirait un peu une main qui attrape une partie de la griffe d'openfab aussi :D

**Comment by nicolasdb** [comment]
https://media0.giphy.com/media/saUNbOl6rmSUo/giphy.gif

**Comment by nicolasdb** [comment]
![image](https://cloud.githubusercontent.com/assets/12049360/26802823/40a69be4-4a42-11e7-846a-24d11990e7b8.png)

**Comment by softrevolter** [comment]
on a déjà validé quelque chose ici?

**Comment by nicolasdb** [comment]
http://starwars.wikia.com/wiki/Galactic_Credit_Standard

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by softrevolter** [comment]
sexy!

**Comment by nicolasdb** [comment]
(punaise, trop bien ce github. J'avais oublié que j'avais trouvé ça)

**Comment by nicolasdb** [comment]
Est-ce qu'on part là dessus?
J'ai intégré l'unité dans mon lootcrate

Si oui, 
+1 +5 pour moi
on peut cloturer cette issue

**Comment by nicolasdb** [comment]
![crrr10](https://user-images.githubusercontent.com/12049360/29778516-eb3ebca8-8c0f-11e7-8330-dd17c87e5631.png)
J'ai ajouté une version 10px. Pour utiliser dans ton lootcrate.
