### ISSUE TITLE
Gestion des inscriptions Membres

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#200]
- [ ] ref to file .md or pullRequest #: .................................................  
Suite et relance de l'issue #136 

*(à remplir quand l'issue est résolue)*
## contexte
Chaque année, on perd des membres, parce que rien n'est en place pour les activer ni relancer et annoncer que c'est la fin de leur année d'inscription
Plus de 130 depuis qu'on est au 274. 
Seulement <30 en ordre d'inscription. 
## objectif
Rendre un minimum automatique cette gestion et améliorer le suivit.
## proposition
Actuellement, on a le formulaire qui remplit un fichier sheet sur le compte google contact.
Quelques formules donnent une idée des dates et tout ça.
Est-ce que quelqu'un (ou une team) pourrait se pencher sur cette amélioration?
Du fichier mais aussi d'un mailchimp ou quelque chose, un petit message tout nice avec des petits chats pour inviter à payer une nouvelle inscription. 
## Resultats
Plus de swag et d'amis.

**Comment by zuperninja** [comment]
Plus de détails sur le méchanisme archaïque que l'on a en ce moment

L'adhérent rempli le google form > inscription sur un google sheet = une nouvelle entrée dans le tableau > ajoute l'adhérent dans une liste mailchimp via [zapier](https://zapier.com)

Google Form et Sheet sur le drive de "contact"
Mailchimp et Zapier avec le compte de "anca"

## ISSUE CONNU : 

- si l'adhérent c'est déjà inscrit même il y a 3ans, mailchimp ne renvoie pas le mail
- prends quelques minutes
- si il y a plus de

**Comment by nicolasdb** [comment]
oui, et sur le drive donc, ça s'appelle **nov-16 - Fiche d'inscription (réponses)**
J'ose pas renommé pour pas casser quelque chose. 

Mais de la feuille qui réceptionne les infos, j'en ai tiré une seconde feuille avec des choses du genres et un total des inscriptions valides ( ya des erreurs et des gens qui n'ont jamais payé, ni venu) et des membres en ordre avec le "Yup"
On a exactement (aujourd'hui) 129 inscrits via le formulaire depuis octobre 2015. 
Dont 19 actifs et 12 que j'ai pas encore fait le suivit :p
Et je suis en retard de cotisation depuis février, j'ai vu :)


Horodateur | Valable jusque | Adresse mail : |Prénom + Nom | Montant dû : | Ont-ils payés ? | Quand?  | full check? | niveau?
-- | -- | -- | -- | -- | -- | -- | -- | -- 
09/02/2017 | 09/02/2018 |  nicolas@openfab.be  | Nicolas de Barquin | 25,00 € | oui | 09/02/2017 | yup | Niveau2 |

**Comment by nicolasdb** [comment]
Inspiration pour le ROI révisé et bridé au niveau 1. 

**Superuser Charter 2018 August**

http://valby.copenhagenfablab.dk/sites/default/files/projects/superuser_charter_august_2018_edition_0.pdf

**Comment by nicolasdb** [comment]
ok, problem solved

on va gérer ça dans zoho maintenant. 
https://github.com/openfab-lab/rtfm/issues/13
