### ISSUE TITLE
Filtre laser bouché

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#207]
- [ ] ref to file .md
https://github.com/openfab-lab/toolsDocs/blob/master/Lasersaur/checklist_soluce.md 

## contexte
Le box de la laser est rempli de fumée, il semblerait que ça aspire plus...

## objectif
Régler le problème et éviter d'enfumer l'espace^^

## proposition
Stop le job, attendre et enlever la fumée par un ingénieux système d'éventail avec une plaque de bois.
Ouvrir la laser et diagnostiquer... en effet il y avait un problème : le filtre (en mousse?) est hyper encrassé.
![thumbnail_20180501_203436](https://user-images.githubusercontent.com/25649502/39487444-852cfdd0-4d7f-11e8-9046-2831f6b485aa.jpg)

1) Nettoyage grossier avec l'aspirateur
2) Nettoyage moyen avec éponge
3) Nettoyage fin avec pinceau
4) Changement du filtre (mousse en rouleau à l'arrière, fixation avec agrafeuse murale):

![thumbnail_20180501_203425](https://user-images.githubusercontent.com/25649502/39487459-90b85870-4d7f-11e8-834e-023c672f5c7b.jpg)

Reste à savoir  : 

- si c'est normal (encrassage régulier) ou si c'est du à autre chose... (j'ai lancé un gros job en 61x122 mais j'ai pris soin de faire ça en 2 fois avec un temps d'attente).
- si le nuage de fumée n'a pas endommagé la laser (elle marche toujours et j'ai tout nettoyé direct mais p-e que ça nécessite un nettoyage plus en profondeur?) 
- si le compresseur est bien réglé? (j'ai d'ailleurs trouvé aucune documentation sur comment faire...)

**Comment by nicolasdb** [comment]
yes, c'est normal. 
J'ai ajouté ce "préfiltre" pour justement faciliter le nettoyage.  
On se rend compte d'ailleurs mieux à quel point le mdf dégage de la fumée lourde de particules. 
C'est ce qui ruine les filtres type BOFA, lorsqu'il n'y a pas d'évacuation extérieure. 

Mon objectif était de mieux me rendre compte et du coup, tu t'en rend compte aussi maintenant, sachant que si c'est pas préfiltré, toutes cette crasse vient s'accumuler dans le moteur d'extraction (chiant a nettoyer) et dans les tubes mais c'est moins grave.

Par contre, je ne m'attendais pas à cet effet, si vite. J'ai du placer ce petit morceau de filtre grossier, il y a 1 ou 2 mois. C'est le même utiliser pour préfiltrer la poussière en entrée. (je ne l'ai jamais lavé lui, ça va donc)

Sorry, je n'avais pas documenté ça.
