### ISSUE TITLE
3D print : où sont les soluces?

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#209]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
--> J'ai accueilli un membre pour lancer ces impressions 3D.
--> J'ai jamais utilisé les machines d'OpenFab mais j'ai pu tester les Fabricator avec FablabMobile donc ça devrait être la même logique.
--> J'ai réussi à en lancer une mais la deuxième, impossible de faire sortir le filament : il me semble pourtant avoir tout testé...
--> Heureusement, il y a github "je vais d'office trouver une série d'issues d'autres gens qui ont comme moi galéré et trouvé une solution"... a bah non, il y a rien!

## objectif
Rendre possible l'impression 3D pour tous!

## proposition
- Trouver (ou créer) une FAQ qui puisse répondre aux problèmes récurrents liés aux impressions 3D.
- Mettre à jour/transférer sur github la prise en main machine & logiciel pour un noob (qui est sur le site mais pas forcément complet/actualisé : http://www.openfab.be/forum/index.php?board=67.0)

**Comment by nicolasdb** [comment]
Yeah. Nice idea. 
Je peux aider si besoin ^^

**Comment by nicolasdb** [comment]
A quoi j'ai répondu :

C'est pas faux pour les tips anticlog mais:

- retirer le filament à chaque fois, risque d'être plus chiant car il faut le retirer complètement, recouper le bout et le remettre avec le risque que ça bloque dans l'extrudeur. 

Dans ce cas, Florent a vu comment faire.

- clean by cold pull. Yup.

C'est bien la technique a suivre comme premier geste pour nettoyer la buse. 

Mais attention, cold c'est trop froid. Le mieux est de retirer le tube ptfe blanc, enfoncer un filament à chaux quelques instants et l'extraire d'un coup bref. 

Couper le bout , recommencer et observer ce bout pour voir si des crasses sont emportées. 

Le dernier test, c'est pareil mais en laissant refroidir la buse et extraire le fil vers 160°C. Vous pouvez tester plus bas mais a un moment, le PLA va solidifier dans l'extrudeur.

Là aussi, c'est pour attacher les dernières crasses dans le PLA plus dur. 


Si après ça, ça ne va pas mieux. Le filament doit s'extruder de manière fluide, droite. Si le fil qui sort est dévié, c'est qu'une crasse bloque encore la buse directement. 

Dans ce cas, il faut chauffer et je prend un fil de cuivre. J'ai dans une boîte du fil émaillé de 0.3mm. 

Couper un morceau, 30cm suffisent, et le glisser par le trou de la buse (avec des gants ou une pince, la chaleur va passer dans le fil)

Et curer la buse en passant le fil entièrement plusieurs fois, le fil va emporter les restes de vieux plastique. 


Si après tout ça, ou si le fil de cuivre ne passe ps du tout, alors il faut démonter et changer la buse. Y en a dans une boîte au dessus de l'étagère avec les imprimantes. 

! Opération à faire à chaud aussi. Le metal se dilate et il faut bien revisser à chaud , sans serrer très fort quand même, mais à chaud pour éviter des fuites lors du print. Ce qui arrive souvent à ceux qui assemble leur extrudeur à froid.

Y a plein de video sur le net. Et c'est pareil pour tout les modèles donc peu importe de trouver obsolument l'info pour la fabrikator.

**Comment by satblip** [comment]
Ceci est aussi une ressource à garder sous le coude : https://www.simplify3d.com/support/print-quality-troubleshooting/

**Comment by DewiBrunet** [comment]
Ok merci pour vos conseils!
Top ce guide (même si je suis déjà arrivé au point "Please consult your manufacturer for instructions", c-a-d Nico^^)

J'ai tout testé, et ça remarche :) enfin après beaucoup beaucoup de tests #uneapremdefrustrations: 
![thumbnail_20180510_173758](https://user-images.githubusercontent.com/25649502/39878877-b7942d92-5479-11e8-8144-001035116077.jpg)
![thumbnail_20180510_162043](https://user-images.githubusercontent.com/25649502/39878914-cd2dd676-5479-11e8-9ef0-531f39cafc57.jpg)

J'ai encore tellement de points obscurs... surtout j'ai pas su trouver le modèle "3Drag" (comme indiqué sur le site OpenFab) sur CURA du coup j'ai testé avec plein de modèle pour finir sur "anet E10" (ça à réglé mes problème d’adhésion au tapis).

Dernier point : sur l'autre machine, je crains d'avoir un peu trop forcé en poussant le filament et qu'il y a un offset sur son axe vertical... Du coup la tête touche le tapis. Comment on fais pour recalibrer ça? C'est à la main ou avec l'écran?
![thumbnail_20180510_173727](https://user-images.githubusercontent.com/25649502/39879191-72424d0e-547a-11e8-9622-a1c703709bcb.jpg)

Il semblerait que mon aventure dans le royaume de la 3D soit plus compliqué que je ne pensais...
![telechargement](https://user-images.githubusercontent.com/25649502/39879462-271691f4-547b-11e8-8e0f-7cfa1dfb7b9a.jpg)

**Comment by nicolasdb** [comment]
La 3Drag, c'est celle dont je t'ai proposé de la hacker pour faire ton premier traceur.  C'est le cadre alu posé sur le meuble "brol pour la vitrine" ^^
bref, c'est du passé. 

Mais c'est bien, j'suis fier de toi. bravo :+1: 
Les problèmes d'adhésion, c'est 
- soit le tape bleu qui est usé > remplacer
- soit la température du lit pas adaptée. > Je met 60 puis avec cura y a moyen de lui dire de redescendre vers 50 après les premières couches. C'est dans le profil cura. 
- soit Z n'est pas correctement réglé. 

## pour calibrer Z
1. vérifier qu'au départ, les 2 côtés sont bien au même niveau. Mesurer simplement entre un point de référence de chaque côté à quelque de fixe en Z. J'utilise soit la table pour la **A6** soit un élément du chassis. **E10**
Tourner manuellement l'axe du moteur pour ajuster. Il faut que les 2 soit à la même hauteur. 
! vérifier de l'autre côté après changement, changer bcp d'un côté peu faire bouger aussi l'autre. 

Normalement, ça devrai déjà faire une différence. 

2. Si c'est le lit qui a bougé. 
Faire une mise à ZERO logiciel = homing Z. 
Déplacer manuellement la tête aux 4 coins et s'assurer que l'écart n'est que d'une feuille de papier. (0.1mm)
Ajuster le lit avec les visses aux coins. 

3. Si c'est pas encore bon, on peut ajuster physiquement la hauteur globale avec une vis de réglage au niveau de l’interrupteur de limite Z. En vissant ou dévissant par 1/4 de tour, on ajuste le point de contact sur le switch et on monte ou abaisse la position du Z=0 de manière globale. 

**Mais d'abord tjs s'assurer que les 2 côtés du bras (Axe X) sont bien au même niveau.** 
Sinon, problème de Z et torsion dans les axes. 


Si la tête est trop basse, le filament ne sort pas et peut boucher la buse. 
Si trop haut, le filament n'adhère pas bien. 

![image](https://user-images.githubusercontent.com/12049360/39917052-a7a9ca7a-550c-11e8-94c0-3a8ae2370b25.png)

**Comment by DewiBrunet** [comment]
Haha, ok bin du coup c'est quoi leur petit nom aux autres machines? Thing-O-Matic?

Je viens de recalibrer et j'ai envie de tester mais truc con, le filament il ressort à chaque fois un peu n'importe ou >< 
Un conseil?

![thumbnail_20180511_170646](https://user-images.githubusercontent.com/25649502/39932476-89986b98-5540-11e8-8180-f29bf76cface.jpg)
![thumbnail_20180511_171608](https://user-images.githubusercontent.com/25649502/39932478-89b611c0-5540-11e8-831a-b77ebae52249.jpg)

**Comment by nicolasdb** [comment]
Yup, couper le filament en biais. C'est un défaut de l'extrudeur, ca arrive souvent sur toutes. Le filament courbe et ne passe pas par le trou et s'échappe par là où il peut

**Comment by nicolasdb** [comment]
Thing-o-matic, c'est ma première. Une en bois, semi démontée à l'arrière côté admin.

**Comment by satblip** [comment]
Ce qui aide aussi, c'est de couper le bout du filament en biais, ça l'aide à rentrer dans le bloc de dissipation du hotend ;)

![image](https://user-images.githubusercontent.com/1811109/39933343-01a11c8c-5543-11e8-8741-4f943fa5e115.png)

**Comment by DewiBrunet** [comment]
couper en biais je fais ça depuis le début, j'ai ouvert (délicatement hein!) l'endroit où ça coince pour comprendre ce qu'il s'y passe... 

Mais du coup, dans CURA faut indiquer quoi comme machine??? anet E10 c'est un truc standard qui marche sur tout?

**Comment by satblip** [comment]
Anet E10, c'est un modèle d'imprimante. Après cela dépend du Cura, c'est un custom maison ou tu l'as downloadé today?

**Comment by DewiBrunet** [comment]
sur mon pc j'y comprends rien à la version 3.3.1 du coup j'utilise celui du bureau OpenFab (avec je penses en effet les réglages custom et je crois qu'en fait toutes nos imprimantes 3D sont custom donc ça me sert à rien d'aller piocher dans la liste...)

**Comment by satblip** [comment]
Après au vue des Photos, tu as bien une Anet E10 sous les mains. 

Pour ton problème de filament, tu as un lcd sur l'imprimante, tu peux lancer un préchauffage pour PLA (+/-210°) ensuite quand elle est à température, tu peux allez dans le menu sur le lcd et aller dans position => move axis => 1mm => extruder. La tu vas pouvoir faire avant l'extrusion (prise du filament dans le nez de l'imprimante) à la main et avoir un meilleur contrôle sur la vitesse de prise du filament, moins prise de tête. Quand ton filament sort du nez, tu peux commencer à printer.

Pour les soucis de print, le réglage dans cura doit être bon si tu choisi Anet E10 (toujours peaufinable mais tu dois pouvoir savoir imprimer). Le problème vient surement de la calibration de l'imprimante et là peut-être que ça peut t'aider : https://www.youtube.com/watch?v=bD7iErK8zGk

Sans être là, je peux pas t'aider plus :-/ Si tu veux je peux tenter de passer lundi, mais je te promets rien, j'ai un agenda bien plein.

**Comment by satblip** [comment]
PS: j'utilise des prints du genre pour tester ma calibration ;) 

https://www.thingiverse.com/thing:2125379
https://www.thingiverse.com/thing:2065515 (doit bien sticker partout, si un endroit est flottant, c'est pas bon ;) )

**Comment by DewiBrunet** [comment]
J'ai ouvert, j'ai compris, j'ai refermé, j'ai essayé, marche pas, même avec ta technique sur lcd (mais bon à savoir merci!). Toujours le même soucis de filament qui se barre par le côté...

J'ai rouvert, j'ai mieux compris :  
![20180511_190023](https://user-images.githubusercontent.com/25649502/39938745-3b68f24e-5554-11e8-9135-28491a44114c.jpg)

 j'ai essayé d'enlever le filament de l'intérieur, j'ai rerefermé, marche toujours pas.
![3005_jackie-chan-meme-why](https://user-images.githubusercontent.com/25649502/39938707-1a65afd8-5554-11e8-9e1e-8cc72215eadc.jpg)

Lundi matin justement il y a une dame qui vient imprimer un truc, heureusement on a encore une qui fonctionne. Mais je suis pas la l'aprem... sinon je suis la mercredi et vendredi si jamais tu passes sinon no stress je trouverais bien une solution^^

**Comment by nicolasdb** [comment]
On va avancer sur ces documentations ici:
https://github.com/openfab-lab/toolsDocs/blob/master/3dprint/readme.md

Todo:
- FAQ
- Doc sur installation du profil Cura
- centraliser les profils sur github

**Comment by zuperninja** [comment]
Moi aussi ça marche pas. J'ai tout bien lu, mais je pense que je manque de temps et de patience (ça fait maintenant plus de 4h...).

J'ai l'impression que le nozzle est bouché. J'ai pas envie de le démonter... (car j'ai galéré la dernière fois et je suis seule à l'atelier.)

Observation : 
- Manque du filament par moment, impression fragilisée ou dépôt de filament pas régulier.
![img_20180813_163005](https://user-images.githubusercontent.com/25099826/44038264-b7f16218-9f16-11e8-98ba-c1a953d80d40.jpg)
![img_20180813_163022](https://user-images.githubusercontent.com/25099826/44038265-b83b68c2-9f16-11e8-81a6-6034bfaea1fe.jpg)
- le moteur pour poussé le fil dans le tuyau blanc parfois saute ou n'a pas une vitesse régulière
- quand je retire le fil, il y a des gros pâtés à chaque fois au bout
- parfois ça l'air de bien se passer et une seconde après plus du tout

Actions faites : 
- calibration avec la règle pour le Z
- calibration du lit
- poussé le filament manuellement (plusieurs fois à plusieurs températures)
- laisser refroidir pendant la nuit les moteurs tout ça
- changé le filament (au cas où)
- modifié les paramètres sur cura et tester
- essayé d'imprimer un modèle qui marchait bien avant
- prié
- pris un thé

**Comment by nicolasdb** [comment]
Si la buse est bouchée, aucune des solutions que tu as testé n'agit sur ce problème.

**Comment by DewiBrunet** [comment]
aaah, je vois que je suis pas seul à galérer ça fait plaisir^^ (je comprends ta frustration!)
en effet, ultime solution est de démonter, mais t'inquiète @zuperninja c'est pas si compliqué, faut juste être soigneux et patient ;) 
j'avance sur ma documentation github et j'ai justement finis mon tuto "déboucher buse bouchée" : https://github.com/DewiBrunet/Impression-3D/blob/master/D%C3%A9boucher%20buse.md

**Comment by Jorgininho** [comment]
Super discussion ;) 
Sinon peut être la température est pas optimale, sachant que ça peut changer d'une marque à l'autre, ce qui fait que la buse se bouche ?
Je sais qu'il y a des moyens d'imprimer à des températures différentes sur le même print, t'as déjà essayé @nicolasdb ?

**Comment by nicolasdb** [comment]
Non mais on sait bien pourquoi la buse est bouchée. 
C'est quand on fait pas assez attention lorsqu'on retire le filament. Un bout pas assez fondu refroidis trop vite et se bloque dans le tube métallique de l'extrudeur. 
Donc demonter, chauffer manuellement et dégager le bouchon.

**Comment by satblip** [comment]
Tiens, btw, j'en ai fait un aujourd'hui (qui m'a d'ailleurs viré un crasse, damn filament au graphite!!), on a parlé quelque part du "cold pull"?

**Comment by zuperninja** [comment]
Si j'ai pas fait la bonne solution tout de suite c'est que je ne savais pas
comment détecter le problème. Apprentissage en cours :D

Le jeu. 16 août 2018 à 20:10, Louis Borsu <notifications@github.com> a
écrit :

**Comment by nicolasdb** [comment]
Le cold pull, c'est pas mal pour nettoyer la buse. C'est juste. 
Mais ici, la plus part du temps, le soucis se passe au dessus de la buse, dans la zone froide. C'est pas sale mais bouché par du PLA dur.

**Comment by satblip** [comment]
Ok, étonnant, ça ne m'est jamais arrivé. Ce serait l'imprimante qui serait laissée trop longtemps en chauffe? Je dois avoir un bon mètre de PTFE quelque part, ça peut valoir la peine de changer le bout dans la zone froide ?

**Comment by nicolasdb** [comment]
y a pas de PTFE dans l'extrudeur, c'est un full metal. 
Qui est froid du coup. 
Donc, si on ne préchauffe pas suffisamment le filament en forçant l'extrusion manuellement (on pousse) pour bien faire fondre le reste de filament dans la buse et réchauffer l'extrémité. 
Puis, extraire le filament manuellement (on tire) de manière franche (pas rapide, pas lente, pas hésitante, franche) 
Si pas, le filament refroidit (trop vite) au contact du métal et colle dans un endroit à la con. Pas dans le tube PTFE.

**Comment by satblip** [comment]
Je suis en e3dv6 sur les deux ici et suis très content. Des petits problèmes d'encrassement de la buse une fois tous les 6 mois, mais je joue avec beaucoup de filaments différents, donc c'est normal. J'en monte une 3ème bientôt (quand j'aurais le temps.... 😄) avec un e3d v6 chinois, je te dirai quoi si il tient les specs ;)

**Comment by nicolasdb** [comment]
J'ai tenté du chinois et les tolérances sont pas dingue dingue, ça passe ou ça casse. Ici, ça n'a pas passé, le filament bloque tout le tps quand il arrive à l'entrée de l'extrudeur. 
J'ai du coup acheté un E3D mais en 3mm pour revaloriser la 3drag (qui est aurjoud'hui complètement démontée) et utiliser les filaments 3mm, surtout le flex qui semble mieux fonctionner en 3mm. 
Mais idem, pas le tps, ça traine. Faut changer le chariot pour l'installer. et je crois m'être trompé entre bowden et direct, bref, faut chipoter ou l'installer sur une autre. La geeetech pourquoi pas.... mais ses axes Z sont nases, ça bloque tout le tps.

**Comment by nicolasdb** [comment]
Issue moved to [openfab-lab/toolsDocs #25](https://github.com/openfab-lab/toolsDocs/issues/25) via [**ZenHub**](https://www.zenhub.com/)
