### ISSUE TITLE
Teambuilding coffee corner

### ISSUE THREAD

**Issue by zuperninja** [openfab-lab/openfab#212]
- [ ] ref to file .md or pullRequest #: .................................................  

## contexte

- +/ 6 personnes
- 2 demi-journées (Jeudi 7 et 14/06)
- construire un coffee corner en palette, mdf et le peindre (2 fauteuils + une table basse + 1 table haute avec rangement)
- fournir les matériaux
- fournir les outils + initiation
- encadrer l'animation (teambuilding)

## objectif

- [x] réaliser un devis (envoyé)
- [x] trouver un animateur.rice (Dewi, Nico, Anca)
- [x] booker les dates (Jeudi 7 et 14/06)
- [ ] commander les matériaux (ou les sourcer)
- [ ] apporter notre griffe, leur faire découvrir les possibilités du fablab

## proposition

![image](https://user-images.githubusercontent.com/25099826/40173541-741f6690-59d2-11e8-9353-b4ba1d44c3fd.png)
![image](https://user-images.githubusercontent.com/25099826/40173560-857abd0e-59d2-11e8-88f5-fb052bbcdd07.png)

- Réalisation des meubles demandés + peinture (selon leur plan)

Swag en surprise:
- Graver leur logo et le nom des participants aux laser dessus
- Impression 3D d'un gadget pratique (?)

## ressources

- [ ] Animateur.rice construction
- [ ] Animateur.rice laser
- [ ] Animateur.rice impression 3D

Les animateurs.rices peuvent se relayer vu que 2 demis journées.

https://github.com/dezminator/Y.A.P.P/tree/master/Reference%20Material/Pallet%20Standards

## resultats

Money money, et c'est pour un journal gratuit... article ?

### rewards

CRR ou real money ?

**Comment by nicolasdb** [comment]
2.5 *600€ pour les 2.5jours. Par personne sur place. 
+ Le tps de préparation. Je sais pas trop combien.
Par contre, faut estimer les matériaux et comment déplacer tout ca. 
On a pas de moyen de transport.

On a aussi une stagiaire en design qui va arriver ds 2 semaines pour 5 semaines

Dans les personnes compétentes, je pense à louis, désiré, moi-même pour le bois, dewi si on ajoute une dimension origami avec leur journaux :)

**Comment by zuperninja** [comment]
![image](https://user-images.githubusercontent.com/25099826/40234170-13601046-5aa6-11e8-8875-35a4fbd82ae2.png)

16 heures d'accompagnements = 2 animateurs pendant 8h.
16 accès journées = 2 accès pour 8 personnes pendant 2 jours. (on ne fait pas de 1/2 journées)

**Comment by nicolasdb** [comment]
ok good, 
Pourquoi y a des lignes non taxées? Attention à ça dans le devis, ça change la TVA et donc le montant final tvac.
Normalement, tout est taxé.

**Comment by zuperninja** [comment]
arf fuck !! je sais pas pourquoi je pensais que tout n'était pas taxé...

**Comment by nicolasdb** [comment]
yup, j'ai commencé une feuille "variables" dans le modèle de facture sur le drive contact (/compta caisse)

Y a tout les tarifs standards avec htva et tvac. Faut utiliser le montant htva à chaque fois, + taxe et à la fin, le montant final est automatiquement calculé.

**Comment by nicolasdb** [comment]
http://www.makery.info/2018/05/29/pour-lheure-de-lapero-sortez-vos-palettes/

**Comment by satblip** [comment]
Inspiration : http://meubleenpalette.com/canapes-de-palettes/chillout-point-de-travail/
