### ISSUE TITLE
Station Météo FabMob_Portes ouvertes de l'observatoire

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#213]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte

J'ai échangé quelques mails avec Gael qui nous propose de participer aux journées portes ouvertes de l'observatoire sur Uccle pour présenter les stations météo du Fablab Mobile.

Gael à pu échanger avec Karolien (de l'Institut royal d'Aéronomie Spatiale de Belgique) qui nous confirme que c'est possible d'avoir une place pour les 3 jours, dans les activités grand public avec la tente du planétarium

## objectif
Capitaliser sur le projet station météo du Fabmob

## proposition
 Proposer un stand pour 3 jours d'animation/sensibilisation avec FabMobile?
(ça peux rentrer dans le cadre de FabMob?)

(+) Faire une synergie avec Clément de GoodPlanet Belgium? ("Notre ASBL travaille activement sur la mobilité et la qualité de l’air à Bruxelles. Dans ce cadre nous envisageons de construire et installer des capteurs de qualité de l’air dans les écoles."). Je le vois ce mercredi 23 mai.

## ressources
- 2 animateurs (plus? moins?) sur 3 jours
- vélos cargo
- mini laser
- mini 3D
- composants éléctronique
- quelques modèles de station météo achevés

**Comment by nicolasdb** [comment]
Génial, oui, c'était d'ailleurs une étape de l' idée de projet phare ballon météo . Pour fabmob.

**Comment by nicolasdb** [comment]
Et on voit Clément mercredi. 
Pour moi, mettre en relation les objectifs fabmob et goodplanet, c'est un potentiel de financement complémentaire pour des choses qui ne sont pas financée par fabmob.

**Comment by DewiBrunet** [comment]
J'ai rdv lundi prochain (18 juin) à 14h avec Julie de GoodPlanet et Gaël de l'IASB voir ce qu'on peut faire ensemble.
@nicolasdb si tu sais être la aussi c'est top ;)

**Comment by DewiBrunet** [comment]
Bilan du rdv : 

- Gaël à l'IASB est plutôt sur Climat que qualité de l'air mais il va transmettre les infos à l'équipe pollution. Il reste dispo si on a besoin de son avis ou pour s'associer à une demande de subside pour gagner en crédibilité.
- Julie est éventuellement intéressé pour qu'on remette une demande de subsides ensemble pour qu'on vienne en appui à des animations en école dans le cadre des Plan de Dépalcements Scolaire (il y a du budget la dessus mais comme dab, le contenu non donc faut trouver des sous!).
- Faut refaire le lien avec la coordination FabMob pour être sur que c'est bon pour le 28/29/30 septembre.
- Faut éventuellement contacter le BRAL (équivalent flamand de Bxl environnement?), il voulait des infos sur nos possibilité de contruire des appareils de mesure.

**Comment by nicolasdb** [comment]
@DewiBrunet 
Le lien est fait avec Fabmob c'est ça? 
On cloture cette issue?

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/44533357-a75eb400-a6f5-11e8-8258-beeb00b8fc1f.png)

**Comment by nicolasdb** [comment]
bon, on va dire que c'est clos, je pense que c'était en octobre. On est le 31. J'en ai jamais plus entendu parlé.
