### ISSUE TITLE
Moquette au laser?

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#215]
- [ ] ref to file .md or pullRequest #: https://github.com/Anou92/Decoupe-laser/blob/master/Materiauth%C3%A8que.md
## contexte
Je vois dans la poubelle des chutes de moquette
## objectif
Question ? Est t'on certain de la composition chimique de ce genre de matière ? Vinyl, pvc, etc....

**Comment by Anou92** [comment]
Ok Anaelle qui utilise cette matière, va demander la composition au fabriquant.

**Comment by DewiBrunet** [comment]
👍  bienvenue sur Github @Anou92! tu vois c'est facile ;)

**Comment by nicolasdb** [comment]
Ok cool, tu mentionnera le résultat ici et idéalement, ça serai pas mal de se faire notre petite liste matériaux qui vont bien ou pas et leurs réglages, comme la feuille des bon combo. 

Ce qui permettra de renseigner ici le lien vers ce doc et clôturer cette issue.

**Comment by zuperninja** [comment]
J'ai proposé à la stagiaire en design produit de se pencher sur une liste
des matériaux et leurs réglages, à voir avec elle quand elle arrive.

**Comment by Anou92** [comment]
ok cool,  je comptais aussi commencer à faire une première liste de matériaux avec leurs réglages

**Comment by zuperninja** [comment]
Parfait ! Ca sera sûrement un gros travail collaboratif ! trop top ! Dis moi @Anou92 si tu as besoin d'aide pour faire ça sur github :)

**Comment by DewiBrunet** [comment]
on a une stagiaire qui arrive???

![images](https://user-images.githubusercontent.com/25649502/40560057-17d45a02-6059-11e8-9bfe-8acb632110ea.jpg)

**Comment by zuperninja** [comment]
Lisa du 4juin au 8juillet :)

**Comment by Anou92** [comment]
J'ai eu des infos d'Anaelle concernant la composition chimique de la moquette :
- La fibre textile est à base de polyamide
- la sous couche est fabriquée à partir d’un carbone polymérisé recouvert d’une couche de fibre de verre.

Je me suis renseignée et j'ai pu voir que la fibre de verre et la fibre de carbone ne peuvent pas être découpées au laser
J'ai trouvé ces infos sur ce site.
http://carrefour-numerique.cite-sciences.fr/fablab/wiki/doku.php?id=machines:decoupe_laser:0_utilisation:materiaux

**Comment by nicolasdb** [comment]
ok good, bon travail ça. ;)
Attention que fibre de verre et carbone, c'est un "ne peut être découpée au laser" parce que ça coupe pas ou pas bien. Ce n'est pas toxique en soit. 
Différent du PVC, Teflon et tout ça où ça coupe probablement mais c'est interdit à cause des dégagements toxiques.

**Comment by Anou92** [comment]
ok du coup si je comprends bien il n'y a pas de danger, on peut tester de découper cette matière, c'est juste qu'elle ne coupera pas bien. Peux tu me confirmer?

**Comment by nicolasdb** [comment]
oui, c'est ce que je pense et ce que j'ai vu dans les essais à la poubelle. 
ça a coupé, mais c'est pas net et ça pue. :) 
Note aussi pour l'encrassement accéléré probable du préfiltre des fumées.
La fibre de verre doit être en faible quantitée. Une feuille de fibre de verre ou de carbonne se comportera différemment.

**Comment by Anou92** [comment]
Dans ce cas nous n'allons pas continuer à découper cette matière

**Comment by nicolasdb** [comment]
@Anou92 Est-ce que cette liste a été commencée? elle est où?
qu'on cloture cette issue.

**Comment by Anou92** [comment]
Oui j'avais commencé à faire une liste sur mon github. Voici le lien
https://github.com/Anou92/Decoupe-laser/blob/master/Materiauth%C3%A8que.md

**Comment by nicolasdb** [comment]
Top, merci :) 

Par contre, va falloir refaire les estimations de vitesses. Avec le nouveau tube laser, on a triplé voir quadruplé la puissance. ^^ 

conseil github: 
- n'utilise pas les accents dans le nom de fichier. c'est des caractères qui passent mal dans les adresses web. Ce qui peut porter à confusion.
> Materiauth%C3%A8que.md
