### ISSUE TITLE
Ecriture commune de la vision et prépa AG + nouveau CA

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#216]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## ressources
#204 + #198 
## context
On a un peu foiré les réunions pour avancer sur le sujet admin de l'asbl, CA, AG etc... 
Alors voici un nouveau test. 

# On DOIT avancer sur ce sujet pour pouvoir avancer sur les appels à projets futurs. 

Ce qu'on doit faire: 
--- 
## Statut
Mayliss les a relu, les statut sont basiques et on besoin d'un bon coup de frais, avec quelques adaptations comme: 
- déménager le siège social à Ixelles. 
- Renvoyer des définitions vers le règlement d'ordre intérieur, pour facilité l'itération de la gestion journalière et de la gamification. Pour la définition des types de membres aussi. (adhérents/effectifs)???
- Mayliss proposait aussi de modifier les nominations du CA, il est possible de nomer président, trésorié et secrétaire que dans la période des **comptes&budgets**
_Intéressant si ces positions intimides...._ 
> il est aussi possible de définir des binômes pour chaque poste comme chez "opensource ecology france". Il faut juste en définir les conditions dans les status.

J'ai relu et corrigé manuellement le scan OCR qui était un peu miteux, c'est disponible ici: 
https://github.com/openfab-lab/openfab/blob/master/_space/asbl/statuts/statuts.04.2016-OCR.md

## vision commune, nos valeurs

Empowerment.
autonomisation des membres,
indépendance de la structure.
openmindset et inclusivité. 
gender Equity not egality. Cultivons nos différences.
Local avec interaction globale
Ecosysteme et permaculture, 
Promouvoir la relation étroite et la communication qui existent entre l'environnement naturel, l'humain et les nouvelles technologies par tous les moyens disponibles.

Comment est-ce qu'on écrit tout ça tant que tout le monde n'est pas à l'aise avec github? ici?
https://docs.google.com/document/d/1y4QsiO8hc_uTvWDd-fPijpJjgvPZ0SoRV2FCHlINn1g/edit?usp=sharing

## les objectifs 2018, et au delà?

- les teams
- l'autogestion du local
- le lien à l'échelle européenne 
- la gamification et le passport.

\+ comment activer les 80% des membres qui se contentent de "consommer" le résultat des efforts des 20% de membres qui contribuent; 
![image](https://user-images.githubusercontent.com/12049360/40498908-a4fb68b4-5f80-11e8-9f5c-8e31d019b4ef.png)

- soit en les amenant à contribuer, via gamification non obligatoire et monnaie interne.
- soit ils payent un tarif equitable en rapport à ce qu'ils bénéficient. 

C'est un peu de la méritocratie, je sais. Mais il est plus juste de trouver l'équilibre, ce flow, dans un cadre aux ressources limitées, qui n'est que le reflet micro d'une situation macro, terrestre. 

![image](https://user-images.githubusercontent.com/12049360/40499212-91bf7a78-5f81-11e8-85c6-664a68454777.png)

## Questionnaire à la communauté
juste pour marquer le coup et voir ce qu'en pense la communauté. On relance le buzz, on met à jour les infos de la communauté, on pense aux mailinglist et aux nouvelles réglementations. 
Je pense que si on veut aussi affirmer notre style, notre griffe, on doit clarifier ce qu'on veut faire (via ce doc), ce qu'on veut être et comment on veut y arriver. 
Il y a trop de flou, on veut faire plaisir à tout le monde (moi en premier) et c'est comme un tabouret branlant, on n'ose pas trop s'appuyer dessus. J'aimerai qu'on polarise plus notre communauté. 
Soit tu monte, soit pas.  Soit tu DIY avec nous, soit t'es un client, soit ben tu fais ce que tu veux hein mais ailleurs. 

![image](https://user-images.githubusercontent.com/12049360/40498673-edc9c4b0-5f7f-11e8-95fc-1bc3c77a26dc.png)

- Comment te positionne tu suite à ce qu'on vient d'écrire?  ça colle ou c'est pas du tout ce que tu cherche dans le fablab?
- Est-ce que ça t'intéresse de t'impliquer? ou juste l'accès aux machines?
- autres?

## next step
- [ ] Envoyer à tout le monde. 
- [ ] Récupérer les avis par mail mais aussi IRL, faire une fête barbec quelque part avec le support de la jacqueline :)
- [ ] Adapter si besoin le doc. 
- [ ] organiser l'AG pour présenter ces changements, nommer un nouveau CA et valider au moniteur. 
- [ ] re-fête et on en parle plus. 

J'aimerai vraiment qu'on puisse écrire ça de manière dynamique, comme on a pu faire quand j'étais away, on commente, on enrichit et on avance. En ligne.  fuck les doodles et les réunions physiques aux même moments. 

![image](https://user-images.githubusercontent.com/12049360/40500389-d8b67f32-5f84-11e8-9eac-7a04491a1cdd.png)

### Ensuite, j'aimerai que 
- quelqu'un prenne la tâche d'organiser la com avec la communauté.
- organise le barbec
- organise l'AG

**Comment by nicolasdb** [comment]
Ensuite, il faudra adapter le règlement d'ordre intérieur. 
J'aimerai bien qu'il soit imprimé comme le passport, avec une couverture rouge et à consulter au buro274.

https://github.com/openfab-lab/openfab/blob/master/_space/asbl/00RTFM-OF.md

![image](https://user-images.githubusercontent.com/12049360/40504086-78a0b85e-5f90-11e8-9c7d-70cec2da9f82.png)


ou carrément aller à fond quoi ^^

![image](https://user-images.githubusercontent.com/12049360/40504117-94356b5a-5f90-11e8-85ee-0fa360b2245b.png)

**Comment by nicolasdb** [comment]
@satblip @Valonlisbeth @zuperninja @DewiBrunet 

Je repars en France pour le FAB14 vers 11 ou 12 Juillet. 
Si je fais un rétroplanning à partir de là, 
- il faut qu'on programme une AG vers le 10 ou avant. 
- il faut officiellement convoquer les membres 15jours avant la date de l'AG. (Liste?)
- ça nous amène vers le 25 Juin. J'aimerai qu'on programme le barbec quelque part à cette date, pour le solstice le 21juin, on fête la nouvelle saison. 
  - idéalement, on introduit notre bière en stoemeling et vente des bouteilles, 
  - introduction des crrr, les membres qui ont déjà des crédit peuvent payer leurs bières avec. 
- on envoie l'invite pour le barbec en même tps que le doc de notre vision commune
- donc ce document co-écrit doit être finalisé dans 15jours max. Suffisamment que pour il n'y ai plus que quelques adaptations si besoin après les discutions avec la communauté. Le doc est éditable jusqu'à l'AG.
- Semaine prochaine, je vais m'occuper de compta pour fabmob et l'asso, rdv avec crédal le 7 pour une mise en place d'outils selon ce bilan des 5 premiers mois 2018.
- Une fois la compta en ordre, je passe à la rédaction. Toutes vos contributions seront les bienvenues, j'ai tendance à m'étaler un peu trop et je n'ai aucune expérience en status d'asbl. ^^'

**Qui pourra s'occuper de trouver une idée de lieux barbec et tout ça?** 
Quelques pistes: 
- juste une fête, on se fait plaisir, pas de présentation, pas de powerpoint, pas de forum ouvert, on mange on picole et on discute et on relève les remarques de la communauté tout en convivialité. 
- olivier de la cuisine à la Serre pourrait aider niveau cuisine. 
- Il me proposait le parc FelixHap, en bas de ch de wavre, l'endroit est pas mal. 
- Tandem occupe en pop-up truc le batiment dans le par felix hap. 
Répa vélo et petite restauration/bières
- On pourrait voir aussi avec la commune XL, il y a aussi le parc du viaduc et le resto Yeti est fermé mais on pourrait peut-être y avoir accès + le parc... voir avec Ursula ou Isabelle. 
- La jacqueline pour l'ambiance, of course. 
- des jongleurs et cracheurs de feu? 
non, allez, je déconne, on est pas à stGilles ici, lol

**Comment by DewiBrunet** [comment]
Fixer condition pour impression 3D : même si c'est du ponctuel (je lance l'impression puis je reviens chercher mon job) il faut payer son inscription 25e + les 10e à la journée.
Reste à savoir si c'est un job long sur 2 jours est-ce qu'on fait payer pour 2 journées?

**Comment by nicolasdb** [comment]
#### travail sur le ROI
_références_
- http://www.fablab-utopi.org/reglement-interieur/
- https://www.mips-lab.net/informations-pratiques/reglement-interieur
- http://fablab-orleanais.fr/images/articles/2014_10_09_reglement_interieur_FabLab.pdf
- https://fablabmons.be/wp-content/uploads/2015/05/ROI-FabLab-Mons.pdf

et j'aime beaucoup celui ci
http://www.fablab-moebius.org/le-fablab/reglement-interieur/

**Comment by nicolasdb** [comment]
## Table des matières
1. [**Usagers et fonctions**](#1)  
  1.a [membres adhérents]()    
      1.1.1 [User ['juzər] :seedling:](#1.1)  
    1.1.2 [superUser ['supər 'juzər] :herb:](#1.2)  
  1.2 [membres effectifs]()  
    1.2.1 [metaUser ['mɛtə 'juzər] :sunflower:](#1.3)  
    1.2.2 [Pro [proʊ] :deciduous_tree:](#1.4)   
    1.2.3 [Explorer [ɪk'splɔrər] :octocat:](#1.5)   
  1.3 [Guest [gɛst] :wave:](#1.6)
2. [**Règles de fonctionnement**](#2)
3. [**Responsabilités**](#3)

prout
prout
prout

**Comment by zuperninja** [comment]
Je peux me charger de la communication à la communauté. (ceux qui veulent aussi y participer faites moi signe !)

- [ ] enquête formulaire + distribution
- [ ] nouveau ziteweb (landing page avec renvoie vers groupe facebook + github)
- [ ] mailing liste à jour avec envoi vers le formulaire et invitation BBQ (avec gros boutons pour choisir d'encore faire partie ou non)

## BBQ : 

Pour le lieu, le yéti est fermé définitivement ? Mais pas le parc ? On a déjà fait des petites sauteries dans ce parc. On refait un bon vieux molkky!&picole :) Avec réservation payante pour la bouffe (ticket à acheter au lab).

**Comment by satblip** [comment]
@zuperninja peut-être en profiter pour rappeler dans la newsletter pourquoi on a leur email, ce qu'on compte en faire et comment se désinscrire (GDRP)

J'aime bien le parc Felix Hap, je trouve que ce soit sympa que ça soit dans le quartier de l'openfab -> local.

Pour tout le reste, je suis un peu mois dispo pour le moment (jusque fin juillet, encore au boulot et j'ai de quoi faire pour finir ;)), mais je suis chaud d'aider, donc @nicolasdb on s'aligne là dessus demain aussi ;)

**Comment by Valonlisbeth** [comment]
Pour le BBQ (je veux bien me charger de l'organisation)
Que pensez vous du week-end du 7-8 juillet??

**Comment by Valonlisbeth** [comment]
je peux faire la recherche du lieu par la suite et faire des affiches sympas avec Vicky (The Maker Cat sur le BBQ!!XD)

**Comment by DewiBrunet** [comment]
Fixer la date est la priorité n°1 je pense, le plus tôt c'est fixé et les invits envoyée, le plus de monde on aura... Donc fonce @Valonlisbeth ;) 

Le 7/8 juillet j'ai un mariage :'( mais bon, il y aura toujours des gens pas la... sinon w-e du 30-1 juillet?

Je veux bien aider la où il y a besoin. Une fois la date fixée, on est près pour envoyer les invitations? mail + event facebook? (@zuperninja tu te charge de la com mais il te faut quelqu'un pour créer le contenu texte/image?)

@nicolasdb tu parlais de convoquer le CA, tu as déjà commencé la dessus? Dans cette "AG Barbeuk", il y a des obligations vis à vis du nouveau CA (min de membres? vote?...)

**Comment by nicolasdb** [comment]
J'avoue que sur mon retro planning de base, le 30 juillet pour le barbec, c'est déjà 1 mois plus tard. 
Mais bon. On fait comme on peut.

L'objectif **PRINCIPAL** de tout ça. C'est d'avoir un nouveau CA pour signer les appels à projets qu'on gagne. 
Car pas de CA, pas d'appel à projet,
pas d'appel à projet, pas de palais,
pas de palais,...  pas de palais.

**Comment by zuperninja** [comment]
Je peux créer contenu texte/image :) Dès que @Valonlisbeth a une date et un lieu et qu'on a le programme :)

**Comment by Valonlisbeth** [comment]
@nicolasdb le 30 juillet?? ou 30 juin? le premier week-end de Juillet si ça te va alors @DewiBrunet ?
Au fait Sensei, j'ai une réunion de préparation de camp louveteaux avec mon jeune staff le lundi 25 juin et j'ai proposé l'openfab à 13h si cela ne vous dérange pas! héhé tout ça fait partie de la stratégie pour le projet avec eux par la suite!! ^^

**Comment by satblip** [comment]
Moi tout me va tant que je suis prévenu 3 semaines à l'avance je sais être là pour donner un coup de main ;)

**Comment by nicolasdb** [comment]
- J'ai lu 30 juillet dans le com de Dewi. 
- Top pour les louveteaux. 

> nicolasdb, tu parlais de convoquer le CA, tu as déjà commencé la dessus? Dans cette "AG Barbeuk", il y a des obligations vis à vis du nouveau CA (min de membres? vote?...)

De ce que j'ai lu dans les [statuts actuels](https://github.com/openfab-lab/openfab/blob/master/_space/asbl/statuts/statuts.04.2016-OCR.md) , seul les membres effectifs sont officiellement conviés à l'AG par courrier 15jours avant la date de réunion. Seul les membres effectifs ont droit de vote. Dans notre cas, c'est le niv3 metaUser et supérieur. 

C'est pour ça que je m'active sur le processus d'inscription et qu'on puisse tous être à niveau pour les teams et donc pour ceux qui reprenne une place dans le CA. 
Il en faut minimum 3.

Donc pour établir un nouveau CA puisque l'ancien est démissionnaire et ne va plus s'engager dans de nouvelle responsabilité, on doit préparer les sujets suivant qui seront officiellement accepté par vote des membres présents : 
- une mise à jour des status, en rapport à l'évolution de l'asbl actuelle.
- le règlement intérieur
Un PV est écrit lors de l'AG, 
et on doit remettre ça au moniteur belge. 
_ça coute 250€, donc c'est mieux de pas changer trop souvent._

**Comment by Valonlisbeth** [comment]
cc! je propose le week-end du 04-05 Aout 2018, si ça vous va à tous?

**Comment by zuperninja** [comment]
Oh non je serai pas là...

**Comment by nicolasdb** [comment]
On peut tjs en faire une avant fab14 moins fancy et tout. Tant qu'anca est là.
Moi je trouve qu'il est mieux de faire 2 fêtes plutôt qu'une.

**Comment by DewiBrunet** [comment]
je suis en vacances à priori début août...
2 fêtes c'est une mauvaise idée je pense, déjà qu'on arrive pas à en organiser une^^
OU
- une petite fête avec Anne-ca en mode informel, entre habitués, pour préparer l'AG
- AG à la rentrée en septembre

NB : je sais pas comment vous voyez la réunion AG mais pour moi c'est pas juste réunir tous les membres et manger ensemble... ça va demander un temps de préparation (hors logistique du lieu/bouffe) sur ce qu'on va raconter et les résultats qu'on veux obtenir. C'est informel à la cool mais formel aussi parce qu'on a besoin de la vision. C'est un des points les plus important à régler à l'OpenFab qui nous empêche d'avancer (la dernière AG peut en témoigner).

<img src="https://user-images.githubusercontent.com/25649502/41822686-e63e7a4c-77f3-11e8-9d98-2c8e97e39adf.jpeg" alt="alt text" width="300" height="300">

**Comment by Valonlisbeth** [comment]
Moi je pars en camp le 13 juillet. Tu es là jusqu'à quand @zuperninja ??
un truc informel c'est plus rapide en effet! no need beaucoup de comm! ça peut être comme le repas de vendredi, sauf que chacun vient avec quelque chose (plein de poulets!!!) pour après on verra comment faire une fête plus organisée!
Je serais partie normalement du 13 au 2 aout (je reviens le 20 pour repartir le 22) 
voili voiluuuuu

**Comment by satblip** [comment]
Moi je valide "2 fêtes plutôt qu'une." très bonne vision!

**Comment by zuperninja** [comment]
Je pars le 10 juillet au matin :)

**Comment by DewiBrunet** [comment]
Ok, du coup semaine prochaine?

Est-ce qu'on se bloquerait pas une aprem ou matin pour combiner avec le workshop que proposait Milena? https://github.com/openfab-lab/openfab/issues/223

**Comment by Valonlisbeth** [comment]
oui, que dites vous de jeudi soir? (au lieu d'aller à un vernissage!héhé)
mais @DewiBrunet le jeudi 05 juillet ou jeudi 12 juillet?

**Comment by nicolasdb** [comment]
Anca part le 10, et moi le 11.

**Comment by Valonlisbeth** [comment]
Olaaaaaaaa! Bon! j'ai demandé sur messenger, pour vendredi, personne n'a réagit!
On va dire lundi 09! Je vais de ce pas écrire à Milena pour voir si elle est dispo, ensuite, je ferais un post sur le groupe! J'attends vos réactions.... sinon bah le silence aussi sera pris pour de l'acceptation! lol
On va appeler ça Pot de remerciement et de bye bye de Anne-Ca et un Soutien à notre Sensei qui va nous représenter en France! Ceux qui veulent lui donner des doléances pour la Fab14! (sisi j'en ai pleins!!krkrkrkr)

**Comment by nicolasdb** [comment]
je redirige la discussion sur le slack. 
channel @vision 
C'est privé, demandez l'accès. 
bisous
