### ISSUE TITLE
Compta facturation

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#217]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Je suis occupé sur la compta et j'ai des questions sur les factures. 

@zuperninja @DewiBrunet 
Devis B020
Je vois anca pour le backoffice 
Dewi pour la prod 

ça n'a pas été accepté, c'est ça? 
la facture B020 est pour Estelle et l'atelier avec @Anou92 

## objectif
être au clair sur les numérotations, sinon ça va vite être le bordel. 

Perso, je ne met pas de numéro aux devis. Et par contre, je fais bien attention que ça se suive, sans doublons, dans les factures. 
Normalement, on export un pdf que l'on envoie au client via l'adresse de facturation. 
Puis on ajoute le pdf sur le dossier dans le NAS à compta>facture out 2018 où l'on revérifie que les numéros sont ok.

**Comment by nicolasdb** [comment]
@Anou92 
Rappelle moi où on en est avec Estelle? 
La facture n'a pas de coordonnée de facturation. Est-ce que c'est envoyé?

**Comment by Anou92** [comment]
Non je n'ai pas encore envoyé la facture à  Estelle car elle était en vacances.
J'attends qu'elle me renseigne pour les coordonnées.
Je vais régler ça avec elle cette semaine

**Comment by nicolasdb** [comment]
ok, on lui laisse le B020 alors. J'ai édité les suivantes à partir de 21

**Comment by Anou92** [comment]
ok et sinon pour les pochoirs je n'ai pas encore fait la facture.
Je vais la faire maintenant et leur envoyer.

**Comment by Anou92** [comment]
Voila c'est la facture OF-B026.
Bon par contre il faut que je leur demande leur numéro de tva pour l'inclure à la facture. C'est bien ça?

**Comment by nicolasdb** [comment]
yes, pour leur compta, et la notre, c'est important d'avoir les références sur la facture. Sinon ce n'est pas justifiable pour la déclaration TVA. 

C'est la même chose pour vos notes de frais chez smartbe par exemple. 
Si pas les coordonnées complètes, le justificatif n'est pas accepté ou considéré comme un simple ticket qui ne récupère pas de tva.

**Comment by Anou92** [comment]
Ok ça marche je prends note de tes commentaires! haha oui faute de frappe pour la matière je vais corriger ça.

**Comment by Anou92** [comment]
Edoardo vient de me dire qu'ils n'ont pas de numéro de tva. Du coup je mets vente à particulier?

**Comment by nicolasdb** [comment]
Non, tu mets juste "NA" = non applicable

**Comment by Anou92** [comment]
ok ça marche. Je rajoute ça et je leur envoie la facture

**Comment by Anou92** [comment]
oui c'est ça, j'attendais d'avoir les coordonnées d'Estelle pour la facture. Je lui ai envoyé un mail la semaine passée pour avoir les infos mais pas de nouvelles. Je vais relancer.

Et du coup je  fais comment pour la numérotation de sa facture?

**Comment by Anou92** [comment]
yes la facture a été validée par oxfam
