### ISSUE TITLE
 Brussels Waste Orchestra

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#219]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Proposition de Gilles du Guichet d'Economie Locale/Village Partenaire/Centre d'entreprises de Saint-Gilles : 
"En septembre 2018, nous inaugurerons la première recyclerie sociale dans le bas de Saint-Gilles.
Dans ce cadre, nous avons imaginé un projet qui permettrait d’animer cette recyclerie en recréant des instruments de musique à base de déchets. Tu trouveras le projet en annexe.
Penses-tu qu’OpenFab pourrait se joindre à ce type d’initiative ?"

## proposition
J'ai envoyé ça : 

"Sur le cadre de la collaboration, je pense que nous ne serions pas à même de gérer la supervision technique globale mais plutôt comme un accompagnement technique. En fonction des besoins, des constructeurs et du budget je pense qu'OpenFab peut proposer :
- un accompagnement en prototypage (par un des membres, en fonction de la demande)
- un accès aux machines et outils (découpeuse laser, imprimante 3D, CNC, petits outillages)
- ou les deux

Nous pouvons te fournir un devis pour une estimation budgétaire sur base du choix qui te semble le plus adéquat."

**Comment by DewiBrunet** [comment]
... il m'a envoyé le dossier de candidature qu'il souhaite remettre bientôt (avant le 11 juin... donc lundi prochain^^). Je viens de le transmettre par mail.

J'ai pas tout lu, juste la partie financière  :  

"...Coordination technique: 5500€ correspondant à 15 jours de consultance par des luthiers et
fablab dans le cadre de la phase d'incubation"

Donc 367€/jour.

Ca me semble trop peu pour de l'accès + accompagnement mais peut-être trop pour juste de l'accès (en même temps...).

Le projet semble intéressant et fun, on accepte? On propose quoi? Un accès + 1 ou 2h d'accompagnement par jour?

![large_electric-waste-orchestra-1](https://user-images.githubusercontent.com/25649502/41042733-abc31756-69a2-11e8-92dc-d556208f6b8a.jpg)

**Comment by DewiBrunet** [comment]
on peux aussi négocier :  "budget potentiel pour OpenFab qui bien sûr reste à discuter ensemble"

**Comment by DewiBrunet** [comment]
J'ai eu Gilles au tel entre temps, il est pas contre l'idée d'un jour d'accès + 1 ou 2h d'accompagnement (il connait pas le fonctionnement des fablabs en fait). Il est emballé pour collaborer avec nous et si son projet est pas retenu pour le Fonds ING auquel il postule, il compte le reproposer autre part. Ça nous engage pas beaucoup (max 15 jours) donc soyons réactif si ça nous intéresse ;) 

A voir si avec 367€/jour on s'en sort....

Rapide calcul : 25€ abonnement +10€ d'accès + 80€ laser/CNC/3D = 115€, reste alors 252€ pour celui qui accompagne.

Le problème que je vois est de clairement indiquer que pour ces montants ce sera du prototypage ou de l'instrument quick and durty, pour un produit finit faudra p-e avoir plus de moyen (genre le luthier sur la CNC, il avait mis combien de temps?)

**Comment by nicolasdb** [comment]
-poke-

on en est où? sujet clos?

**Comment by DewiBrunet** [comment]
![im-not-going-to-follow-up-any-further-im-just-going-to-assume-that-everything-went-according-to-plan](https://user-images.githubusercontent.com/25649502/44535303-f60e4d00-a6f9-11e8-84bc-220db12c0500.jpg)

**Comment by DewiBrunet** [comment]
Blague à part, c'est en attente de réponse j'imagine comme c'est un appel à projet.
Mais encore une fois, ça vaut p-e le coup de retoper Gilles? (ça m'emmerde de faire ça mais je crois qu'il y a pas le choix, faut mettre en place le flow "excuse me sir" ^^)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/44535804-33270f00-a6fb-11e8-95f5-1180dd382908.png)

**Comment by zuperninja** [comment]
J'ai un bouquin sur faire des instruments à partir de "déchets". Dans le
bundle MakerSpace

**Comment by nicolasdb** [comment]
j'imagine que c'est mort cette histoire. ...

**Comment by DewiBrunet** [comment]
Yep on ferme     
![téléchargement](https://user-images.githubusercontent.com/25649502/54623930-bf6c9b00-4a6c-11e9-80f6-46c3ae66404b.jpg)
