### ISSUE TITLE
Nouvelle gestion membres

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#22]
Comment amener les anciens membres à mettre à jour leur statut et participer à la gamification?

- profiter de la rentrée en septembre comme date de mise en opération du système ?
- tant que les check-list de niveau ne sont pas complétées, le statut n'est pas actif ? Attention à la logique des étapes, pour documenter la réalisation de son passeport, il faut déjà avoir son compte github, et pour obtenir des crrr il faut son passeport pour les y collecter. 
- ces conditions doivent être connues et acceptées via le règlement d'ordre intérieur. RTFM.

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by softrevolter** [comment]
ajouté au events Bricole et Picole

https://github.com/openfab-lab/openfab/blob/master/Events/Bricole-Picole.md
