### ISSUE TITLE
Workshop - mecaniques discursives

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#221]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Bertrand a mis en lien Openfab pour une proposition de modules dans le cadre de ce projet.
http://www.mecaniques-discursives.com

- Remise du dossier par "Julie" début juillet; contact de Bertrand. B/ qui fait le lien avec PointCulture.
- Proposition pour 2019/2020 (des ateliers a proposer sur 2 ans avec des jeunes)

## objectif
Discuter d'une proposition d'intégrer le fablab dans le processus.

**Comment by nicolasdb** [comment]
Next step/ 
@DewiBrunet si t'es dispo lundi 18 à 9h30 jusque 11h.  Bertrand viendra discuter de ce qui est possible.
Je pense qu'on pourra définir une offre similaire à brussels waste orchestra. à discuter de vive voix pour mieux cerner les besoins.

**Comment by DewiBrunet** [comment]
### Contexte : 
Exposition itinérante en Wallonie sur 2 ans (février 2019-2021), toutes les 3 semaines.
Organisé et financé par Pulsar (promotion de l'art contemporain dans les centres culturels wallons).

Besoin d'une partie médiation/workshop/dessous de la création en "sortant de l'atelier tampon en patate".

### Proposition : 
Atelier/sensibilisation pochoir papier. Avoir une banque de formes d'animaux que les participants peuvent choisir et découper avec la mini laser. Puis avoir rouleau de peinture pour venir combiner les têtes/corps d'animaux.
En continu, toutes les 30min ou 1h.

Faire une phase test avec ça, avec la possibilité d'atelier plus construit (et payant).

Au niveau du prix : 
- 2 animateur à 350€/jour
- location module laser
- transport
- marge de rentabilité OpenFab!!

= +/- 1000€/jour?

### A faire (proposition max 2 juillet) : 
- Quelques tests d'exemples
- Fixer tarif

**Comment by zuperninja** [comment]
Attention au temps d'engagement ! Qui se voit faire ça encore en 2021 ?

**Comment by nicolasdb** [comment]
Tuto inkscapes
http://tavmjong.free.fr/INKSCAPE/MANUAL_v14/html_fr/AShortExampleEU.html

**Comment by DewiBrunet** [comment]
J'ai eu Bertrand au tel, il faut une réponse ce soir (Julie propose le projet ce lundi).

Attention en effet au temps d'engagement, si on estime à la hausse, ça veux dire que 2 personnes doivent dégager respectivement 35 journées temps plein sur 2 ans (mais ça ferait rentrer 5000/6000€ brut/an). VOici donc ma proposition qui reste évasive pour négocier après les termes de la fréquence:



## Proposition d’un volet médiation pour l’exposition.

### Concept
« A la manière » de Frédéric Penelle et Yannick Jacquet, OpenFab souhaite mêler savoir-faire traditionnel et nouvelles technologies. Comme Gutenberg à son époque, OpenFab propose un atelier d’impression itinérant avec une découpeuse laser.

Nous aimerions vivement pouvoir rencontrer les artistes au préalable afin notamment de pouvoir adapter le contenu graphique avec eux.

### Déroulé
Sur un ordinateur, les participants pourront choisir dans une banque de formes morcelées (animaux, typographies…). Avec leurs formes, ils pourront découper dans du papier avec une mini découpeuse laser. Ensuite à l’aide d’encre, les participants pourront combiner leurs pochoirs dans une réflexion discursive et venir imprimer leur création.

En fonction du choix du public cible et de la durée la plus adéquate, nous pourrions éventuellement concevoir des ateliers plus complets en recréant des GIF sur papier ou des vidéos en stop-motion par exemple.

### Durée
Nous pouvons proposer des ateliers fréquents durant une journée pour toucher plus de participantes ou des ateliers sur plusieurs jours pour un travail créatif plus complet, voire les deux. Nous souhaiterions en discuter ensemble ainsi que de la régularité de notre venu sur deux ans.

### Budget par jour
2 Animateurs 800
Location module laser 100
Transport 110
Consommables 60
Total : 1070 (1260ttc)

NB bidouille interne : les animateurs seraient payé 350, 10 serait pour le backoffice et 40 revient à OpenFab

QUESTION : 
- 100/jour pour location du laser/caisse/entretien machine... ça suffit? (pas envie de se retrouver avec la même situation que fabmob et devoir revoir le tarif animateur!)
- est-ce qu'on est sur que ce sera pas un problème logistique avec fablab mobile pour la location des machines/caisses?
- le transport reste problématique je penses, 110/jour ça fait cher... c'est ce que j'ai trouvé sur http://www.taxisverts.be/envoyer-colis-express/
- niveau engagement, je serais d'avis de signer une convention au préalable avec les 2 animateurs (en laissant une possibilité de remplacement) pour pas devoir passer du temps à chercher qui fait l'animation à chaque fois. Moi ça m’intéresse de m'engager sur 2 ans, qui sera le 2ème? Nico? Navid?

@nicolasdb @zuperninja vous en pensez quoi?

**Comment by nicolasdb** [comment]
- 100€/J de maintenance, ouais, x35j, 3500€ ça rentabilise un module. à confirmer sur base du tps de prod mais je pense que c'est notre budget achat matériels total pour 4 modules. 

- Si on prévoit à l'avance, ça devrait aller. Si on voit qu'il y a conflit, on pourra produire un module indépendant à fabmob. Le conflit n'est aussi que d'un an (2019)

- transport, oui, faudrait trouver autre chose de plus souple aussi. Si c'est sur bruxelles, le vélo cargo reste une bonne solution. En dehors, ça va vite être plus cher. Je reste d'avis que le transport ne devrai pas être un prix fixe. Ou alors faire une sorte de frofait en fonction des distances. 
Là aussi, il faudrait voir comment marche Smart, il me semble qu'il y a des camionettes en location partagée. (c'est peut-être fini aussi, je sais pas)

- yup, comme on a dit oui, bosser sur une convention. Ce serai d'office bien. Le workshop est récurrent donc c'est d'autant plus simple pour un animateur d'acquérir une habitude.

**Comment by nicolasdb** [comment]
C'est fait ça non? 
On clot le sujet?

**Comment by DewiBrunet** [comment]
Yep (gardons quand même ça comme référence pour des tarifs workshop)

**Comment by nicolasdb** [comment]
oui, si tu as le mail ou un doc avec le devis, ça serait pas mal de l'ajouter sur le drive wortkshop aussi, comme référence
Et mettre @satblip dans la boucle, team workshop powa
