### ISSUE TITLE
Appel à projet - SAU

### ISSUE THREAD

**Issue by satblip** [openfab-lab/openfab#222]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte

La Société d’Aménagement Urbain (SAU) publie ce jeudi un Appel à manifestation d’intérêt (AMI) pour identifier des porteurs de projet susceptibles d’assurer une occupation temporaire sur une partie du site de l’ancienne école de gendarmerie, au coin du boulevard Général Jacques et de l’Avenue de la Couronne, à Ixelles.

http://www.sau.brussels/fr/actualites/la-sau-cherche-des-occupants-temporaires-pour-le-site-usquarebrussels

## objectif

Ce serait peut-être intéressant non ? En faire un espace de coworking makers, ce serait une belle vitrine et en 3 ans on peut voir si c'est rentable ou pas et donc couvrir le déménagement par après, non?

**Comment by nicolasdb** [comment]
ha ben oui, c'est bien ça. 👍 

GoGoGo

**Comment by satblip** [comment]
Opération « entreprenariat et innovation » visant à accueillir un incubateur commun ULB-VUB, un
FabLab et un StartLab. Ces programmes se développeront dans le cadre de projets de
reconversion et de construction sur une surface de **+/- 6.000 m²** (dans les bâtiments F et G).

**Comment by satblip** [comment]
Le dossier est ici : http://www.sau.brussels/sites/default/files/actualites/ami-caserne-usquare.pdf

à voir : **point II.4 Critères et sélection des projets** 
à remplir **au plus tard pour le mercredi 04 juillet 2018 à 11h00.**

**Comment by DewiBrunet** [comment]
![wait-were-moving-to-a-new-office](https://user-images.githubusercontent.com/25649502/41682386-e2c986b4-74d7-11e8-9438-2e3957b991a3.jpg)

### Pour résumer : 
- possibilité d'un local beaucoup plus grand
- possibilité de pas payer de loyer
- seule contrainte : devoir dégager dans 3 ans

DONC ça peut être un bon jackpot. C'est pas loin donc le déménagement est facile et on perds pas la communauté (et surtout pas payer le loyer... faut faire le calcul : 12 x 800 = 9600 économisé par an!).

Et à la différence de l'appel Next Tech, il n'y a pas vraiment de nouvelles idées à formaliser ;)

### Pour le dossier, on doit écrire 13 pages MAX sur : 
1) Note de compréhension (1 page pour vérifier qu'on comprends le projet^^)
2) Note de projet (10 pages)

"L’objectif est d’évaluer la valeur ajoutée du projet d’occupation temporaire et sa compatibilité avec le
site...  valeur ajoutée pour le quartier, économie circulaire, ancrage local et rayonnement à plus large échelle..." en gros faut juste décrire ce qu'on fait déjà^^

3) Note organisationnelle (2 pages sur nous : ma vie, mon oeuvre et mes poireaux)

@satblip @nicolasdb @Valonlisbeth @zuperninja on s'y met?
Qui veux/peux quoi sur cette to do : 

- [ ] Bien lire l'appel à projet et ses conditions (si ça se trouve on est pas éligible^^)
- [ ] Note de compréhension (ça va avec la lecture de l'appel)
- [ ] Note de projet (expliquer ce que fait OpenFab)
- [ ] Note organisationnelle (en gros dire qu'on est pro et respectueux)

Si on est chaud, prévoit-on un meeting avant la deadline le 4 juillet?

**Comment by zuperninja** [comment]
Je suis chaud, je suis là ! :) 

Je lis le bazar et je veux bien déjà écrire mon résumé que je posterai ici

**Comment by zuperninja** [comment]
## Note de compréhension


En gros, quand on occupe OF doit : 

- [ ] Assurer nos activités et les manifestations publiques
- [ ] Bien gérer la sécurité du lieu (safety first)
- [ ] Investissement et travaux à notre compte
- [ ] Payer charge et loyer (si commerciale)
- [ ] Participer aux réunions organisée par le coordinateur et accepter les ROI et conventions.


#### !!! WARNING !!!

> 11. L’occupation temporaire peut s’envisager à titre gratuit, dans la mesure où l’activité implantée n’est pas génératrice de recettes pour l’occupant temporaire.  
> 12. Les occupants temporaires assumeront à tout le moins et proportionnellement aux activités proposées, les charges inhérentes (eau, gaz, électricité…) à l’utilisation du bien. 

> OpenFab manifeste sont intérêt pour s’implémenter temporairement sur le site de l'ancienne Caserne d'Ixelles.
> 
> OpenFab comprend l'opération de reconversion de l'ancienne Caserne et son caractère amélioratif et d'ouverture pour et sur le quartier, Bruxelles, et la région en générale. Et comprend, en conséquence, que le site et les bâtiments seront soumis à des travaux de dépollution des sols et de désamiantage, ainsi que la réalisation des études de conception pour la suite des opérations.
> 
> OpenFab s'engage à activer, gérer et entretenir le site, ainsi qu'à agir et interagir avec les riverains. De par son but social (inscrit dans les statuts de l'ASBL) et sa mission de mise en capacité // de lieu ouvert à tous pour apprendre, et partager. (???)
> 
> OpenFab comprend les tâches nécessaires à effectuer de sa part pour aider la coordination du lieu, et s'engage à assister aux réunions impluser par le coordinateur.
> 
> OpenFab est prêt à offrir son expertise à se projet transitoire pour : 
> - Ancrage et animation locale du site. 
> - Ouverture et rayonnement de ce nouveau quartier. 
> - Accompagnement et identité du projet Usquare.brussels
> 
> OpenFab s'engage à signer une convention d'occupation précaire avec les autorités régionales sous les conditions précisées par la SAU.
> 
> OpenFab comprend que la SAU et/ou le SPRB n'interviendront pas dans les investissements et les travaux nécessaires à l'occupation temporaire du lieu. OpenFab assurera la sécurité de ses usagers et visiteurs et mènera ses activité dans le respect des réglementations en vigueur ainsi que l'obtention des autorisations administratives propre à son activité. Pour cela OpenFab est prêt à fournir tout document nécessaire de la part de son assureur (pour ses activités et manifestations publiques).
> 
> OpenFab s'engage à respecter les conventions et le règlement d'ordre intérieur du site.
> 
> OpenFab comprend que son occupation temporaire doit répondre au futur cadre d'opération de Usquare.brussels. OpenFab, de par sa nature, sera complémentaires avec les autres activités, le quartier, et la ville. Valeur ajoutée pour les habitants.
> 
> OpenFab garantit l'accès à son occupation à la SAU, la Région, les universités ou leurs représentants.
> 
> OpenFab comprend que les communications publiques doivent se faire de façon concertée et en commun.


### A rajouter :

La vision d'OF de la phase de gestion transitoire et comment OF répond aux objectifs et enjeux. En se basant sur ça : 
-> "La SAU et ses partenaires souhaitent, bien entendu, que la phase de gestion transitoire puisse autant que possible préfigurer le futur aménagement urbain ouvert sur le quartier et la ville prévu sur le site."

![image](https://user-images.githubusercontent.com/25099826/41712899-fe20cbc4-754b-11e8-8e1d-a79917cb1814.png)

![image](https://user-images.githubusercontent.com/25099826/41712941-21236cb2-754c-11e8-8537-27ff4f9d6802.png)

![image](https://user-images.githubusercontent.com/25099826/41712995-429f113e-754c-11e8-98e4-b30348c2af96.png)

**Comment by nicolasdb** [comment]
De là, on a aussi une plus grande agilité et mobilité. 
Faire le lien avec les lieux d'incubation, les lieux de productions, de prototypage, les machines immobiles. 
Et faire le lien avec l'internationnal, les autres lieux, les autres communautés via Vulca principalement.

On pourrait écrire une note d'intention ou une lettre de recommandation à faire signer par tout nos copains d'un peu partout, avec qui on a bossé, avec qui on résonne. 

Voir avec Michel Bauwens, lui faire une note d'intention. Comment renforcer notre discours et que ça lui serve d'un exemple concret supplémentaire. Faire le lien avec la smart?

Exemple de ceux chez qui ont a influé/inspiré quelque chose :
Village Partenaire / Smart 
Crédal
Osmos
Vulca (EU)
CHIC (FR)
FabFoundation (World)
Plaine Commune (FR)
La Jacqueline
Make it Sound
CIN
Gobo
DewiOrigami
En Stoemeling
~~Hackistan~~ (= CIN)
Fablab Slovenie, Zagreb, ParthLab (internat.)
L'Heureux Nouveau
Digizik/Denis Meyer/un truc près des casernes
Giacomo Falaccie = fablab toscano

**Comment by nicolasdb** [comment]
## the turkey and the bull
A turkey was chatting with a bull. 
\- "I would love to be able to get to the top of that tree," sighed the turkey, "but I haven't got the energy."
\- "Well, why don't you nibble on some of my droppings?" replied the bull. "They're packed with nutrients."

The turkey pecked at a lump of dung and found that it actually gave him enough strength to reach the lowest branch of the tree.
The next day, after eating some more dung, he reached the second branch.
Finally after a fourth night, there he was, proudly perched at the top of the tree. Soon he was promptly spotted by a farmer, who shot the turkey out of the tree.

Moral of the story: Bullshit might get you to the top, but it won't keep you there.

**Comment by Valonlisbeth** [comment]
Bonsoir Bonsoir!
comme l'a déjà dit le sensei, hier j'ai pu assister à la présentation de Lieven (fabmanager fablab Brussels) du projet du nouveau big Fablab de la VUB et ULB sur le site des Casernes!
(je ne sais pas comment ajouter une image de mon pc dans un commentaire sur Github donc je vais juste expliquer lequel des bâtiments il s'agit en m'appuyant sur la carte présentée plus haut : 
Donc à long terme le fablab + des salles de classe s'étendra sur les deux bâtiments reliés par une croix en verre F et G sur la carte mais pour OCTOBRE 2018 le fablab Brussels occupera le rez-de- chaussée du batiment G tandis que la fablab ULB (de Victor Levy) sera au premier étage du même bâtiment! 
Selon les plans finaux pour dans 3 ans (Lieven pense que ça prendra plus, genre 5 ans, l'espèce de croix en verre qu'il y a entre les deux bâtiments va disparaitre pour laisser place à un bâtiment (En verre encore parce que ça coute cher et que c'est BEAU) qui fera tout l'espace entre les deux bâtiments et qui va habriter un autre Fablab mais cette fois-ci commun des 2! Parce que un Fablab dans un long rectangle en verre c'est COOL! Ha ha!
BON, Lieven a proposé à Victor de faire un unique Fablab mais Victor n'est pas trop chaud et il doit aussi s'entendre avec ses collègues des autres facultés de l'ULB pour faire un fablab non pas pour seulmenet la fac d'archi mais pour TOUT l'ULB, et bon, il préfère que chacun se gère durant 3 ans et Ensuite "on verra" (sacré Victor...) Mais du coup, la mise en place de son fablab risque d'être repoussée...dans les délais des universitaires...( ça me rappelle d'autres institutions tiens...)
MAIS Lieven lui, n'a aucun souci avec ses collègues des autres facultés et de Plus à le pleine appui de SA faculté à lui! Il ne pense pas faire "un fablab pour toute la VUB" mais juste un fablab pour la faculté des ingénieurs qui serait ouvert à TOUS! si les autres facultés s'impliquent, bah elles pourront aussi avoir une empreinte plus visible, sinon bah leurs étudiants seront bienvenus en tant que visiteurs et pis c'est tout! ça lui permet d'être super plus rapide dans la mise en place! Pour lui, le 1 er Octobre, il y sera, même si la peinture n'est pas finie, qu'il doit faire lui même le système électrique etc! Il a déjà répertorié toutes les machines qui vont partir (certaines resteront à l'Erasmus Hogeschool), les plans 3D des aménagements sont déjà faits, bref Touuuuuuuuuuuuuuut est prêt pour qu'il aille s'y installer!!!

DONNNNNNNNNNC après toutes ces précieuses informations, je lui ai demandé si il était au courant de l'appel à projet? il a dit NEINE! lool nous avons cherché le site ensemble, il l'a lu et tout était même surpris! Il sait qu'il y a une volonté d'inviter des écosystèmes plus entrepreneuriaux dans le coin mais de l'appel à projet, il n'avait pas entendu parler! (je fais mon maitre Yoda!) Je lui ai dit : bah L'OF est intéressé! Première réaction:" Say them to call me!!" Ha Ha! Bon il a dit que ce serait intéressant de voir comment présenter la chose pour être complémentaire d'une certaine manière parce que bon, un petit fablab à coté de 2 Big Fablabs, ça pourrait paraitre un peu nase quand même... Du coup, il m'a dit de lui dire un peu les spécificités d'Openfab et les éventuels "gagnant-gagnant" de l'affaire! Biensûr j'ai vendu l'histoire de l'Europe, Vulca, Passeport maker (ha au fait, il va être à fond "automatisation" dans son Fablab, donc il va arriver très vite avec des systèmes de badges pour permettre d'accéder directement aux machines... vu l'espace qu'ils auront, il n'a carrément PAS le temps d'être derrière chaque personne.)
Il a trouvé ça intéressant, par exemple pour Vulca, bah il y a des chambres sur le nouveau campus, qui pourrait servir pour loger les makers transitaires et tout! Bref il y a moyen de trouver un arrangement! Il est aussi à la recherche de personnes qui peuvent lui permettre de se décharger au MAXIMUM des tâches qu'il trouve chiantes (bon il dit qu'il n'a pas le temps > ça aussi j'ai déjà entendu ça quelque part...) : workshops, initiation aux machines (qu'il remplace purement et simplement par des systèmes de tutorials) etc...

VOILA VOILAAAA!!!!!!! DONNNNNC (c'est le dernier "donc"! promis) 
Il propose de se rencontrer au plus vite afin de discuter des pourquoi et comment (une expression de chez moi) pour voir comment agencer les choses pour que si l'Openfab rentre l'appel à projet, bah qu'il fasse au moins une note pour expliquer les complémentarités et tout! Parce que c'est chaud de parler Fablabs alors que 2 fablabs universitaires s'installent et un 3è sera en construction...
Mardi matin il sera en visite sur le site des casernes! Il sera libre à partir de 14h, il pourrait alors visiter l'Openfab qu'il ne connait pas d'ailleurs (je vais sérieusement penser à organiser un maker Tour pour les fabmanagers bruxellois eux-mêmes...) et discuter en live! 
Ou Mercredi, il sera au fablab Brussels, à l'Erasmus Hogeschool mais il a des réunions et tout donc il sera libre entre 14h-15h et 16h-17h (je dois vérifier)!!

Je suis sensée lui envoyer un SMS sur son GSM ou l'appeler lorsque vous aurez décidé de quand!

Au fait, ilSensei @nicolasdb , tu as bien oublié de citer BSproutLab...... va be' et c'est Giaccomo Falaschi= Fablab Contea-Toscano!

Voiiiliii voiiilouuuu!!! Rapport de mission de l'Agent Colibri pour le siège du Maker Cat! A vous!!

[https://media.giphy.com/media/abZldcGbaqEuI/giphy.gif](url)

**Comment by nicolasdb** [comment]
yeah. Merci pour ce rapport Agent Colibri.
j'ai réunion mardi matin avec Giordano,; je serai de retour pour 14h au bureau pour Lieven, ce sera plus relax alors que à Erasmus s'il faut le voir entre 2 réunion. 

D'ici là on affinera une idée plus clair de winwinwin. 

@Valonlisbeth; biensur que j'oublie pas BSproutLab, t'es la famille. Mais je ne pensais pas spécialement faire intervenir les autres fablabs pour la lettre, mais on pourrait oui. 
Si on a un objectif de guilde, faut qu'on ai le support des autres. 

note pour sarah, 
Pour mettre une image. Quand tu édite une issue, pour ajouter une image, c'est marqué en bas de la fenêtre d'édition.  drag/drop, copy/past ou selecting the item.

Pour les gifs, faut insérer le lien de l'image dans les balises markdown. 

`![image animée lol](https://media.giphy.com/media/abZldcGbaqEuI/giphy.gif)`
![image animée lo](https://media.giphy.com/media/abZldcGbaqEuI/giphy.gif)

**Comment by zuperninja** [comment]
Pour le futur d'OpenFab est notamment ce changement vers les casernes. On pourrait accentuer notre côté guilde de makers. 
On a besoin d'un local pour réunir notre communauté, partager à manger, travailler sur le côté européen, sur le passeport, sur les communs. En fait un lieu où nous pouvons explorer le futur du fablab. 
Une grande pièce avec nous tous dedans + un atelier de machine en prototypage pour ceux qui ont leur badge explorateur pour explorer les machines et la technique.




### Guilde

Recherche rapide sur les Guildes : 
> [
"Organisations de solidarité, les guildes protégeaient les intérêts communs d’un groupe, artisans ou commerçants. D'abord apparues dans l'Europe du Nord-Ouest, elles se sont propagées aux XVe et XIVe siècles dans l’ensemble de l'Europe avec le développement des liens commerciaux. Les guildes d'artisans, apparues au XIIe siècle, géraient la surveillance de la qualité des produits et assuraient la protection des marchés. Leur contrôle portait sur l’atelier du maître-artisan, mais aussi sur l’échange des compétences entre les ateliers collaborant à la fabrication d’un même produit." ](http://expositions.bnf.fr/flamands/arret/05.htm)

> ["des hommes [ou femmes hein dis] ayant des intérêts communs (marchands, artisans, paysans même) et mal garantis par les liens de dépendance et de protection du système féodo-vassalique. [...] Fraternités de cooptation, les guildes introduisent dans le système de sécurité communautaire un élément supplémentaire, à un niveau différent de la commune et de la communauté taisible. C'est ainsi qu'elles ont notamment assuré la cohésion économique des marchands originaires d'une même ville dans leurs opérations sur les autres marchés. "](https://www.universalis.fr/encyclopedie/guilde-gilde/)

[The Silent Revolution: A New Perspective on the Emergence of Commons, Guilds, and Other Forms
of Corporate Collective Action in Western Europe](https://www.ris.uu.nl/ws/files/20096187/_PUB_SilentRevolution_IRSH_53_Suppl.pdf)
Résumé par Michel Bauwens : 
> "le nombre d’accords de guildes et de communaux a littéralement explosé au 12ème siècle, une véritable explosion des pratiques de mutualisation que les commoners et les travailleurs ont utilisé pour créer de la solidarité face à l’insécurité de la vie."

**Comment by nicolasdb** [comment]
ho yeah, you mean, we nead.... a LAIR!


![image](https://user-images.githubusercontent.com/12049360/41818541-5d20d954-77b1-11e8-8cd5-d3f6872bff38.png)

# Bravest makers!!!
![image](https://user-images.githubusercontent.com/12049360/41818485-8f237df4-77b0-11e8-8c94-b65eef74940a.png)

**Comment by nicolasdb** [comment]
Aussi. 
On va pas pouvoir prendre Vicky avec nous.

**Comment by DewiBrunet** [comment]
Merci agent colibri pour cet input!

Anne-Ca, c'est parfait ce que t'as écris, on a déjà la note de compréhension du coup :)

Nico, super la liste de ceux chez qui ont influé/inspiré quelque chose, ça va nous aider!!!

Par contre cette division entre l'ICAB pour le business; ULB/VUB pour le monde académique et OF, un petit fablab de proximité pour les makers me semble pas la bonne approche. Pourquoi on pourrait pas être sur les start-up et le monde académique? et cette idée de relais entre les gros cailloux, qu'est ce qu'on y gagne NOUS dans l'affaire? On est certe petit mais certainement pas dans nos ambitions ou les innovations qu'on veux proposer!

Et au risque de passer pour le briseur de rêve, cette "Guilde de makers" est excellente en théorie mais en pratique j'ai du mal à imaginer la chose. Où est la viabilité économique derrière ça? (oui c'est génial d'avoir une guilde, un lair mais faut faire du fric pour faire tourner ça).

Pour moi on en revient au problème crucial de la vision... c'est quoi OpenFab? (nos valeurs, nos rêves, notre business model, notre écosystème...). Et ça devient critique car qu'est ce qu'on va bien pouvoir dire à Lieven du coup? La proposition de Milena est excellente pour avancer la dessus : https://github.com/openfab-lab/openfab/issues/223 

<img src="https://user-images.githubusercontent.com/25649502/41823160-8088c812-77fb-11e8-8149-9201ddc3a539.jpg" alt="alt text" width="300" height="300">

**Comment by nicolasdb** [comment]
Pour moi la vision ne doit pas parler de business model. C'est l'objectif idéal vers lequel avancer.
Ensuite on fait le retro planing, et pour chaque étape on établit le plan financier realiste pour atteindre la première étape, ensuite on ajuste plan financier ou objectifs suivant les résultats.

La réflexion précédente n'est qu'une réflexion par rapport spécifiquement à la situation de concurrence ou d'opportunité face à des structures avec qui ont ne peut pas rivaliser sur les arguments d'argents ni sur leur corps de métier qu'ils représentent depuis si longtemps. Sur ce terrain, si on leur fait frond, on se grille même si on est sur une bonne route. 

Donc vision oui, 
En fonction comment se positionne t'on face à eux, 
on s'adapte et on trouve comment les carresser dans le sens du poil, histoire de bénéficier de leur structure , grandir de l'intérieur, symbiose parasitaire... (Voir alien 1,2,3 et 4) 
Ou On rentre dans un rapport de force. Combat dont on a pas les moyens, certainement pas financier.

Ensuite, business model à adapter selon choix. 

On en discute demain avec le café. :)

**Comment by zuperninja** [comment]
Après le RDV avec Lieven j'ai écris ça.

![image](https://user-images.githubusercontent.com/25099826/41920458-0a2c1bd0-7961-11e8-8683-1eeec8838cd2.png)

**en quoi son projet d’occupation temporaire est en mesure de répondre aux objectifs et enjeux présentés au point I.1.** 


> OpenFab est une communauté de makers du quartier de la Couronne avec de fortes relations avec le reste de l'Europe. OpenFab cherche à déplacer son local dans un lieu plus grand.
> OpenFab est intéressé par occuper une partie du site temporairement et certifie répondre aux besoins de la SAU.
> 
> En effet, OpenFab est un groupe de makers, entrepreneurs et passionnés qui explorent de nouvelles façons de faire (social, économique, et apprentissage). Une communauté de personnes recherchant la collaboration et la transmission de savoirs tout en s'appropriant les outils et la méthodologie de l'usinage.
> Au travers de son ouverture sur le quartier, OpenFab permet aux habitants de partager des connaissances, des machines, et des projets lors de différents événements et workshops.
> 
> OpenFab participe à plusieurs projets sur la RBC et l'Europe. Comme le programme CHIC (création d'un réseau de makers en Europe autour de partage de savoir), le programme VULCA (résidence et mobilité des makers dans l'Europe), le projet FabMob (fablab mobile pour donner des ateliers à un public de 6 à 10ans en RBC). 
> 
> OpenFab développe aussi une communauté soudée pour favoriser la collaboration entre professionnels et passionnés. Des projets transdisciplinaires qui fructifient en workshop, success story, et productions locales. 


> OpenFab travaillera en collaboration avec le fablab de la VUB pour maximiser l'utilisation des machines et des lieux (workshop en collaboration avec la commune et la VUB).
> 
> OpenFab pourra aussi assurer la production plus conséquente que les membres du fablab peuvent avoir besoin. 
> 
> OpenFab permettra les échanges avec l'Europe et avec des clients, en permettant aux membres d’accéder à une sécurité et un accompagnement lors de la réalisation des ces projets et commandes = un espace pour travailler = des membres pour les soutenir = un moyen de facturer = la confiance openfab.

**Comment by nicolasdb** [comment]
J'ai lu un truc intéressant. 
ça pourrait nous donner les mots qu'il nous faut pour exprimer ce qu'on peut apporter de complémentaire aux fablabs ulb/vub. 

> **Plus « il y a de la technologie », plus nous avons besoin de lieux physiques favorisant une réelle appropriation sociale de ces technologies ?**  
> \- La suprématie d’une vision scientiste, la représentation du monde à travers la science et la technique, l’efficacité de la preuve par l’expérience, la technique (en) « marche » et s’impose comme vision du monde au détriment d’une approche sensible et plus proche du fonctionnement de la nature.  
> \- Nous sommes également parfois, contre notre gré, complètement partie prenante dans « l’écosystème » créatif et innovant : les *labs (fablab, medialab, hacklab, …) comme avant garde de l’innovation (avec par exemple la récupération des hackatons par les démarches entrepreneuriales), nous sommes parfois défricheurs de futurs terrains fertiles mais dont les légumes et les fruits seront récoltés par des start-ups à la pointe de l’intégration capitaliste de ces dynamiques créatives et de partage.  

https://medium.com/@julbel/lieux-trans-num%C3%A9riques-entre-pratiques-populaires-et-r%C3%A9-appropriation-des-technologies-ec375c90532b

**Comment by zuperninja** [comment]
### Note de compréhension

- [ ] Mélanger vision et compréhension. Textes @zuperninja à réécrire. Rajouter ça "permettra aussi d’activer, de gérer et d’entretenir le site, ainsi que de favoriser son appropriation par les riverains"

### Note de projet

![image](https://user-images.githubusercontent.com/25099826/41979835-4647da2c-7a25-11e8-85ac-2f7d3996a5f7.png)

- [ ] La nature de l'occupation d'OpenFab dans ce lieu = de quoi on a besoin et comment (environ 150m²?)
- [ ] Le public-cible d'OF d'ajd et celui qu'on veut aussi toucher
- [ ] Programme : organisation et fréquence des events/ateliers/workshop (bricole & Picole, brain candy)
- [ ] Durée de l'occupation
- [ ] Financement

![image](https://user-images.githubusercontent.com/25099826/41979992-ad7ee0d2-7a25-11e8-9480-ca924c6a74bc.png)
C'est à dire un plan 3D type sketchup, ou juste colorer les plans qu'on a reçu avec une légende.

- [ ] espace bureau
- [ ] espace assemblage + stockage
- [ ] espace machine exploration (soft : 3D, tissu, laser, robotique, soudure + bois ?)
- [ ] kitchenette
- [ ] surface travail

![image](https://user-images.githubusercontent.com/25099826/41980114-023928f8-7a26-11e8-93a9-4a06f16e543e.png)
Même plan mais avec les : 

- [ ] flow de sécurité (où sont les extincteurs, la sortie de secours, les panneaux indicatifs, la boite de premier secours, etc)
- [ ] flow de entrée sortie du client ou futur membre (zone pour membre et juste workshop)
- [ ] flow d'évacuation fumée/poussière

![image](https://user-images.githubusercontent.com/25099826/41980468-d95e8652-7a26-11e8-914c-a9deb758c3e0.png)
-> ancrage locale
- [ ] Communa
- [ ] Artisan 2.0
- [ ] On est déjà présent dans le quartier (prems!)
- [ ] Nos membres habitent dans les 15min à pied
-> rayonnement plus large échelle
- [ ] Vulca
- [ ] Chic
- [ ] Passeport Maker
- [ ] Europe
-> ambition de usquare.brussels
- [ ] Développer un lien de projet entre les habitants
- [ ] Mutualisation des machines à l'échelle de quartier
- [ ] Espace pour les entrepreneurs qu'ils puissent prototyper et se professionnaliser / se rassembler

![image](https://user-images.githubusercontent.com/25099826/41980715-71e716fa-7a27-11e8-8ab4-7871208d0375.png)
- [ ] Assurance, faire un point avec notre assureur
- [ ] Pas d'autre besoin administratif  ?(siège social, CA, AG)

- [ ] Moyen propre pour le déménagement et installation + aménagement
- [ ] Faisabilité technique = voir le lieu d'abord (surtout attention au branchement électrique). Pour le plus 6 mois on a pas besoin d'aménagement lourd particulier.

![image](https://user-images.githubusercontent.com/25099826/41980897-ec84847e-7a27-11e8-9e87-6fd88c226027.png)
- [ ] Timeline planning à faire en fonction de notre bail
- [ ] Un mois d'aménagement 
- [ ] Début d'activité en décembre
- [ ] Présent pour toute la période transitoire, à rediscuter avec le coordinateur dynamique.

### Note organisationnelle

![image](https://user-images.githubusercontent.com/25099826/41981413-25d5ce8a-7a29-11e8-820e-e109696dc764.png)

- [ ] Présenter l'équipe et l'apport de chacun : 
    - Nico (gestionnaire espace + accompagnateur)
    - Dewi (project manager + animateur + accompagnateur)
    - Anne-Camille (secrétariat + gestionnaire de communauté + communication)
    - Louis (dev)
    - Sarah (animateur + ambassadeur)
    - Milena (animateur + project manager + ingénieur)
- [ ] Partenaire public et privé et leur répercussion sur OpenFab
   - FabMob
   - Flop Académie
   - Artisan 2.0

- [ ] Interactions avec le lieu, les occupants du lieu, et le coordinateur

**Comment by DewiBrunet** [comment]
et pour pas réinventer la roue, on peut largement s'inspirer de ce qu'on a écrit pour NextTech ;) 

[NextTech2018_Formulaire_FR-1_Pass Tech.pdf](https://github.com/openfab-lab/openfab/files/2146067/NextTech2018_Formulaire_FR-1_Pass.Tech.pdf)
[Rapport d'activité 2017_Syntonie.pdf](https://github.com/openfab-lab/openfab/files/2146068/Rapport.d.activite.2017_Syntonie.pdf)


<img src="https://user-images.githubusercontent.com/25649502/42047183-e23e93a0-7aff-11e8-9d8f-4f05ffe83a0d.jpg" alt="alt text" width="300" height="250">

**Comment by zuperninja** [comment]
Comme un boulet j'ai trop écris 

https://docs.google.com/document/d/1GsIdUH9eW6NXpo1lWrWZzuYv8FdiO1mh_LaNYB3JTxQ/edit#

Piocher dedans pour compléter votre partie :)

**Comment by Valonlisbeth** [comment]
![vue3d](https://user-images.githubusercontent.com/26233726/42105232-e30e5830-7bcf-11e8-995b-1a39b5ecc477.jpg)

**Comment by satblip** [comment]
Ola les amis, je viens bien lundi, donc je pourrais rusher avec vous si il manque quelque chose ;-) Vivement le 13juillet que j'ai bcp plus de temps pour tout cela :) 

Dans le descriptif de l'équipe je veut bien être mis comme animateur et accompagnateur aussi, le dev n'est pas vraiment ce que j'ai envie de faire principalement à L'openFab :D 

Des grosses bises !

**Comment by nicolasdb** [comment]
par mail!? 

![past](https://78.media.tumblr.com/dd54449211439505d887a87d570f0ff7/tumblr_inline_o8nngnJYkQ1r53amc_250.gif)

**Comment by nicolasdb** [comment]
J'ai créé une branche et un PR #228 pour centraliser les docs. 
Vous pouvez tjs bosser comme vous préférez (pour cette fois) mais j'apprend les bonnes pratiques et montre l'exemple. ;)

**Comment by DewiBrunet** [comment]
Voila la partie note organisationnelle (j'ai aussi mis sur la branche SAU).

[Note organisationnelle par.pdf](https://github.com/openfab-lab/openfab/files/2152014/Note.organisationnelle.par.pdf)

**Comment by Valonlisbeth** [comment]
Hahaaaaaaaaa GG @DewiBrunet ! I like it! (ça me fait penser que je dois mettre une photo plus lumineuse sur Linkedin!)

**Comment by nicolasdb** [comment]
bon ben c'est bien, je clos cette issue.
