### ISSUE TITLE
Corbeilles design et production

### ISSUE THREAD

**Issue by zuperninja** [openfab-lab/openfab#224]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*

## contexte

> Nous souhaiterions faire réaliser environ 200 corbeilles de fruits en bois pour notre service de livraison de fruits bio dans les entreprises.
> 
> Nous souhaiterions 3 types de corbeilles de fruits: 
> 
> Dimensions :
>  - Corbeille de 3kg : 8*20*30
>  - Corbeilles de 5kg : 8*27*36
>  - Corbeille de 7kg : 8*27*45
> -En bois belge dur huilé avec une huile écologique et alimentaire
> Pas d’utilisation de colle
> Pas trop ressemblant à la corbeille d’un de nos concurrents 
> Inscription du logo Fresho sur la corbeille bio soit via un cachet à brûler, soit via une gravure laser, soit via une petite plaquette en inox. Ou autre.
> As-tu besoin que ces corbeilles s'emboitent ? Non.
> 
> Doivent-elles être réutilisables ? Oui, elles doivent être solides.
> 
> 200 corbeilles de chaque capacité ? Environ 100 corbeilles de chaque capacité. Si il n’y a pas de différence de prix entre 80 et 100 corbeilles nous préférons en faire produire 80 et en refaire produire plus tard.
> 
> Ton budget est de combien en production et en design ? Le prix du design sera compris dans le prix de la corbeille.
> 
> De combien envisages tu le prix de fabrication d'une corbeille ?  Entre 10 et 30€ pour le design et la fabrication par corbeille.
> 
> As tu un budget pour le prototypage ? Non à toi de proposer un budget.
> 
> Seulement bois ou est-ce que tu es pour le mélange de matières ? Ca dépend du mélange de matières. Tu parles de bois et de quelques éléments en une autre matière ou plutôt d’une matière composite bois et autre matériaux? Pas d’aggloméré en tout cas.
> 
> C'est quoi ta timeline ? Dés que possible. Nous avons besoin de prototypes assez rapidement pour avoir le temps de les tester.
> Ces nouvelles corbeilles font partie du lancement des nouvelles corbeilles bio de Fresho. Nous lançons le nouveau site internet de Fresho en octobre. L’idéal est d’avoir les corbeilles avant pour pouvoir déjà lancer le nouveau produit auprès des clients existants et de lancer le nouveau produit auprès de nouveaux clients en octobre.

## objectif

Produire 240 corbeilles en bois en répondant au cahier des charges

## proposition

@Lisa-oraa en design avec @nicolasdb 
@DewiBrunet en production (avec quelqu'un d'autre ?)

## ressources

http://www.fresho.be/entreprise/corbeille.php
Me demander pour les mails

### rewards

Money money !

**Comment by DewiBrunet** [comment]
ok cool, merci Anne-Ca :)

rapide estimation budgétaire sur base d'un job similaire qu'on avait fait avec Nico en 2017 : https://github.com/openfab-lab/openfab/issues/139
- faudrait être dans une fourchette entre 2400€ et 7200€ (240u x 10 à 30€/u).
- si on estime à 50h le design  : 50h x 34€ = 1700€ en design
- si on estime 30min de fabrication par corbeille (ce qui est peu?): 240u x 30min = 120h x 34€ = 4080€ en production
- rajouter coût matériel + coût machine + forfait backoffice + prototypage

DONC a minima on sera autour de 6.000€ je pense pour un total de +/- 180h de boulot (= 1 mois temps plein).
![b70](https://user-images.githubusercontent.com/25649502/42042277-170b19e8-7af4-11e8-907f-a54ebefdefc9.gif)

Niveau planning, j'imagine juillet/août pour prototypage/design et validation du devis et septembre/octobre pour la production. Perso, ça m’intéresse, c'est un bon exercice et ça fait rentrer des sous :)  

@nicolasdb @lisa-oraa chaud? On se cale une aprem/matin semaine prochaine pour préparer un proto?

**Comment by nicolasdb** [comment]
yup, ne pas oublier la partie vernissage. ça prend un tps con. à faire avant assemblage du coup.

On en parlait rapidement hier avec anca. 
Je vois 2 pistes de base pour une prod efficace. C'est pas incroyable comme design mais ici, je pense à la faisabilité de prod, à nous de broder du joli dessus. Faut rester réaliste, du cintrage de latte, c'est compliqué et on a pas la place. 

### idée 1
- une base commune de coin triangulaire, comme dans les cagettes en bois, c'est de la longueur de bois, on coupe tout les 15cm (suivant dimension). ça saucissonne. 240x4 petites bouts. 

![image](https://user-images.githubusercontent.com/12049360/42083265-b1301c94-7b8a-11e8-89d3-2bc6da04b1cb.png)

1. Ensuite, un fond à tester sur notre cnc, en bois (à voir ce qu'on trouve de local) 
Avec le logo fresho dedans, = swag. (attention solidité)  
Ensuite, quand ça marche, on fait produire chez atelierCNC, zoupzoup.
2. on fait les contours, prédécoupé chez fournisseur en x rectangles suivant les 3 tailles. 
On grave ou cut logo sur les faces. 


### idée 2

Partir sur quelque chose de différent. Comme pour les bouteilles. L'avantage non demandé, c'est les poignées, plus simple pour déplacer et livrer chez le client.  (Mais plus difficile à superposer pour le transport général)

![image](https://user-images.githubusercontent.com/12049360/42083539-82537532-7b8b-11e8-8890-01d29acdf974.png)

- là aussi, le plus simple, c'est des découpes droites ou quelque chose qu'on peut automatiser en production. 
- Puis gabarit ici pour la gravure laser ou investir dans un cachet à bruler. ça peut valoir le coût.

![image](https://user-images.githubusercontent.com/12049360/42083696-ee937972-7b8b-11e8-8b15-4e2965025d21.png)


Faudra un gabarit pour les gravures, on enchaine la prod. 
Et si on reste simple mais de bon gout, on peut garder les coups assez bas. 

Pour le vernis, on peut normalement aussi utiliser un pistolet à peinture. (sur compresseur air)

![image](https://user-images.githubusercontent.com/12049360/42083796-2c92ac7a-7b8c-11e8-999a-27e9784d5f88.png)


Restera l'assemblage, on pourrait investir dans une clouteuse pneumatique sur le compresseur air aussi.
 
![image](https://user-images.githubusercontent.com/12049360/42083225-8ced55cc-7b8a-11e8-9100-b6216124e51b.png)
 
Test de 3 protos, 3 tailles. 
Solidé, on les charges avec 25/30% de poids supplémentaires. Pour le "y en a un peu plus, j'le met quand même?"
On pourrait même charger le poid du panier supérieur. 5kg dans le 3kg, 7 dans le 5 et 10 dans le 7. Un truc du genre. 

Plan optimisé de production avec les fournisseurs. 
Plus le tps de vernir et séchage. 
Et assemblage.

**Comment by Lisa-oraa** [comment]
J'aime beaucoup l'idée et ça à l'aire intéressant de travailler sur un produit ou le client pose un certain nombre de contraintes. 
Si vous voulez je commence à travailler sur les formes, je fait une banque d'idées pour avoir un support sur lequel on pourrait discuter la semaine prochaine! 

Cela nous permettrais d'activé le mode "maquettes" et "prototype" asses rapidement! 

Il faut voir ce qui est le plus intéressant en termes de prix et d'esthétique si on pratique par assemblages de bois ( ou il y en à un nombres infinie et qui permet un rendu final très jolie) ou si l'on reste sur la phase facile d'un assemblage par clous ou vis?

Mais c'est plustôt un max fun! :')

**Comment by nicolasdb** [comment]
**note:** 
Un truc qu'on a jamais précisé. Pour des gros jobs comme ça, il faut demander un accompte!! d'au moins le coût des investissements matériaux, machines.

**Comment by DewiBrunet** [comment]
Cool si on peut avoir un proto semaine prochaine :) 

idée 1 j'ai peur que ça ressemble trop à leur concurrent (ou faudra bidouiller^^)

**Comment by Lisa-oraa** [comment]
Alors les petits amis voila, je vous envoie les séduisante photo des 2 prototypes qui ont été choisis. 
L'un comme l'autre sont réalisables en séris, il faut juste compter un peut plus de temps pour la corbeille avec des tige en bois, car il faut raboter les tiges qui ressortes de chaque cotés du proto.

Pour le client je vois bien un petit texte qui résume la situation: 

Bonjour, nous vous proposons deux type de boîtes pour votre demande.
Voici deux prototype formelle pour avoir votre avis sur la forme et sur ce que vous souhaiterais modifier ou améliorer. 

La première boite est asses simple à fabriquer. Elle demande une prédécoupée et un assemblage classique. Ce qui la rend séduisante sont ses ajours délicats et originaux. Ils permettent de pouvoir voir la couleurs des fruits que contient la cagette, mais permet de créer des poignets pour faciliter le transport de ces caisses. Elle est simple à fabriquer, à transporter et à nettoyer.

Pour la seconde boîte, son design est plus originale. Composée d'une plaque au font et de deux côtés liée à l'aide de barre en bois, cette boîte véhicule l'esprit de la ferme. Comme dans un berceau, les fruits sont offert à la vue de tous grâce à la légèreté que procure les simples barres de bois. Pratique à transporter grâce à ses deux anses sur les cotés, elle reste empilable et facilement stockable. Cette Boîte est plus originale et permet de créer une identité visuelle unique. 
Sa fabrication est toute fois un peut plus longue que l'autre.

Voici les deux pistes de recherches que nous avons à vous offrir pour rester dans votre demande qualité-prix.  Les photos que nous vous joignons sont des photos des prototypes des plus petites boîtes. 


![36630715_987220058119302_6848178568669691904_n](https://user-images.githubusercontent.com/39944297/42334019-998d5d58-807c-11e8-990b-005b018e2f65.jpg)
![36639427_987219978119310_6334174466280521728_n 1](https://user-images.githubusercontent.com/39944297/42334021-99afabb0-807c-11e8-89e7-db237d71410a.jpg)
![36636728_987220181452623_5509982487129882624_n 1](https://user-images.githubusercontent.com/39944297/42334022-99ca8ade-807c-11e8-8f7c-3a94456d1dba.jpg)
![36641599_987220078119300_2458561081207947264_n](https://user-images.githubusercontent.com/39944297/42334023-99e52a60-807c-11e8-8556-12cd46c12dc5.jpg)

Voilllllaa je vous fille les photos que j'ai fait et si vous avez besoins de dessins ou quoi je peut vous les passer aussi!!! :') voillllaaaa

**Comment by Lisa-oraa** [comment]
Salut les crapules, alors je vous met ici même en bas les photos trafiquer pour faire genre y'a une gravure laser 🥇 
y'en à plusieurs photos donc vous choisissez celle qui vous convient! 👍 

![mise en situation caisse en bois vide gravure 3](https://user-images.githubusercontent.com/39944297/42372804-88cebc54-8113-11e8-991f-969e26e735b4.jpg)
![mise en situation 4](https://user-images.githubusercontent.com/39944297/42372805-88ee550a-8113-11e8-8a14-672b97b13b92.jpg)
![mise en situation caisse en bois gravure fresho 1](https://user-images.githubusercontent.com/39944297/42372806-89083952-8113-11e8-8def-0482422d7d5f.jpg)
![mise en situation caisse en bois gravure fresho 2](https://user-images.githubusercontent.com/39944297/42372807-89263f4c-8113-11e8-9e37-4f8f7a2cba97.jpg)

**Comment by Lisa-oraa** [comment]
https://giphy.com/gifs/rjkJD1v80CjYs

on y 'es presque! :')

**Comment by zuperninja** [comment]
Location de l'atelier CNC chez cityfab1 : pour les 3 petites CNC = 12€/jour par personne. Booker en avance dès qu'on sait les dates. Maité doit être présente. On peut assembler là bas, y a de la place. Ils sont fermés la semaine du 15aout.



Produit | Nb produit | Item | en mm | qté | Largeur | Longueur | En m² | Total/ boite | Total prod
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Boite small | 80 | fond | 200 x 300 | 1 | 200 | 300 | 0,06 m² | 0,14 m² | 11,20 m²
  |   | côté large | 80 x 200 | 2 | 80 | 200 | 0,03 m² |   |  
  |   | côté longueur | 80 x 300 | 2 | 80 | 300 | 0,05 m² |   |  
Boite medium | 80 | fond | 270 x 360 | 1 | 270 | 360 | 0,10 m² | 0,20 m² | 15,84 m²
  |   | côté large | 80 x 270 | 2 | 80 | 270 | 0,04 m² |   |  
  |   | côté longueur | 80 x 360 | 2 | 80 | 360 | 0,06 m² |   |  
Boite large | 80 | fond | 270 x 450 | 1 | 270 | 450 | 0,12 m² | 0,24 m² | 18,94 m²
  |   | côté large | 80 x 450 | 2 | 80 | 450 | 0,07 m² |   |  
  |   | côté longueur | 80 x 270 | 2 | 80 | 270 | 0,04 m² |   |  
  |   |   |   |   |   |   |   | Total = | 45,98 m²

**Comment by Lisa-oraa** [comment]
voilaaa la dernière!!!! :')

![mise en situation deux maquettes](https://user-images.githubusercontent.com/39944297/42373497-57a0c6a2-8115-11e8-932a-ce183ca06ba1.jpg)

https://giphy.com/gifs/rjkJD1v80CjYs

**Comment by zuperninja** [comment]
Voilà c'est envoyé !


![mail_corbeille_fresho](https://user-images.githubusercontent.com/25099826/42378286-1321737a-8127-11e8-93a0-f7e439960caa.png)

**Comment by zuperninja** [comment]
Suivi job ici : https://github.com/orgs/openfab-lab/teams/team-job/discussions/1
