### ISSUE TITLE
Mayor Dewi

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#227]
juste du lol. C'est samedi.
ça fait longtps que j'y pense. 👍  hihihihi

![image](https://user-images.githubusercontent.com/12049360/42124608-31109d68-7c66-11e8-925d-cf0fc30eb468.png)

![image](https://user-images.githubusercontent.com/12049360/42124616-581c4c18-7c66-11e8-8bdd-4363ec6bcc6a.png)

[![IMAGE ALT TEXT](http://img.youtube.com/vi/dunxpN_yVvA/0.jpg)](http://www.youtube.com/watch?v=dunxpN_yVvA "Video Title")
https://www.youtube.com/watch?v=dunxpN_yVvA

**Comment by nicolasdb** [comment]
à voir,
- Game Anatomy - Celeste, une nouvelle façon de faire du platformer ?
https://www.youtube.com/watch?v=hYGqiHl5YrA

- Rebecca Sugar & Steven Universe | Apprendre à grandir
https://www.youtube.com/watch?v=gTc71r5-pMU

**Comment by DewiBrunet** [comment]
haha, génial! ça à l'air cool cette série faut que je mate^^
