### ISSUE TITLE
Contestation facture - job découpe laser

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#229]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Monsieur Antoine, s'est présenté un milieu d'après midi, avec un job de découpe laser en urgence pour le lendemain.  Navid était présent et s'est occupé de cette personne.

Découpe sur base de fichier, 7 pochettes pour disque vinyle pré-imprimée, un design d'étudiant.  
Navid a passé 1.5h pour préparer, calibrer et découper les 7 pochettes. Les papiers préimprimés ont été fournis, pas d'exemplaire de test. 

**Resultat:** (pas de photo, dommage) 
Découpe extérieur ok, selon les traits de coupe imprimés mais une typo, à découper aussi à l'intérieur de la forme, est non synchro avec l'imprimé. 
Le centre et la taille est ok mais il y a un décalage vers les extrémités. 

Aujourd'hui, le père conteste la facture à cause de ce décalage. (B038)

## objectif
Créer un précédent, une jurys-prudence... pour simplifier la résolution de ces cas. 

## proposition
- soit en amont, en refusant les urgences OU en ayant un bon de commande avec acceptation de non garantie de résultat. 
- soit en aval, en préparant une routine de gestion de réclamation. 

## Resultats

- [ ] Une guideline clair pour les membres metauser et au delà. 
- [ ] Un bon de commande avec acceptation des conditions.
- [ ] Un formulaire C.O.P à faire remplir aux contestataires. 
S'il ne sont pas content, c'est à eux de bosser. 

### rewards
\+ de tranquillité

**Comment by zuperninja** [comment]
Il demande quoi ? Juste de pas payer toute la facture ? Sinon on lui fait 20% de remise et on récupère comme ça le temps machine au moins.

**Comment by nicolasdb** [comment]
Et attention, il est important de rester poli et courtoit tout au long. C'est de la communication non violente. Le gars est très correct aussi. 

Voilà l'échange actuel;
> Bonjour ,
Je reviens vers vous sur ce projet .
Je tiens à remercier Navid pour son écoute mais je vais devoir contester la facture étant donné le résultat.
Pourriez vous me téléphoner pour discuter de cela.
En attendant je vous souhaite une belle fin de journée 

---

>Bonjour,
C'est Nicolas, on s'est eu au téléphone la dernière fois.
Désolé d'apprendre cette contestation. 
Dans l'esprit de partage, d'opensoure et de transparence, nous décrivons les expériences acquises pour que tout le monde en bénéficie. 
Nous avons une politique de documentation des problèmes similaire à la documentation des jobs en interne qui passe par "contexte, objectif, proposition".
Donc,
Pour garder une trace des discussions, nous évitons le téléphone.
Je te propose de me renvoyer une description du problème selon:
> 1. le contexte
> 2. la description de la contestation
> 3. une proposition de résolution.
> Suite à ça, la proposition sera acceptée ou une adaptation sera proposée. 

---

> Je reprends vos termes :
> 1. le contexte :::: demande de travail pour un examen de fin d’année en infographie
> 2. la description de la contestation :::: le travail de découpe laser était décalais par rapport à l’impression === visuel qui vibré. Impossible de le rendre à l’école .
> 3. une proposition de résolution ::: aucune proposition de votre part pour résoudre le problème .Nous avons acheté du matériel chez Schleiper afin de bomber la surface et de rendre le défaut invisible .
> Que proposez-vous dans ce genre de situation ????
> En attendant de vous lire je vous souhaite une belle fin de soirée 
>

**Comment by satblip** [comment]
Je pense deux choses : 

1) Typiquement ce genre de discussions doit être privée et pas publique (tu viens  de citer A365, google indexe ça ;) )

2) Avoir un bon de commande avec acceptation de non garantie de résultat me semble une excellente idée !

**Comment by nicolasdb** [comment]
ok, donc pour référence futur, la prochaine fois sera sur slack. :+1: 

ha oui, et donc, faudrait plus de détails de Navid (documentation!)

Une réduction, je sais pas, oui, si on s'écrase. 
Mais ça m'ennuie quand même, 
- Navid a fait du bon boulot, 
- en urgence, en fin de journée (pression)
- sans droit à l'erreur, 7 print à découper, 7 print fournis.
- si la découpe extérieur correspond mais pas la typo, c'est que la calibration de Navid était bonne. 
- "bug/erreur" probable de fichier, entre le print papier (effectué ailleurs) et le laser. 
- Ou la typo n'était pas vectorisée... donc remplacement automatique probable par inkscape avec la typo la plus proche. 
- le client a reconnu au téléphone que s'il n'y avait pas eu le lettrage imprimé, ça n'aurai pas posé de problème. = erreur de préparation du workflow qui se serai prévue hors urgence.

On en discutait avec Xavier ce week-end et il conseillait lui de carrément lui rajouter 20% parce qu'il nous fait perdre du tps, qu'on aurai pu le laisser se débrouiller et qu'on est pas un magasin.

**Comment by nicolasdb** [comment]
Xavier suggérait aussi de faire comme avec le reste, on est opensource, on documente, il ne paye pas ou si ça se passe mal, on le documente et comme dans les réseaux sociaux, il y a un avis négatif qui est émis et qui avertis la communauté.

**Comment by satblip** [comment]
Hahaha si tu arrive à rajouter 20% et qu'il paie tu gagnes le badge "je t'offre un sandwich", moi je trouve que la proposition de @zuperninja est bonne, on diminue de 20% comme ça on se fait pas chier. Ensuite pour les prochains, condition de vente au recto du bon de commande et tchao bonsoir ;)

**Comment by nicolasdb** [comment]
:) chez gedebois, ils avaient un jour fait la remarque à un mec qui cherchait à négocier au comptoir pour sa commande. 
> \- tu veux négocier? ok, c'est 10% en plus. 
> \- ok, je la ferme ^^' 

'mon fait marré. :laughing:

**Comment by satblip** [comment]
Hahaha ces bon vieux gedebois 😄 Ils m'avait fait une ristourne à l'époque, je devais leur sembler sympathique 😄

**Comment by satblip** [comment]
Ou alors j'ai payé 10% de plus sans m'en rendre compte ? 🤔

**Comment by nicolasdb** [comment]
ok, nouvel épisode, rapidement. 

Il n'est pas satisfait avec ma proposition, s'il y avait du texte imprimé, à nous de faire avec et il demande 50% de réduction. 

Je lui ai rappellé qu'on était un collectif et que je n'avais pas la liberté de donner des réductions selon mon bon plaisir. Je lui propose le tarif membre, il ne paye donc pas le backoffice ce qui ne réduit pas non plus ce que Navid recevra. (un truc du genre parce qu'il continue de remercier malgré tout Navid pour son temps)

J'ai édité la facture, lui ai joint "en espérant que ce compromis le satisferai" 
Dans le cas contraire, je devrai faire appel à la communauté pour obtenir une décision du collectif. 

Dans ce cas, je pose la question sur le groupe FB, bim. non?

**Comment by nicolasdb** [comment]
Plus de contact avec le mec. 
Mais je n'ai rien vu arriver sur le compte, de mémoire. 

à surveiller.

**Comment by nicolasdb** [comment]
Issue moved to [openfab-lab/devis-et-facturation #10](https://github.com/openfab-lab/devis-et-facturation/issues/10) via [**ZenHub**](https://www.zenhub.com/)
