### ISSUE TITLE
Meetup

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#23]
La compta se rappelle à moi. 
Je viens de me rappeler en voyant les extraits mastercard que c'est Openfab qui paye le groupe meetup, 
pas grand chose mais quand même. 27,29€ pour 6 mois je pense. 
Actuellement, c'est @dsmrs qui est le "propriétaire" du groupe parce que c'est lui qui la créé. 

Donc 2 questions pour le groupe @openfab-lab/gami 
- Comment changer de propriétaire, parce que c'est chiant pour obtenir les justificatifs de paiement, seul Dorian a accès. 
- Est-ce qu'on ne ferai pas un évènement exceptionnel tout les 6 mois avec vente de bières pour financer le groupe?

**Comment by softrevolter** [comment]
On relance un Braincandy en aout? et on met un peu plus de promo sur les boissons?

**Comment by nicolasdb** [comment]
Chaud. Ouais. 

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Ginsburg** [comment]
Du coup, ce groupe meetup est inter-fablab ? Il y a quelques règles ou on peut le spammer du moindre événement ? 

Comment peut-on échanger avec les autres Fab Managers du groupe ? Je pensais notamment aux journées portes ouvertes qui concernent pas mal de monde, ça pourrait être bien d'avoir un événement commun.

**Comment by nicolasdb** [comment]
hier, il a été dit "et si on faisait un braincandy sur le toolporn?" 
Mmmm, ok, ça devait être moi.

exemple:
https://vimeo.com/30698649
https://vimeo.com/28408829
https://vimeo.com/56287630

le tool porn, c'est déjà plus de qualité vimeo. c'est pas sur youtube.

allez et un dernier pour la route.
https://vimeo.com/48864768

**Comment by nicolasdb** [comment]
et ma préférée pour la fin du brain candy
https://vimeo.com/74965870

**Comment by softrevolter** [comment]
nice one, ça serra bien pour le prochain oui :)

**Comment by nicolasdb** [comment]
@dsmrs 
Salut, 
Je pense qu'on va bientôt arrivé à la fin des 6 mois d'abo et qu'on va repayer automatiquement. 
Est-ce que tu pourrais voir comment transférer l'admin à un compte Openfab? On galère à chaque fois pour obtenir les justificatifs comptable, il faut régler cette histoire.
bisous

**Comment by dsmrs** [comment]
@nicolasdb je viens d'annuler le paiement, normalement j'ai envoyé un email automatique a tous les organisateur pour reprendre le paiement (faut le faire avant le 28 mai 2018 😉 )

**Comment by nicolasdb** [comment]
ha ouais, ok, c'donc comme ça que ça marche. :)

**Comment by nicolasdb** [comment]
voilà, c'est transféré, payé et c'est repartis pour 6 mois. 
par contre, ça augmenter... 
Faut qu'on le rentabilise ce brol.

Je lance un braincandy de l'espace ce week-end. 
qui ça branche?
