### ISSUE TITLE
Approvisionnement matières

### ISSUE THREAD

**Issue by arnaudwiertz** [openfab-lab/openfab#230]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Tout projet de fabrication qui requiert du consommable ou des produits à acheter ou trouver à l'extérieur

## objectif
Partager des bons plans, adresses, conseils et retours d'expérience sur où et comment trouver du bon matériel de base

## proposition
1. Un annuaire évolutif et plus ou moins informel
2. Une liste à jour des chutes qu'on offre à la communauté
3. Une liste de courses des consommables nécessaires pour OpenFab (des fois que quelqu'un aurait prévu une commande perso qui va dans le même sens)

## Resultats
(exemple:)
**Item**: Polystyrène en feuille pour thermoformage
**Fournisseur**: Schleiper chée. de Charleroi
**Détails du produit**: styrène blanc, plusieurs épaisseurs disponibles de 0.25mm à 1.5mm, un peu plus étroit que A4.
**Prix**: variable selon l'épaisseur, environ 2€ la feuille
**Utilisation et expérience**: Thermoformage avec chauffage à 150°C dans mon four de cuisine, très bonne mise en œuvre pour peu que la température soit uniforme. Attention au design du modèle: l'épaisseur du résultat varie selon la sévérité de la mise en forme (pentes raides, angles aigus,...). On peut en discuter, et la table d'aspiration est à disposition sur demande.

**Comment by satblip** [comment]
Ok peut aussi faire un dossier par "matière générale" : bois, plastique, metal, etc... Ca limiterait la longueur du fichier tout en ne mettant pas en oeuvre une db, etc...

**Comment by nicolasdb** [comment]
intéressant ce post sur fablabs.io

http://discuss.fablabs.io/t/non-chemical-plywood-in-benelux-area/8403

**Comment by nicolasdb** [comment]
ok, donc
todolist: mettre en évidence où ce retrouve cette ressource? 

Où est-ce qu'on pourrait indiqué cette liste ?
Dans petit cadre au bureau? avec son QRcode et son adresse html? 

![image](https://user-images.githubusercontent.com/12049360/44533223-551d9300-a6f5-11e8-962b-0034baa43809.png)

**Comment by nicolasdb** [comment]
Une nouvelle issue est là pour un jour déplacer ça au bon endroit. 
https://github.com/openfab-lab/rtfm/issues/11

![image](https://user-images.githubusercontent.com/12049360/57315783-98d5f280-70f4-11e9-958c-5c025b1334c9.png)
