### ISSUE TITLE
Hardware needs your wrench, man!

### ISSUE THREAD

**Issue by satblip** [openfab-lab/openfab#232]
## contexte

Few machines need maintenance/fix/love

Idea is to list them here so we can dedicate some time to it when we come.

This issue is dedicated to machine maintenance.

Maintenance for each machine has to be documented.

## objectif

![fix it](https://media.giphy.com/media/4f1B6N2Tl302I/giphy.gif)

## proposition

We do a list the gear that need man work (do not hesitate to edit this post to update the list)

- [ ] 3D drag

    Actually in pieces, what do we do? A plotter? Fixing it to 3d print again?

- [ ] Extruder on Anet

    Filament constantly gets stuck in the cold zone of the extruder.

- [ ] Wifi and network
 
    Has been started, but wires has to be properly installed, and the wifi AP is getting old, let's change it.

## ressources

-> @satblip will bring two wifi access points (one for admin and staff, one for members and visitors)

### rewards

TBD

**Comment by nicolasdb** [comment]
Bonus level: 
- **3Dprinter**, in general: 
Check the safety temp behavior and reupload new firmware with safety activated in config.h
During uncloging, the heat cartridge felt off (bad screwing) and I watched the cartridge going RED in a couple of dozen seconds, without any reaction of the board.  I, of course, turn the power supply off.
Which should trigger the safety if temp doesn't follow the heating command. 

{
if (not);
then (halt and catch fire);
delai 100;
serial print ("surprise motherfucker");
}

![image](https://user-images.githubusercontent.com/12049360/44359696-ed7b0400-a4b8-11e8-9069-fa491d4f09a6.png)

**Comment by satblip** [comment]
@nicolasdb are they marlin based? Because indeed the new versions include a lot of security feature. We can also control the fan of the extruder from the software and make it switched off if under 50° (my setting here)

**Comment by nicolasdb** [comment]
Yup, anyway depending on the board we can upload a fresh marlin, or repetier or something fresh. Boards are open hardware based, we can do what we want. :)

**Comment by satblip** [comment]
I like that!

**Comment by nicolasdb** [comment]
http://www.latelierdufrdd.fr/2017/12/13/installation-bltouch-sur-anet-e10/

Et ceci 
http://www.latelierdufrdd.fr/2017/12/12/installation-marlin-sur-anet-e10/

thanks Internet.

**Comment by DewiBrunet** [comment]
good idea!
we could also think of "ID cards" for each machine that we could print and put irl to see if there is any current problem? (and also details like : name, age, upgrades, where are the tools/materials for repair...)

**Comment by satblip** [comment]
Anet A6 has been cleaned, cable managed and firmware updated with the security patches, less chances it will burn now 😄 

Our firmware for the Anet A6 is located here : https://github.com/openfab-lab/Marlin/tree/anet-a6/OPENFAB-BUILDS

This will be branch for each printer on this repo.

**Comment by satblip** [comment]
Good hardware is the key

![image](https://user-images.githubusercontent.com/1811109/44650107-01a59080-a9e6-11e8-978c-b03a7f84a5a0.png)

**Comment by nicolasdb** [comment]
Yeah, 
On vient de recevoir le nouvel extrudeur E3D chinois. 

On le monte sur quelles machines?

**Comment by satblip** [comment]
On peut retaper la geektech et l'installer dessus ?

**Comment by satblip** [comment]
@openfab-lab/team-gestion @openfab-lab/superuser Alors j'ai commencé l'update de sécurité sur l'anet E10, mais je n'ai pas eu le temps de finir, alors elle ne sera pas opérationnelle d'ici mercredi prochain. (j'ai aussi eu un Z bien bien trop bas dans mes tests, et je n'étais pas attentif, mea-culpa. Bref j'ai recommandé des build plates stickers ;))

**Comment by satblip** [comment]
J'ai reçu la build plate ;)
![image](https://user-images.githubusercontent.com/1811109/47641535-a1a6a400-db66-11e8-9991-fcf1b1dfbaa6.png)

**Comment by nicolasdb** [comment]
2018, geez. Sujet clos et en même temps, jamais finit. 

Merci à tout ceux qui ont aidé à ce moment là. :)
