### ISSUE TITLE
infobésité. les notifications me tuent.

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#234]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*

![image](https://user-images.githubusercontent.com/12049360/44554591-d6931680-a731-11e8-8d92-c5a260ebba25.png)

Je prend très au sérieux le problème d'infobésité dont je suis conscient d'être atteint. 
https://futurstalents.com/talents-futur/anticipation/les-9-dysfonctions-liees-a-linfobesite/

haaaaaaaaa, et je reviens relax de tournevie et voilà.
200 nouveaux mails, j'aime pas les mails.

![image](https://user-images.githubusercontent.com/12049360/44552745-844ef700-a72b-11e8-94fe-77130729cf70.png)
![image](https://user-images.githubusercontent.com/12049360/44552760-8c0e9b80-a72b-11e8-8764-8cc099e5b243.png)

alors du coup, est-ce que c'est juste la même chose que je retrouve ici **ET** dans slack **ET** dans les notifications github? si oui, alors je quitte gmail....
Fu** that sh**

---

Je respire et regarde et oui, c'est bien 3x plus de notifications que nécessaire.
![gif](https://media.giphy.com/media/2jlDkaipGfgGc/giphy.gif)

Sur slack, je reçois les liens vers l'identique, mais c'est classé (uniquement pour team-job) sauf qu'il n'y a pas de détails ou de titres. Pas encore de team fabmob donc les notifications arrivent par mail. 

![captureslack](https://user-images.githubusercontent.com/12049360/44553841-24f2e600-a72f-11e8-8204-f37cafbeb29b.JPG)

Il faut donc creuser pour voir de quoi il s'agit. -nul-
Par contre. 
Github. :octocat: 
C'est bien classé par repository. C'est beau, et c'est pour moi bcp moins stressant quand c'est trié comme ça. :) 

![capturegithub](https://user-images.githubusercontent.com/12049360/44553935-77340700-a72f-11e8-9b1d-47f68f9b2492.JPG)

Mais ça reste triple notifications pour tout le monde par defaut. 
_Désolé, ça doit donc être pareil quand j'écris des trucs. Et je dois écrire pas mal, non? 
C'est pour ça que vous répondez pas, hein?_

J'ai du coup, désactivé mes notifications github par mail. _Slack c'était déjà fait._ 
Je peux donc me dire que si je tiens à l'oeil github, je devrai m'en sortir. _Avec un gif ou l'autre sur slack et ce sera cool._ 
Il resterai bien un truc à faire pour savoir si c'est des msg généraux ou si c'est à destination de quelques personnes spécifiquement. Comme quand on utilise les @ 

le problème c'est que par défaut c'est tout ou rien 
![image](https://user-images.githubusercontent.com/12049360/44554263-941d0a00-a730-11e8-81fc-240b3a22e07c.png)

je sais que ça va s'améliorer mais pour l'instant, je ne suis pas tout à fait satisfait de la routine de notification. 
Qu'en pensez vous? 
 Des idées pour améliorer ça aussi ou en fait, ça vous dérange pas?

**Comment by zuperninja** [comment]
J'ai coupé les notifications bureau et gsm comme ça je suis tranquille.
J'ai des petits dossiers dans gmail avec des filtres pour savoir si ça vient de github ou slack. 

Pour pas me perdre je ne lis pas tout à la fois. Si je fais du suivi client, je check tout un client et j'actualise le kanban.
Si y a juste besoin de mon avis, je fais ça en fin de journée.
Si y a un projet qu'il faut suivre je renvoie à la bonne personne. 
J'utilise en plus des petits tags pour mes boites mails voir : https://github.com/zuperninja/WIP/blob/master/OpenFab/Germaine/nomenclature.md
Si je vois qu'un sujet renvoie à un autre sujet je mets le lien

Je trouve qu'on a bcp de notifications pareil mais pas assez d'organisation. Je pense que ça peut être bien d'avoir des Kanban pour le suivi client (déjà fait), le suivi membre (pour le moment c'est une feuille de papier sur mon bureau) et le suivi facturation. 
Je continue de tester dans la team job l'organisation, et dès que ça me satisfait je copie le modèle.

**Comment by nicolasdb** [comment]
ouais, j'aime bien ton approche Louis. 

Même si j'essaye de faire comme Anca dit, mais c'est bcp plus difficile 😿 
Va me falloir un coatch organisation. J'y arrive pas tout seul. 

J'avais affiché le GTD devant moi pour essayer de m'y tenir.
![gtd](https://user-images.githubusercontent.com/12049360/44571919-9445f580-a782-11e8-9005-61bfc0b0c2de.jpg)

Résultat, j'ai changé de place. 
_C'est pas ma faute, on a réorganisé le bureau._


Mais, j'aime bien venir consulter les notifications sur github. 
Comme ça, c'est effectivement pas intrusif et j'y suis souvent donc je peux rester focus.

**Comment by nicolasdb** [comment]
ok, that's cool. 
beaucoup plus calme niveau notification par mail. 
Top. ça marche.  :)
