### ISSUE TITLE
Comptabilité au OpenFab

### ISSUE THREAD

**Issue by milenasonneveld** [openfab-lab/openfab#236]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Pour qui Milena puisse aider à la comptabilité de Openfab, surtout pour le projet du Fablab mobile. En long terme on pourrait déléguer la comptabilité. 
## objectif
Le trésorier sera toujours la personne qui vérifie la comptabilité tous les 3 mois. Dans les facturations du jour en jour on peut déléguer les taches de facturation de dépenses, de facturation à des clients et de validation des notes de frais. Pour cela il faut être rigoureux et ne pas oublier des étapes.
## proposition
On décrit ici le flow de la facturation et des notes de frais pour le fonctionnement de OpenFab.
*Étape 1 - Préparation*
- [ ] On est level 3
- [ ] On se laisse invité au Google Drive
- [ ] Se connecter au OpenfabNAS (voir aussi https://github.com/openfab-lab/toolsDocs/blob/master/Informatics/Network/LANdiscovery.md)
- [ ] On fait un premier facture et note de frais avec le trésorier

*Étape 2 - Faire une facture*
- [ ] Dans Compta Caisse\2018 Vérifier le denier numéro de facture.
- [ ] Dans Compta Caisse\00 Model Facture OF-B0 suivre le flow indiqué.
- [ ] Si on facture à un nouveau client, introduire le client dans le fichier Compta Caisse\Client.
- [ ] Si tout est correct, créer une copie du document dans le dossier Compta Caisse\2018. 
- [ ] Dans le tab client, autoriser l'accès. Renommer le dossier avec le numéro de facture et nom du client.
- [ ] Imprimer en pdf (cellules sélectionnées).

*Étape 3 - Partager la facture*
- [ ] Ajouter la facture au OpenfabNAS\000WORK\2 gouvernance\Comptabilité\Facture Out\2018 - Factures clients
- [ ] Envoyer la facture au client avec le compte facturation@openfab.be avec le Message client.

*Étape 3 - Valider une note de frais*
à complèter

 ## ressources

**Comment by nicolasdb** [comment]
@zuperninja t'en pense quoi?

J'ai ajouté un flowchart aussi sur 
https://github.com/openfab-lab/devis-et-facturation/blob/master/accountingFlow.xml

Qu'on complétera la prochaine fois pour les notes de frais et petit à petit le suivit compta des factures.

**Comment by nicolasdb** [comment]
![accountingflow](https://user-images.githubusercontent.com/12049360/44617842-0abe2280-a86b-11e8-9080-196bf6cce544.jpg)

**note:** la copie dans le dossier 2018 AVANT d'imprimer est une astuce chronologique (de toutes façons faut le faire)
En créant une copie du modèle, Drive demande où et le nom, c'est l'occasion de renommer correctement la facture. 
`
ATTENTION au nom client. L'autorisation d'accès à la feuille client ne suis pas la copie. Faut juste cliquer authorisé et zoup, le nom du client réapparait sur la facture. Si qqun sait comment fixer ça, welcome.`
Lorsqu'on imprime en pdf, il n'y pas d'étape où renommer mais le nom du document est utilisé et directement téléchargé. 
On évite de devoir renommer le pdf après téléchargement. _Quand on doit le faire 40fois, ça fait plaisir._
Puis bien le ranger sur le NAS.

**Comment by zuperninja** [comment]
https://github.com/zuperninja/WIP/blob/master/OpenFab/Germaine/comptabilite.md

**Comment by zuperninja** [comment]
https://github.com/openfab-lab/devis-et-facturation

**Comment by nicolasdb** [comment]
Issue moved to [openfab-lab/devis-et-facturation #2](https://github.com/openfab-lab/devis-et-facturation/issues/2) via [**ZenHub**](https://www.zenhub.com/)
