### ISSUE TITLE
Retour de la convention de guilde

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#239]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
- InfiniFab, julien @Jorgininho
Aimerai développer l'aspect mobile/volant du fablab à l'internationnal (FR/BE)
Au travers de son catalogue et des workshops qu'il pourrait animer à Openfab, selon la demande. 
Sorte de InfiniFab Tour in EU. 

- beSproutLab @Valonlisbeth 
presque pareil mais sur la région BXL. 

- Velom2 @milenasonneveld 
Asso membre d'Openfab. Spécialisé VéloCargo et énergie. (+ partenaire Fabmob)

- Macocoi @Anou92 
Asso membre potentiel d'Openfab. Spécialisé textile. 

## objectif
Trouver une formule adaptée pour chaque type d'accès, partenariat. 
L'idée de Guilde revient. 

## proposition
- Un point de départ est le passport maker pour accéder à différent fablab. Les gens sont inscrits dans leur fablab d'origine, lui paye une cotisation et c'est un deal entre le fablab "host" et le "guest" 
- Second point, la proposition de gestion pour asbl ou entreprise discuté avec @satblip 
L'achat de code prépayé pour l'inscription de xPersonnes à Openfab. Avec l'association des membres à un compte client unique; blablabla. à mieux décrire.

**Comment by nicolasdb** [comment]
ok, donc... 
L'idée ici est que nous alimentions d'idées, de nos besoins et comment est-ce  qu'on pourrait répondre à ça de manière à ce que tout fasse sens et qu'on s'y retrouve tous.

**Comment by Valonlisbeth** [comment]
bon bon, détails de la convention, si j'ai bien compris : 
- avec 125 euro/ mois , on a doit à avoir notre petit bureau et accès full time au lieu et aux machines? Participation aux appels à projets en temps que partenaire etc etc!
question : et si je dois utiliser les machines pour faire le travail d'un client, est-ce que je paye en plus? 
Comment ça marche niveau propriété intellectuelle : dois je mettre le logo d'OpenFab aussi?
Je pense à des idées de projets à faire en collaboration : genre les deux logos etc qui pourraient être moins "chers" si on doit payer pour l'utilisation des machines en plus
Et les projets only B.SproutLab bah on paye full price. ça semble correct?

**Comment by nicolasdb** [comment]
Ce que propose @satblip c'est : 
- l'accès à 10€ l'heure, la première est payante, les suivantes sont offertes. 
OU
- l'accès par membership à 50€/mois sans desk, 125€/mois avec desk. 

Plus supplément sur consommation formations, matériaux, tps machines, boissons.

Mais c'est pour le niveau 1, si tu t'en fou de t'impliquer dans la communauté. 
---

Si tu t'implique, 
Les deals sont au niveaux 3. _Le niveau 2 est là pour l'onboarding._
Avec accès par membership à 35€/mois. 
c'est à partir de là qu'on peut négocier sur de l'espace partagé ou un desk en échange de workshop ou d'activités. le niveau 3 accède aussi aux teams et donc aux jobs et donc à des crrr qui peuvent compenser le coût d'un desk fix et d'usage machine, matériaux, boissons. 

Pour le tps machine pour job client. On en parlait la dernière fois. 
2 cas de figures. 
1. job pour un client **sans passer** par openfab. Donc pas de backoffice, pas gestion par openfab. Mais tarif sur le tps machine 40€/h and no question asked. 
2. job pour un client **passant** par openfab.  Gestion par la teamJob, devis et job selon les conditions de la team, tps machine à charge du client et rémunération sur base actuelle de 34€/h. (+ reward loot/XP) 
+ la griffe + job mis en vitrine sur le site OF.
