### ISSUE TITLE
Résidence/atelier Montréal

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#240]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
On a eu la visite de Camille Montuelle‎ de Perte de Signal (http://perte-de-signal.org/) aujourd'hui. Elle a eu vent de notre dynamisme :) 

Basé à Montréal il développe entre autre un festival d'art numérique "KidsLab" où des artistes sont invités pour faire des ateliers pour des nenfants autour du numérique.

## objectif
Créer des partenariats à l'international
Partager nos bonnes pratiques
Profiter des plaisirs canadiens^^

## proposition
Je lui ais proposé de créer un partenariat entre Perdre le signal, Fablab PEC (à Montréal) et OpenFab pour envoyer un maker pour une résidence et création d'ateliers la bas. Elle revient vers nous pour une proposition mais ça peut être bien de la relancer.

## ressources
A priori il y aura du budget, les échanges Canada/FWB sont demandé et la cible jeune permet d'avoir des subsides plus facilement :)

**Comment by nicolasdb** [comment]
Yes !
![image](https://user-images.githubusercontent.com/12049360/47805432-98b8fc80-dd37-11e8-9358-e824f5baa451.png)

**Comment by nicolasdb** [comment]
on relancerai pas? 
à mettre en lien avec le projet de **Coopérations francophones au sein du collectif Fab City**

**Comment by DewiBrunet** [comment]
Oui excellente idée!! rappelle moi de faire ça semaine pro si j'oubli!

**Comment by nicolasdb** [comment]
Issue moved to [openfab-lab/workshop #7](https://github.com/openfab-lab/workshop/issues/7) via [**ZenHub**](https://www.zenhub.com/)
