### ISSUE TITLE
Rangement du fablab

### ISSUE THREAD

**Issue by satblip** [openfab-lab/openfab#242]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*

## contexte

Préparation du déménagement en rangeant le fablab, ya du boulot!

## objectif

- [ ] Mettre tous les outils en boites nommées 
- [ ] Trier les ressources et jeter ce qui ne servira plus
- [x] Rangement câblage réseau et électricité section laser/assemblage
- [x] Rangement section imprimante 3D
- [ ] Rangement section entrée
- [ ] Rangement section stock
- [ ] Rangement section bureau
- [ ] Rangement table de bureau
- [ ] Rangement cuisine
- [ ] Aménagement cubes membres level 3 espace epson
- [ ] Grand nettoyage balais et eau général

## proposition

On se retrousse les manches et on y va !

### rewards

@satblip 
=======
+ mercredi : 3h de travail (105crrr)
+ vendredi : 4h de travail (140crrr)
+ Badge laser
+ 1xp laser
+ 1xp colle à bois
+ 1xp balais
+ 1xp câblage réseau

@Jorgininho 
=========
+ 1xp colle à bois

**Comment by satblip** [comment]
Remplacement des filtres de la laser:

**Comment by satblip** [comment]
Découpe et assemblage de boites (10) pour les outils :

![image](https://user-images.githubusercontent.com/1811109/48269780-b0c80480-e438-11e8-99e4-f09609a6f34e.png)
![image](https://user-images.githubusercontent.com/1811109/48269892-f389dc80-e438-11e8-828b-91928254a90f.png)

Note: Il faut choisir les "sujets" des boites, il reste des trucs obvious comme "clouer", qui a des idées? Il me faut aussi quelqu'un pour écrire les tags, car j'écris très très mal :)

**Comment by nicolasdb** [comment]
Frapper. Pour les poinçons, marteaux and shit.

**Comment by nicolasdb** [comment]
Coller, peindre, usber si c'est l'action de connecter à l'aide de cable usb.

**Comment by nicolasdb** [comment]
Et pour les tags, je colle un tape ou qqch pour la version alpha. Je ou quelqu'un peindra les boites puis seulement, écrire le tags final

**Comment by satblip** [comment]
note: je dois encore racheter du MDF pour le lab

**Comment by satblip** [comment]
J'ai recâblé le réseau en évitant d'avoir des cables au sol pour pas que l'on remarche dessus, j'ai testeé NAS, WIFI et Laser, tout est accessible 

![image](https://user-images.githubusercontent.com/1811109/48282744-d6fe9c00-e45a-11e8-9106-beaefaa3b700.png)
![image](https://user-images.githubusercontent.com/1811109/48282808-ff869600-e45a-11e8-9e21-4197af0e0269.png)

Note: un ou deux câbles ont leur pin d'arrêt qui s'est barrée avec le temps, prendre une pince et des fiches pour les remplacer pour éviter les deconnexions

**Comment by satblip** [comment]
J'ai rangé les grandes planches et ait libéré les radiateurs, car comme @milenasonneveld l'a bien fait remarqué, un radiateur ça doit irradier et en gros là on chauffait des meubles et des planches en bois :D 

![image](https://user-images.githubusercontent.com/1811109/48282927-58eec500-e45b-11e8-93ba-50c97d4489ff.png)
![image](https://user-images.githubusercontent.com/1811109/48282938-60ae6980-e45b-11e8-9cb0-6d27ad51183c.png)

**Comment by satblip** [comment]
J'ai rangé le display, parce que c'est cool 😄 

![image](https://user-images.githubusercontent.com/1811109/48282993-80de2880-e45b-11e8-8901-9a654087b854.png)

**Comment by satblip** [comment]
J'ai rangé les outils Bosch et ai fait un coin "recharge", je fais un message sur facebook pour sensibiliser 

![image](https://user-images.githubusercontent.com/1811109/48283066-b2ef8a80-e45b-11e8-9100-c57c96d6296f.png)

**Comment by satblip** [comment]
J'ai déplacé la borne d'arcade (btw, elle était allumée en veille, je sais pas depuis combien de temps, mais dommage pour la consomation). Ca fait beaucoup plus de place en rentrant et autour de la table d'assemblage. (le coin de l'entrée est encore à ranger 😄 

![image](https://user-images.githubusercontent.com/1811109/48283246-3c9f5800-e45c-11e8-8c64-d7306a3c3f71.png)
![image](https://user-images.githubusercontent.com/1811109/48283258-445efc80-e45c-11e8-8594-a2932016e31c.png)

**Comment by satblip** [comment]
Bon y a encore pas mal de boulot, j'y vais au finish :) Par contre @openfab-lab/superuser @openfab-lab/team-job @openfab-lab/team-gestion @openfab-lab/team-a @openfab-lab/team-event, je me sens bien seul lors de mes sessions de rangements, je vous invite donc à venir me rejoindre les mercredis et vendredis, même une heure en fin de journée pour ranger tout ça, je vous vois plus quand le sensei est là ;)

**Comment by satblip** [comment]
PS: j'adore `usber` j'appelle le Larousse pour qu'il rajoute le mot 😄

**Comment by DewiBrunet** [comment]
Nice! Bravo @satblip 👍 

Je passe mercredi prochain aider la dessus (et certains soirs, parce qu'il y a aussi le petit cortex à nourrir^^).

Pour les tags, je peux faire un truc propre et réplicable avec la découpeuse vinyle, faut juste définir la typo (roboto?) et la couleur.

A propos de couleur, @nicolasdb avait fait un super boulot la dessus, ce serait cool de reprendre la logique et améliorer le principe : https://nicolasdb.github.io/post/colorcode/ 
 (--> https://github.com/nicolasdb/nicolasdb.github.io/issues/29)

**Comment by satblip** [comment]
Oui j'adore l'orange to interact, à garder clairement

**Comment by DewiBrunet** [comment]
Je m'attaque au point 2 " Trier les ressources et jeter ce qui ne servira plus"

Work in progress au niveau des déchets laser : 
<img src="https://user-images.githubusercontent.com/25649502/48303964-e0970b00-e511-11e8-81b5-d474d8343b91.jpg" width="250" height="200">

--> j'ai dégommé et jeté ce qui sert à rien (et yen avait plein et il m'en reste un peu à faire!)

![20181110_171700](https://user-images.githubusercontent.com/25649502/48303969-f99fbc00-e511-11e8-9468-c44b323dd80c.jpg)

--> j'ai fait un bac avec tout ce qui doit être dégommé à la scie. Si quelqu'un veux garder certaines de ces chutes, c'est le moment de s'exprimer, sinon poubelle! Je m'en occupe semaine prochaine.

--> je réfléchis à un moyen de plus avoir cette situation car c'est récurrent (->panneau avec ma tronche "i'm not your mother, deal with your shit" et "content de bénéficier des chutes gratos? envie que ça continue?" et "bien...pas bien")

samedi : 1h de travail (35crrr)

**Comment by DewiBrunet** [comment]
Propal pour les tags #swag 
(quelqu'un sais pourquoi mes images se retourne sur github? le code pour changer ça?)
<img src="https://user-images.githubusercontent.com/25649502/48304022-c7db2500-e512-11e8-842d-80c2ee5751f6.jpg" width="400" height="300">

**Comment by DewiBrunet** [comment]
et sinon @satblip j'ai pas réussis à retrouver ma boite avec des bouts de vinyle rouge qui me servent de test... (mais je me suis aussi rendu compte que j'avais plein de brol un peu partout qui faut que je dégage!)

**Comment by satblip** [comment]
![image](https://user-images.githubusercontent.com/1811109/48355244-da309c80-e693-11e8-8955-6c3051fae462.png)
Rien qu'une bonne Dymo ne peut résoudre ^^

**Comment by satblip** [comment]
(d'ailleurs, retour d'xp ici, d'office écrire des deux côtés de la boite 😄 )

**Comment by nicolasdb** [comment]
à Depo2015; l'atelier kids
![image](https://user-images.githubusercontent.com/12049360/48368429-fba18080-e6b3-11e8-810a-a1440478fffa.png)

**Comment by satblip** [comment]
Super love, on doit réfléchir à ça pour le prochain lieu de travail

**Comment by nicolasdb** [comment]
Nouvelles idées de noms.
- reseauter
- programmer
- condenser
- résister
Et bien sûr
- électroniquer
- tamponner

Tout n'est que du contenu a destination d'une action, n'est ce pas ?

**Comment by satblip** [comment]
Aujourd'hui, coin 3D Print
![image](https://user-images.githubusercontent.com/1811109/48494255-c9b42980-e82d-11e8-95d9-8e7b5071aaeb.png)
![image](https://user-images.githubusercontent.com/1811109/48494267-d33d9180-e82d-11e8-9a58-4411beed2f08.png)

Remplacement du plateau de la E10
![image](https://user-images.githubusercontent.com/1811109/48494305-e81a2500-e82d-11e8-8b03-c7d187aa2609.png)

**Comment by satblip** [comment]
Rangement des filaments de stock 

![image](https://user-images.githubusercontent.com/1811109/48494538-624aa980-e82e-11e8-9177-a731b10f5b67.png)

On a aussi un coin électronique 🎉 
![image](https://user-images.githubusercontent.com/1811109/48494566-7393b600-e82e-11e8-92e5-ef8b3d3f0c9b.png)

J'ai aussi eu des crises 
![image](https://user-images.githubusercontent.com/1811109/48494646-9b831980-e82e-11e8-916d-fbf27898470a.png)
![image](https://user-images.githubusercontent.com/1811109/48494684-a9d13580-e82e-11e8-8e74-b13c46eded57.png)
😄

**Comment by nicolasdb** [comment]
Organisation, propreté et rangement des espaces communs
https://wiki.lghs.be/hackerspace:espace

**Comment by nicolasdb** [comment]
update: 
J'ai mis en blanc les boites. 

Next step, à suivre ici:
https://github.com/nicolasdb/nicolasdb.github.io/issues/63#issuecomment-369550620

![g7648](https://user-images.githubusercontent.com/12049360/36840334-dfa9358c-1d44-11e8-92c0-fab9ad195007.png)

**Comment by nicolasdb** [comment]
Ha oui, 
Et un spécial "cone of shame" pour les encolleurs de boites. 
3 des boites se sont défaites lorsque j'ai mis en peinture. Sur un total de 5, c'est pas excellent.

![image](https://user-images.githubusercontent.com/12049360/54597599-20797c00-4a37-11e9-9b14-e089649890da.png)

**Comment by DewiBrunet** [comment]
![e63](https://user-images.githubusercontent.com/25649502/54623605-289fde80-4a6c-11e9-8932-fb2ff88b3ce0.gif)
 Je suis responsable avec @Valonlisbeth de ce mauvais boulot!
0 crédit
+1 pts shame - 1 pts 101

**Comment by satblip** [comment]
Dire que vous m'avez étalé ce boulot dans tous les sens sur instagram 😂😂

**Comment by nicolasdb** [comment]
c'est cool tout ce que vous aviez fait mais faut tout recommencer maintenant :D
