### ISSUE TITLE
AG CA 01/02/2019

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#246]
**Assemblée Générale du Conseil d’Administration de l’ASBL Syntonie**
01 février 2019 – 18h à 20h

Présent :

- Odile Collin
- Francis DeWarichet
- Nicolas de Barquin
- Dewi Brunet
- Aurélie Portois
- Pauline Evrard
- Mathis Pierlot
- Fabienne de Barquin
- Catherine de Barquin

### Ordre du jour

- Introduction : état des lieux 2018/2019 (projets, comptabilité, lieu…) – 15 min
- Tour de table – 15 min

- Acter la démission de l’ancien CA, la nomination du nouveau 
- CA et le déménagement du siège social – 5 min
 
- Définition de la mission du CA, du rôle de chacun et du workflow (notamment AG exceptionnelle) – 20 min
- Modification des statuts & du règlement d’ordre intérieur (établir une todo list) – 15 min

- Gouvernance & prise de décisions : CA, CO, gestionnaire, teams – 15 min

- Autres – 15 min

- Fixer la date de la prochaine AG

**Comment by nicolasdb** [comment]
mise à jour du PV du PR au .md

je clos cette issue.
