### ISSUE TITLE
AaP Ecole-Culture-Quartier

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/openfab#248]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Sabrina, prof de math à l’Athénée Charles Janssens (école secondaite à Ixelles) nous propose de participer ensemble à l’appel à projet « Ecole-culture-quartier » dans le cadre du Contrat de Quartier Durable Athénée.

#### Objectif de l’appel :
- Développer le potentiel socio-culturel de la zone.
- Améliorer les synergies entre les écoles, le quartier et la culture.

#### Thèmes intéressant pour nous :
- L’école et son environnement (connaître son quartier, mutualiser, construire ensemble)
- L’école et l’environnement (mobilité durable, changement de comportements, alimentation durable) 
- Accès à la culture et à l’enseignement (démocratisation, vulgarisation, médiation)

#### Quand :
- Septembre 2019 à janvier 2021
- Deadline : 3 juin 2019
- Réponse : juillet 2019

#### Budget :
- 120.000€ pour l’ensemble de l’appel

Détail de l'appel : http://www.ixelles.be/site/783-Appel-a-projets-Ecole-culture-quartier

## objectif/intérêt
- un projet régulier en phase avec nos valeurs de transmission
- une utilisation du matériel/contenu/expérience de fabmob
- l'appui d'un encrage local avec la commune (qui encourage notre candidature rue Gray)

## proposition
Discussion avec Sabrina le vendredi 10 mai 2019

**Comment by DewiBrunet** [comment]
Ce que j'ai en tête pour l'instant :
- trouver un projet ambitieux de fabrication, en lien si possible avec l'environnement et le quartier (fabrication de capteurs, mini production d'énergie éolienne, ....)
- prévoir un temps régulier en classe et/ou au fablab (ex : 2h en classe et 2h au fablab/semaine)
- incorporer un aspect de documentation : ouvrir une chaine youtube ou l'objectif d'un tuto sur instructable ou sur github (et pas un truc "juste" pour garder une trace mais un truc vraiment pro!)
- voir si on embarque des partenaires du quartier avec?
- bien définir au préalable qui embarque dans le projet et avec quel rôle

**Comment by DewiBrunet** [comment]
Rapide résumé de notre discussion avec @nicolasdb en préparation du rdv de demain :
- proposer une formation aux enseignants (car comme on voit avec fabmob, une fois qu'on est parti les profs on peur/savent pas...)
- créer du next step après l'école

Prévoir d'éventuels partenariats avec : Mundo-b, Ecole des Arts, Horloge du Sud...
Prévoir d'éventuels co-financement avec : GoodPlanet (si sujet enviro) ou Scout (proposer le même service pour former les animateurs scouts? à discuter avec @Valonlisbeth!)

Insister sur le fait qu'on développe du contenu pour des workshops ou de la formation aux enseignants et que le budget sert surtout à ça (et pas à donner les animations/formations).

Bien calculer pour avoir du bénéfice qui revient à OpenFab (éviter la même erreur qu'avec fabmob)

**Comment by DewiBrunet** [comment]
## Bilan du rdv :
Était présent : la prof de math, la proviseure, Nico et Dewi
Elles ont aussi été voir l’ULB et la Scientothèque.
Elles nous rappellent leur double public : les 1,2,3 secondaires qui ont besoin des bases (logiciel, 101…) et les 4,5,6 qui sont plus autonomes et veulent aller plus loin. Elles remarquent que les scouts qu’ils ont à l’école sont les plus motivés et les plus indépendants.
- Les besoins des profs = de la pédagogie par projet et du contenu clé en main (cf : 1,2,3 codez)
- Les besoins de l’école = savoir réparer les machines (dont PC), monter un mini fablab ? Assurer une durabilité des activités, une indépendance des profs

### Ce qu’on a décidé de proposer :
1)	Des workshops chaque mercredi (prolonger ceux de fablab mobile)
2)	De la formation aux profs
3)	Création de contenu
4)	(+bonus : expertise fabrication et réparation machines)

En lien avec l’appel à projets, le contenu pourrait cibler l’écologie : travailler sur la mise en place de capteurs dans le potager de l’école par exemple (il y a d’ailleurs un prof de biologie à l’école qui s’en occupe). Ce projet peut être l’occasion de créer des partenariats ou prolonger le projet hors les murs avec : Good Planet ou Centre d’écologie urbaine.

### Budget :
A adapter en fonction de ce qu’on propose. Sur base de 40€/h si dans l’école et 55€/h si chez nous (facturé 34€/h pour les animateurs)

Avec Nico, à la louche on partait sur 
-	un 60.000€ au total sur les 2 ans (+/- équivalent à 1 temps plein d’un an)
-	des binômes systématiques (pour mentorship, croiser expert pédagogie/expert technique…)
-	2 jours/mois de workshop (1/2 jours chaque mercredi)
-	2 jours/mois de formation prof & création de contenu
-	+ matériel, coordination…

Ex avec tarif fabmob : 4 x ½ jours workshop les mercredis/mois avec 2 animateurs, sur 2 an  4 x 160€ x 2 x 24 = 30.720€ pour les workshops (ce sera moins avec les vacances mais faut rajouter les 40% du lab, la maintenance…)

### Proposition de ressources humaines :
Workshop : Sarah  + Milena ou Dewi
Formation prof : Nico + Milena ou Dewi
Création contenu : Louis + Navid
(plus Bertrand en consultance au préalable sur formation prof)

@nicolasdb @milenasonneveld @Valonlisbeth @satblip @O-Navid @DewiBrunet la discussion est ouverte si ça vous intéresse ;) 

### Calendrier :
2 semaines rédaction (deadline 24 mai) :
-	on attend validation 
-	on rédige un premier draft contenu et budget
-	on leur passe le draft pour modification/complément

1 semaine relecture

Prochain rdv : vendredi 17 mai à l’école

**Comment by milenasonneveld** [comment]
Info complémentaire : feedback du stage People Pedal Power :
- très chouette
- apprentissage des outils de base, la soudure, l'électricité et l'électronique (possibilité d'intégrer la laser)
- en partenariat avec MJ Verte (https://www.facebook.com/mjverte/)
- faisable par classes 4-5-6 en 5 demi-journées (mieux de faire 10 demi-journées) pas plus de 13 jeunes
- il faut calculer 2 jours de prépa pour une demi-journée de stage.

**Comment by nicolasdb** [comment]
Issue moved to [openfab-lab/workshop #8](https://github.com/openfab-lab/workshop/issues/8) via [**ZenHub**](https://www.zenhub.com/)
