### ISSUE TITLE
Payer les factures.

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#250]
- [x] OVH
- [x] Refresh
- [x] Commune
- [x] VOO
- [x] Assurance AG

**Comment by satblip** [comment]
ovh? Je l'ai payée 🤔

**Comment by nicolasdb** [comment]
t'inquiète, c'est un vieux truc qu'on a imaginé à l'époque avec Xavier, on paye un domaine qui un jour sera super important. 
cuman.cc 
Coopérative d'utilisation de machine assistée numériquement. 
C'est l'adaptation urbaine des cuma, les coopératives d'utilisation de machine agricole.

**Comment by satblip** [comment]
ok ^^ ;)
