### ISSUE TITLE
[DEV] Mise à jour des tarifs 2020 GRAY

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#259]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Aujourd'hui, les tarifs sont: 
![image](https://user-images.githubusercontent.com/12049360/75979858-aeb56f00-5ee1-11ea-836b-488ca45bb282.png)

Il est important que l'on garde en tête notre mission de recherche d'un modèle économique équilibré car l'argent ou les efforts doivent tjs bien venir de quelque part (cf Lavoisier). 
Et pour ça, avoir une procédure itérative sur l'ajustement de ces tarifs est important. 

Plusieurs facteurs influences aujourd'hui cette demande, ce besoin de mise à jour. 
- Le nouveau local, nous a imposé l'achat d'un filtre à fumée du laser = 3000€ et une consommation importante de filtres (250+90€ each)
- Nous voulons adapter les tarifs à des usages courants. 
1. Soutien non usager
2. Soutien usager occasionnel
3. Soutien usager fréquent
4. Demande de stockage vs place de stockage limité
5. Demande de location (machine transportable, Vélo cargo)
6. Demande de formation
7. Demande de services, Devis et production. 
8. Faible participation vs rémunération sur la gestion.

### avec subside
![image](https://user-images.githubusercontent.com/12049360/75980922-b413b900-5ee3-11ea-96ca-f2ccc118f2b3.png)
![image](https://user-images.githubusercontent.com/12049360/75981363-a1e64a80-5ee4-11ea-9b72-edad8aa599f2.png)

Voici aussi les tarifs de cityfab3, intéressant leur tarif différencié entre membre d'un fablab bxl et les autres. 
https://docs.google.com/spreadsheets/d/1NzhjY0PWkpaCcE6qoKoBRgAbYUmjM8tD3ZbNOqRj71Q/edit#gid=1881868341
### sans subside
![image](https://user-images.githubusercontent.com/12049360/75981676-4799b980-5ee5-11ea-80d1-74d2bd9a7abc.png)
+les options: https://goo.gl/iLrRVi

**Comment by nicolasdb** [comment]
## objectif
Mon objectif n'est pas de monter les prix pour monter les prix. 
Il n'est pas non plus de s'aligner sur le prix des autres 
MAIS toutes fois, il est important 
1. de sensibiliser sur le vrai coût des services d'un fablab
1. d'apporter une transparence à ce sujet, combien du montant est subventionné, combien paye la machine, son entretient, etc... ce que ça implique lorsque c'est cassé. 
1. de comprendre les besoins des usagers 
1. de renforcer notre com sur la mission de l'asbl et que l'abo est un support et non un produit de vente.
1. **de faciliter le message, simplifier les comptes et assumer un modèle d'entraide**
ex: le modèle abo fitness. On est tous ok de payer x€/mois alors qu'on n'y va pas. 
ou: la mutuelle. On paye un peu tout les mois pour au cas où. 
ou: le cafe suspendu. Si t'es à l'aise, tu paye un peu plus, ça aide les makers qui sont dans la dèche au travers d'un abo réduit.

## proposition
> la cotisation de membre est d'un minimum de 20€/an (statuts)

Tous les montants vaudrai comme cotisation de membre adhérent.
1. 25€/an, pour les non usager mais qui veulent nous soutenir dans nos activités. 
2. 15€/mois, avec engagement (6mois? 12mois? ordre permanent?) pour les usagers occasionnel du lab. 
3. 100€/mois, tjs avec engagement pour les usagers fréquents, avec stockage, badge d'accès 24/24, 

Avec toujours la possibilité de réduire ces coûts en gagnant des crédits en participant aux activités/tâches .


## ressources
j'ai bossé sur une map pour nous donner une idée des différences. pour envisager une com. 
![image](https://user-images.githubusercontent.com/12049360/75983684-410d4100-5ee9-11ea-89ef-cc43f53befe4.png)

j'ai aussi avancé sur un tableau avec une projection des entrées par rapport aux frais commun, hors workshops et services. 

## Resultats
Les membres qui aident, qui donne du temps, de l'amour dans le projet ne s'épuiserons pas et le vrai potentiel d'un fablab communautaire pourra grandir et se développer. 
Donc, plus de cool projet, machines, matériaux, événement et opportunités.

**Comment by nicolasdb** [comment]
@O-Navid demandais ce que couterai au total 2 mi-temps de gestion + les charges asbl. 
1 ETP normal (commune d'xl) est accepté à 60k€/an. 

Les frais de l'année dernière s'élève à 14908,75€
![image](https://user-images.githubusercontent.com/12049360/76851369-6daa4c80-6849-11ea-819c-0a7a2e5adec4.png)

Total arrondis à 75k€/an. 
Donc, 6250€/mois
Donc, 312,5€ / jour ouvrable, _j'ai compté 20j/mois._

**Comment by nicolasdb** [comment]
## Statut du nombre de membres
https://github.com/openfab-lab/conseilAdmin/issues/38#issuecomment-599962328

**Comment by nicolasdb** [comment]
avec @O-Navid, on a fait un peu le point sur les tarifs. 
Il en ressort 3 types: _peut-être 4 mais ce serai plus simple de rester à 3_
1. le support sans usage = cotisation annuelle à 25€
2. le support avec usage occasionnel = cotisation mensuelle entre 15 et 20€, faudra préciser htva ou tvac.
3. tjs du support avec usage récurent ou pro = cotisation mensuelle minimum à 42€htva (50€tvac) 
MAIS minimum, lorsqu'un membre vient souvent, c'est qu'il est d'abord passé par l'usage occasionnel, right? 
càd que chaque personne qui souhaite profiter d'un accès fréquent, voir avec les clés et du stockage et tout ça, passe une sorte d'entretient privé avec la team pour clarifier les droits&devoir, inviter à devenir membre effectif et aider à définir une cotisation mensuelle en accord avec ses valeurs et en rapport à son revenu. 
càd le minimum est 42€ facturé htva mais si on est à l'aise financièrement, on peut choisir de donner plus en fonction de sa situation. 

le 4. serait un "bon" de support, à garder, à offrir, whatev' . 50€
avec, très important:
- le rappel que c'est un montant de support pour notre mission, insister sur le why Openfab. 
- en remerciement, ils ont droit à une aprèsmidi de guidance sur un projet, valeur 300€. _watcha-st'aubaine là!_ 
- Mais attention! pour les encourager à venir l'utiliser et luter contre la procrastination, c'est valable que 3 mois. _yup, karma_

On pourrait les proposer en ligne, lors des councils maker, lors d'une campagne de com tout les 3 mois, lors des fêtes pâques, Noel, anniversaire, Hanuka and shit... too much, maybe ... or is it?

## goal = 300€/jours 
pour pouvoir engager 2 mi-temps pour la gestion et l'organisation de plus d'activité > afin d'atteindre la mission de l'asbl bien sur. 

- le rapport au travail, à la production et à notre consommation, par une réappropriation des technologies. 
- un club de geeks et geekettes qui développent leurs skills en faisant des projets DIY. 
(j'dévelop mes skills! j'porte mes sun-glass de steeel)

**Comment by nicolasdb** [comment]
## Goals progressifs
Selon ma dernière estimation, en considérant Syntonie et Openfab comme 2 unités spécifiques. 
Selon Achat/Presta/Revenu
![image](https://user-images.githubusercontent.com/12049360/80680679-8439f980-8abf-11ea-8f7e-27477ad2caeb.png)
1. Les presta Syntonie correspondent à organiser le courrier admin, faire le lien avec l'assureur, le comptable, exécuter les payements, convoquer l'AG, occasionnellement déposer un dossier au moniteur belge, s'assurer qu'il y a de l'ordre dans tout ça. 
**J'estime cette tâche à ~10h/mois.**
1. Les presta Openfab correspondent à:
   1. la maintenance de la ventilation (.5jour, 2x/an)
   1. nettoyage (.5jour, 1x/mois)
   1. Réparation (10h /mois)
   1. Encodage du facturier zoho, suivit des achats, suivit des membres (10h/mois)
### Goal minimum = 800€/mois
Pour couvrir les assurances, le comptable, les charges et différents frais matériels nécessaire à la tenue du lieu. 
Admettons que ceci est le scénario 100% bénévolat. 
### Goal idéal = 2500€/mois
Pour couvrir les frais mais aussi les prestations liée à la main d'oeuvre.

**Comment by nicolasdb** [comment]
## Options cotisations
_je suis occupé d'encoder mes frais chez smart et c'est uberchiant de répéter 12x le membership et 1x la cotisation_ 
Comme je dois encoder par factures, j'aimerai pouvoir choisir un paiement de cotisation à l'année, donc tout en une facture. 
@O-Navid , @DewiBrunet ça doit vous parler.
Est-ce qu'on pratique une réduction dans ce cas? 
![image](https://user-images.githubusercontent.com/12049360/80682274-75087b00-8ac2-11ea-9797-8b21b7ebd5c1.png)

Ensuite, c'est un choix à préciser lors de l'inscription ou à modifier sur son profil de membre en ligne. 
@121593 Loic? Implémenter un champ de ce type sur le site, ça te prendrai combien de temps?
Faudrait réfléchir à comment c'est prit en charge aussi du côté gestion. 
Le service Gestion doit être tenu au courant de la modification et activer manuellement pour le membre concerné, la facturation annuelle dans zoho. (~10min)

**Comment by 121593** [comment]
Ça ne sera pas long
D'après l'expérience des tickets précédents, ce qui sera long sera d'avoir le contenu à afficher à côté du champ :D

**Comment by nicolasdb** [comment]
## tarif horaire - barème proposé
Un alignement de 55 à 60€ est à prévoir dans les tarifs annoncés/appliqués.
- barème à 60€/h déjà appliqué entre Mathieu et Nacho. respectivement pour la sous-traitance CNC et lasercut. 
- c'est plus simple pour les comptes, 1€/min.

**Comment by nicolasdb** [comment]
## Comparaison: 
**FLTM, rue du cigne.**  
Inscription?
L'accès est à:
- 15€/journée par personne, accès occasionnel. 
- 40€/mois par personne, accès Mardi, Jeudi, Vendredi et Samedi. 
\+ prix libre sur les matériaux de récup.

**Comment by nicolasdb** [comment]
## pour les tarifs d'usage laser. 
Mise à jour, l'ajout d'un compteur pour le temps d'activité du laser. 
Il compte en décimal, 1h = 1 unité donc 0,1 unité = 6min. 
Le tarif des membres est donc aujourd'hui à 60€/h tvac, ça semble plus cher qu'avant mais on ne compte que le temps réel du tir de laser (peu importe sa puissance!). 

Le calcul est donc simple. 
On compte 15€ de départ, par défaut même si le job ne prend que 2min. 
Concrètement, tu note la valeur du compteur avant/après et on multiplie le delta mesuré par 60€.
Ex: départ du compteur à 105.3, fin du job, 106.0 > 15+(60*0.7) = 57€
Si le job est très court, départ à 105.3, fin à 105.3 > 15+(60*0.0) = 15€

bisous

**Comment by nicolasdb** [comment]
## Calcul de tarif en fonction de la valeur de la machine

La formule se base sur un % de la valeur par jour d'usage et puis une approximation d'un coût à la minute. 
**Paramètres:**
> - IF valeur > à 1500€ alors 5%, Else 10%. 
> - la journée est de 8h
> - le starting fee correspond à 15 min. 

Exemple pour la lasersaur:
![image](https://user-images.githubusercontent.com/12049360/88372396-1d626e80-cd96-11ea-8183-9fde22b74f64.png)
et nous obtenons les tarifs proposés précédemment 

Du coup, si j'applique le modèle à: 
### li'l Sebastian (mini laser)
![image](https://user-images.githubusercontent.com/12049360/88372878-112ae100-cd97-11ea-9f98-16245abebe4e.png)

### Vinyl Cameo
![image](https://user-images.githubusercontent.com/12049360/88372932-2b64bf00-cd97-11ea-9142-8b4cba9532f1.png)

### CNC 3040
![image](https://user-images.githubusercontent.com/12049360/88372986-4b947e00-cd97-11ea-96c8-5d4103555568.png)


Admettons aussi que 
- si on peut être précis sur l'estimation ou la mesure du temps et que l'usage dépasse par défaut les 15min, on n'applique pas le starting fee. _ça fait sens avec le laser qui n'est mesuré que par 6min et qu'on peut souvent être en dessous, mais avec l'impression3D?_ à voir avec la pratique.
- les calculs sont arrondis au 0.10€ supérieur. 
- L'unité payée est celle consommée. 
- le tarif horaire correspond plus justement à l'usage qu'on en fait. Principalement pour la 3D, il y a de grosses différences de temps en fonction de la qualité des réglages (couche et détail) qui ne sont pas représentées par le tarif au gramme. 
- l'objectif premier des revenus est de rembourser l'achat de la machine, ensuite c'est pour 1: entretient/achat, 2: revenu pour l'asso.

**Comment by nicolasdb** [comment]
dernière mise à jour des tarifs mise en ligne sur le site web, 
l'original est sur le drive
![image](https://github.com/openfab-lab/openfab/assets/12049360/65494732-78eb-4cf4-aa96-f2332b09c400)
