### ISSUE TITLE
Vermicompost/compost 

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#26]
C'est super cool comme petit projet DIY. Et ça donnerai l'exemple d'en avoir un ici.
Exemple:
http://woodwormfarms.com/index.php?route=product/product&product_id=55

![vermicompost-embed-large](https://user-images.githubusercontent.com/12049360/26916495-ea8b5016-4c2a-11e7-8d70-1c7e0df8d1ae.png)

**Comment by softrevolter** [comment]
Une chouette missoin 'boss' pour le user non?

**Comment by softrevolter** [comment]
donc si je prendrais mon exemple dans issue #16 si je crée cette mission et qu'elle est validé par la table des anciens ( ou quelque chose dans ce genre) je recevrais un 1D6

**Comment by nicolasdb** [comment]
donc, pour reformuler ton commentaire et être sur d'avoir compris: 
- Tu vois l'issue, ça te motive
- Tu rempli une fiche projet sur la création d'une boite à vermicompost (lien vers fiche projet type?)
- que c'est validé par les anciens (qui? à définir) (comment? push/pull request maybe?)
- tu gagne 1D6 pour la définition de la mission

La mission elle même est peut-être valorisée par les anciens (4D6 dans ce cas) 
Lorsque la mission est cloturée càd: 
- documentée et finie selon les critères/objectifs définit dans la fiche projet
- reward de 4D6 supplémentaire. 

La personne qui crée la fiche projet n'est pas obligatoirement celle qui remplit la mission.

**Comment by softrevolter** [comment]
Yes YES et encore YEEEES :D

**Comment by softrevolter** [comment]
bon je vais cloturer cette issue pour les raisons suivantes:

c'est documenté à deux endroits -> issue #35 et maintenant [ici](openfab/Gamification/Missions/Boss 1: Aquaponic System.md) 
je l'ai enlevé des quest, car pour moi c'est plus-tot un Boss level, les quests c'est des truc donné par des gens endehors du FabLab non?

Puis la question est, si je crée une mission dans le rep. de Gamification, est-ce que on doit encore les avoirs en Issue? en Issue on peut mettre les labels, les mettres en projets et tous, c'est cool, mais alors tous les mission vont ce mélanger avec le reste. 

L'idée est alors de créer un rep. unique pour Gami avec son architucture propre, qui pompe de tous le reste pour gamifier ça, vous suivez encore?

**Comment by nicolasdb** [comment]
j pense que ce genre de mission doit aboutir à la création d'une fiche projet. 
Puis d'un répository spécifique, en charge de qqu'un ou d'une équipe pour y documenter l'évolution de l'aquaponie au  buro274

**Comment by nicolasdb** [comment]
Attention!
Ne pas confondre aquaponie et compost ! 

Dans l'issue 35, je propose une mission sur l'aquaponie. 
Les vers du vermicompost pourraient en fait nourrir les poissons. 
Et la boucle est bouclée... :)

### bref
Ceci dit, même si c'est de vrai proposition mission, j'ai surtout testé 2 cas: 
- 1. créer directement une fiche projet.
Puis je me suis rendu compte qu'il faut peut-être d'office une issue pour initier le process... 
- 2. proposer un sujet de mission via une issue. 
à qui veut, de détailler la mission dans une fiche projet.

**Comment by softrevolter** [comment]
est-ce une mission ou juste une idée?

**Comment by nicolasdb** [comment]
c'était une idée de mission pour tester la méthodo mais Slyman m'a dit être chaud pour le faire. 
Reste à le mettre en action.

**Comment by nicolasdb** [comment]
On en a reparlé avant le déménagement et même si ça serait parfait dans notre jardin. 
C'est une préoccupation et une gestion supplémentaire qui sera certainement prise en charge dans le quartier à court terme. 
- le potager et toiture au niveau du colruyts, il y avait un compost géré par le début des haricots, ça devrait se remettre en place à la fin des travaux. 
- projet de poulailler participatif au parc viaduc. Une demande à été faite dans ce sens par le collectif ReSeptre.
