### ISSUE TITLE
Gestion Projets

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#27]
J'ai été inspiré par ton petite ajout dans Projects, gestion de bureau @nicolasdb 

Est-ce qu'on mettrais pas la, la visualisation des missions, quests et autres

Avoir 3 grands boards

User
Super User
Meta User

ou on peut bouger les projet, les lier au bon répo, bouger les tâches récurrante et autres. ça serait bien de voir tous ça. Et puis faire un board par Grande Quest comme la jacqueline pour bien voir le projet des Quests

**Comment by nicolasdb** [comment]
ouais, à fond. 

Mais je ne connais pas encore bien le process des projets. 
Faut qu'on teste. 
L'usage des Milestones conjointement avec les projets et labels pourrait être super efficace.

**Comment by nicolasdb** [comment]
voir #30

**Comment by nicolasdb** [comment]
@softrevolter 
En fait, j'ai créé un projet Workflow pour y reprendre et analyser les tâches par type.
https://github.com/openfab-lab/openfab/projects/6

Quels types de tâches sont récurrentes, quels types concernent User, SuperUser, ...

Du coup, je clos cette issue.
