### ISSUE TITLE
Labelisation

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#28]
based on this logic, how can we make our labilsation better

https://github.com/openfab-lab/openfab/blob/master/Gamification/5cat-genealogy.md

**Comment by zuperninja** [comment]
Qu'une personne soit en charge d'observer ce qu'il se passe et de caser tout ça dans ce système ?

**Comment by nicolasdb** [comment]
J'avais créé la page dans l'idée d'avoir un document de travail évolutif en partant de ce qu'on sait ou de ce qu'on pense être bien. 
- 5 catégories, 5 couleurs 
Aujourd'hui, 
**Bleu** = ~~lundi~~, ~~l'eau~~, _l'eau est dans tout, fluidifie, communique donc peut-être plus_ ~~Electricité~~ **Technologie**

Bref, tu vois quoi. Si on se rend compte qu'une thématique ou catégorie est trop précise et qu'on pourrait réunir 2 thèmes en un autre mot, on remonte ainsi doucement l'arbre généalogique, tout ça pour n'en avoir tjs que 5 très générale. 
Par contre, faut proposer des thèmes, des idées de labels. 

Actuellement, j'ai commencé en bleu ce qui touche les crédits. 
"Mission" et les valeurs "1D3" "1D4"
J'ai backoffice en Gris pour la compta, et les tâches de support. 

Le reste je sais pas. 

On en reparle en tout cas dans la #11 et aussi dans le repo github intro https://github.com/openfab-lab/github-introduction-ws/issues/4
J'aime particulièrement bien cette approche:
https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63

Il a même un script pour redéfinir une liste de labels lorsqu'on crée un nouveau repo et pas le refaire à la main.
à explorer aussi

**Comment by softrevolter** [comment]
bon on à discuté autour de la labelisation et suite au tests, voici ma proposition: 

Jaune: plastic / metal / ind Material
Vert: Wood
Bleu: electronic / energy
Rouge: Bug / help needed
Noir: Code/ software / programming 
Gris: BackOffice

Statut: idée, blockée, à faire, en cours, idée, 

Urgence: faible, moyenne, fort, 

Valeurs: Dé

**Comment by zuperninja** [comment]
Donc pour chaque issue on a un code couleur, un statut, une urgence et une valeur ? 

Je réfléchissais au label en lisant GTD et ReWork. Je partage un début de réflexion.

|
Nom du tag | Description |
| --- | --- |
| Statut : Inactif | Une issue dont le groupe n’a pas jugé utile de donner suite ou qui n'a pas trouvé sa place dans la timeline. |
| Statut : Actif | Une issue qui a trouvé une solution acceptée par la majorité ou noyau dur. Une issue active. Statut par défaut. |
| Statut : Ouvert | Une issue où l’on recherche des personnes pour s’en occuper/collaborer. Par ex : Transformer l'issue en page wiki. |
| Statut : Prendre une décision | Une issue bloquée, besoin de prendre une décision. Actif ? Inactif ? Ouvert ? _Citation : "You can't build on top of "we'll decide later" but you can build on top of "Done"." "commit to making decisions. Don't wait for the perfect solution. Decide and move forward" Rework, Jason Fried _ |
| Statut : DONE ! | Une issue qui a été accepté et dont la documentation a été faite. Appel à la célébration. |

**Comment by nicolasdb** [comment]
j'aime bien, j'ai ça au dessus de mes écrans. 
![n3buaskj5-irxvounzqummrvjmldehll4-a3nlqf7uhzel-laydduacahwgg4xg6wkwi7_dbhb1plpbcpkoz3ib8aieejw806z88b6z6whlnhkt10mzjpm6nq6act7epoiexb4w0cc4kbzg8t_a2gns0_xw8oltpdhvlzc5gbundmmrfurnoj-dyigtyl3ck23jlsegnmo3wiwdwvdm](https://user-images.githubusercontent.com/12049360/27440524-5aaa7890-576b-11e7-8b46-0a12f79fa28a.jpg)

**Comment by nicolasdb** [comment]
[gtd_workflow_advanced.pdf](https://github.com/openfab-lab/openfab/files/1095196/gtd_workflow_advanced.pdf)
![gtd](https://user-images.githubusercontent.com/12049360/27440573-7ace5984-576b-11e7-8cad-7394697e9540.jpg)

**Comment by zuperninja** [comment]
Oh il est beau ce flowchart de GTD !

**Comment by softrevolter** [comment]
fait un pull request pour valider les couleurs et les choix en lien avec la gamification
