### ISSUE TITLE
Bank Of Skills

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#29]
Create a logic protocol where the skills are noted in our system

**Comment by nicolasdb** [comment]
ça pourrait être cool d'arriver à un flowchart visuel.
![image](https://user-images.githubusercontent.com/12049360/27322567-e299ef0c-559e-11e7-907a-3a1e6774ed56.png)

Ceci dit, on pourrait essayer d'utiliser twine pour tester les logiques scénaristiques, il y a moyen d'ajouter des balises conditionnelles et de définir des valeurs et les faire évoluer en fonction des passages/actions que l'on décide. 
ex: 
Début d'histoire (valeur: CRRR=0), 
plus loin, après cloture d'une action (CRRR = CRRR+5)
La valeur est maintenant CRRR = 5, 
passage suivant, si CRRR = 45, on peut afficher une nouvelle option de choix. 

Bon, je dis ça mais je sais pas bien comment ça marche, je l'ai juste lu. Reste à voir comment faire avec github. Il y a une API github pour collecter, utiliser, envoyer ailleurs les données d'ici.
 
y a plein de youtube sur twine, c'est cool l'internet.
https://www.youtube.com/watch?v=trguvHzlvrU

**Comment by softrevolter** [comment]
ça devient donc les badges, ce issue n'as plus sa place? 
Qui cloture?

**Comment by nicolasdb** [comment]
La suite se détaillera ici.  https://github.com/openfab-lab/pack-openbadge-fablab

process: 
- proposer un badge
- son unité 
- comment le débloquer
- les paliers de level pour chaqu'un
- et le gain bonus gagné en fonction du niveau.
