### ISSUE TITLE
glossaire des termes utilisés

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#30]
@openfab-lab/gami 
Je me pose aussi la question de qu'est-ce qu'une quête? le rapport avec un projet? 
Il faudra peut-être aussi définir les termes et le lien entre eux quelque part. 

Comme je le comprend maintenant c'est:
- Un projet = une quête, une quête est définie par la "fiche projet ++" version relativement complète 
- Une quête est composée de plusieurs missions. 
- Une mission est définie par une "fiche projet --" une version simplifiée 
- Les missions peuvent couvrir un thème spécifique mais pas nécessairement unique au projet. Utilisation de #tag pour associer des thèmes transversaux.
-Est-ce qu'une tâche est une mission? ou une mission peut se composer d'une série de tâches?

Ce que je trouve compliqué, c'est qu'il y a des termes qui sont similaires ou identiques en anglais et français et aussi ici sur github mais que le sens et les logiques d’affiliations ne sont pas toujours pareil. 

Sur github, je fais le comparatif suivant:
- un repository reprend le contenu d'une quête, défini par son README.MD, le résultat documenté par son wiki et dont la R&D est son contenu (dossiers, fichiers .md et sources)
- une quête peut-être composée de "milestones", des objectifs à franchir sont définis, des étapes importantes sont à franchir dans la progression de la quête? Une aide à la planification?
- Les Milestones sont composées d'issues, (mission ou tâches?) Il y a une jauge d'état d'avancement pour les milestone, composée du total d'issues assignée à la milestone et de son ratio issues open/closed. 
- Les labels, c'est les tags. pour classer par thèmes transversaux entre quêtes ou milestones. Peut servir dans les outils de recherche.
- reste les projets? reprend les "issues" pouvant être converties en "task" et classé sous forme de tableau kanban/trello pour les états d'avancement.  

J'aimerai qu'on puisse fixer ces infos là aussi dans le wiki, ça aidera aussi dans une forme de gestion de projet, qui fait quoi, on en est où, qu'est-ce qu'il reste à faire, dans quel objectif.

**Comment by nicolasdb** [comment]
Je vois que je ne suis pas le seul à me poser la question :D
https://stackoverflow.com/questions/39591795/what-is-the-difference-relationship-between-github-projects-and-milestones

**Comment by softrevolter** [comment]
je suis presque tous à fait d'accord avec toi Nico, 
donc si je peut m'essayer à un premier jet de clarification

**Repository** avec sa structure = Quête 
**Projects** sert à manager les Tasks = Missions Recurrent / Overview Mission? 
**Issues** = Début de création d'une Mission
**Milestones** = classifications des tous les Mission nécessaire pour voire avancer le projet?

**Comment by nicolasdb** [comment]
ouais, reste à mieux comprendre les subtilités de la gestion de projet. 

MAIS surtout, je pense qu'il est urgent de faire une première liste de labels. Quand je relis les issues ouvertes, il y souvent des sujets complémentaires mais discuté sur plusieurs issues. 
Un label commun permettrait de faire ressortir la thématique en question. 
ça ferait déjà un beau tri et amènerai la définition d'un projet ou d'une milestone.

**Comment by softrevolter** [comment]
je m'occupe de créer un glossaire et une logique de glossaire sur le wiki

**Comment by nicolasdb** [comment]
Tiens, est-ce que quelqu'un a avancé sur ce glossaire?
j'ai l'impression que ce sujet est revenu plusieurs fois.
