### ISSUE TITLE
Présentation OpenFab pour site internet

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#31]
**Contexte :** 
1 an que le site d'OpenFab n'a pas été mis à jour, il faudrait mettre à jour la présentation du projet.

Site : http://openfab.be/

**Objectifs :** 
_Pouvoir expliquer clairement dans quelle direction avance OpenFab pour trouver des partenaires qui vont dans la même direction.
_Montrer qu'OpenFab s'inscrit dans un projet plus grand que lui, une vision de société.
_Marquer la différence d'OpenFab comparé aux autres fablabs bruxellois.
_Mettre en avant la communauté Openfab (les projets réalisés et en cours avec la doc si existante ; + vu des badges (gamification) des membres ?)

**Questionnements :** 
_Présentation pour la page d’accueil du site ?
Avoir deux versions, 1 synthétique (accueil) et 1 plus précise (autre page : À propos ?)
J'aime bien l'idée que la page d'accueil aille droit au but, qu'une personne qui arrive sur le site soit vite rediriger vers ce qui l'intéresse. (--> Google Analytics ? #32  Comprendre qui vient sur le site et pourquoi, cela permet de plus facilement savoir ce qu'ils attendent et donc adresser le bon message. --> Restructuration du site ? Suite à l'analyse.)

**Documents préparatoires :**
_Le texte actuel du site internet ainsi que le texte préparé pour Design September par [ici](https://github.com/openfab-lab/openfab/blob/master/Txt%20pr%C3%A9sentation%20OpenFab.md).
_Et [là](https://github.com/Ginsburg/openfab/blob/master/S%C3%A9mantiqueOF.md) un simple champ sémantique, d'inspiration autour d'OpenFab
_Par [ici](https://github.com/Ginsburg/openfab/blob/master/Why-How-What.md), une structuration du message d'OpenFab autour du Why/How/What

**Document de travail :**
[Ici](https://github.com/Ginsburg/openfab/blob/master/texte-site.md)

**Comment by zuperninja** [comment]
Je rajouterai dans les objectifs :

- mettre en avant la communauté openfab (les projets réalisés et en cours avec la doc si existante ; +vu des badges (gamefication) des membres ?)

**Comment by softrevolter** [comment]
j'ai essayé un premier pull request sur base de ton texte, tout petit changement car je sais pas trop comment ça prend forme :)

**Comment by Ginsburg** [comment]
Si on joue la carte du "Plus qu'un FabLab", est-ce qu'on irait pas jusqu'à rediriger les visiteurs vers les autres FabLabs bruxellois s'ils ne veulent pas de cet aspect communauté, aventure humaine ? 

Pour le coup, ça n'a pas sa place sur la première page du site mais est-ce qu'on ne les amène pas vers ça après qu'ils aient cliqué sur "rejoignez-nous" (ou équivalent). On leur explique un peu plus le topo et on ose un "si tout cela ne vous correspond pas, n'hésitez pas à aller chez : ... (liste des fablabs bruxellois)."

Ils abordent ça dans le chouette bouquin : ["Rework: Réussir autrement"](https://www.amazon.fr/REWORK-REUSSIR-AUTREMENT-Jason-Fried/dp/284001713X)

J'aurai du ne faire qu'une issue pour le site plutôt que 2 : "restructuration" et "présentation".

**Comment by nicolasdb** [comment]
pour la redirection, on pourrait avoir une page de lien vers le réseau Bruxellois? ça se fait encore ça ou c'est super ringard ?
ça fait moins "si ça vous plait pas, vous pouvez tjs aller voir ailleurs... "

**Comment by zuperninja** [comment]
Oui une carte en embed sinon avec un zoom sur Bruxelles, et si c’est des gens de ailleurs ils peuvent s'y retrouver aussi

**Comment by nicolasdb** [comment]
j'ai commencé les cours sur

**Comment by softrevolter** [comment]
je permet de le placer ici, car j'ai pas envie de créer un nouveau issue pour ça.

https://github.com/openfab-lab/openfab/blob/master/storytelling/Gamification%20au%20Fablab.md

j'ai commencé à expliquer le premier mois de documentation, @Ginsburg tu peux aider sur le texte?

**Comment by Ginsburg** [comment]
@softrevolter Je fais ça, je commence par la correction de l'orthographe et pourquoi pas quelques tournures de phrase. Je vais essayer de ne pas dénaturer ton taf :)

Merci en tout cas, c'est chouette.

**Comment by nicolasdb** [comment]
Moi j'ai mis en page :D

**Comment by softrevolter** [comment]
Ou on en est ici?

**Comment by nicolasdb** [comment]
suite ici
https://github.com/openfab-lab/openfab/pull/120
