### ISSUE TITLE
Analyse des visiteurs site internet

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#32]
**Contexte :**
1 an que le site d'OpenFab n'a pas été mis à jour et il serait intéressant de lui faire un petit lifting (#31 & #33)

Site : http://openfab.be/

**Objectifs :**
_Comprendre qui sont les visiteurs du site OpenFab pour pouvoir le mettre à jour correctement avec un message qui correspond à sa cible.

**Questionnements :**
_Comment faire du "Quick and dirty" sur ce sujet ?

**Tuto :**
[Configurer le suivi Analytics](https://support.google.com/analytics/answer/1008080?hl=fr)

**Comment by zuperninja** [comment]
Pour le moment en outils analyse visiteur on a 👍 

- Wordpress sur le tableau de bord
- Google my Business (reçu chaque mois sur la boite anca@openfab.be)
![image](https://user-images.githubusercontent.com/25099826/27081222-a4d50512-503f-11e7-8677-53abe224b1cf.png)
- [Smartlook](https://www.smartlook.com) qui capture le comportement des visiteurs sur notre site (id et mdp voir avec moi)
![image](https://user-images.githubusercontent.com/25099826/27081460-c2f3c0be-5040-11e7-986a-27eb759e5095.png)

On peut faire un questionnaire à diffuser via facebook + mailchimp pour connaitre les attentes

**Comment by softrevolter** [comment]
ça serra peu-être interessant d'avoir un endroit ou on pourrais consulter les données en 'temps réel' sur le github. Une partie: Analytics qui reprend un peu tous ça 
ça peut aider des gens pour leur dossiers, pour améliorer de la communication ciblé, ... 
Mais perso pas fort dans ça

**Comment by zuperninja** [comment]
@softrevolter : de façon automatisée ?

Quel comportement et info on veut relever ? Si on sait un peu mieux ça on peut créer/trouver des outils qui correspondent mieux.

**Comment by Ginsburg** [comment]
J'imaginais savoir quels mots clés sont tapés pour arriver sur le site par exemple. 

Si les gens tapent "OpenFab", on peut imaginer qu'ils connaissent déjà le FabLab et donc on peut se concentrer sur la présentation "Plus que FabLab" ou alors ils tapent juste "FabLab + Bruxelles" et là on risque peut-être de leur faire peur à vouloir aller plus loin (mais bon, ce n'est pas forcément mauvais, comme dans le bouquin Re:Work, prendre des parti-pris et ne pas hésitez à rediriger vers d'autres FabLabs qui répondent mieux aux attentes pour des projets one-shoots en solitaire).

**Comment by nicolasdb** [comment]
ouais, prenons parti. 
ça filtre et surtout ça attirera plus clairement ceux qui ont la même vision.

**Comment by zuperninja** [comment]
Je suis pour aussi, je regarde ce qu'il se fait pour les mots clefs, très bonne idée

**Comment by softrevolter** [comment]
cloture car discussion à l'air d'être finit?
