### ISSUE TITLE
Restructuration site internet

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#33]
**Contexte :**
1 an que le site d'OpenFab n'a pas été mis à jour et il serait intéressant de lui faire un petit lifting.
C'est la première vitrine d'OpenFab.

Site : http://openfab.be

**Objectifs :**
_Clarifier le message, l'aligner sur les visiteurs (#32)
_Avoir un site à la hauteur des ambitions du projet (#31)

**Questionnements :**
_Réussir à le faire vite et bien sans se lancer dans un grand chantier. --> focus page d'accueil ?

**Inspirations :**
_[Site internet TechShop](https://www.techshoplm.fr/) --> visuel puis message qui va droit au but
"Des ateliers collaboratifs pour réaliser tous vos projets" puis petit texte puis lien vers l'offre.
_[Site internet FacLab](https://www.faclab.org/) --> programme + blog
_[Site internet Artilect](http://www.artilect.fr/) --> carrousel événement + présentation en mosaic de toutes les activités (ateliers, événements, machines, ...)

**Comment by nicolasdb** [comment]
@zuperninja t'aura peut-être des idées sur cette mise à jour

**Comment by zuperninja** [comment]
En quick&dirty, j’enlèverai tout le contenu du site qui est trop dense et plus en phase avec ce que est openfab aujourd'hui. 

Le [texte](https://github.com/Ginsburg/openfab/blob/master/texte-site.md) V2 de@Ginsburg en avant, avec des liens vers le github pour les tarifs et le reste qui renvoie à Facebook (en gros les deux plateformes où nos actus sont à jour).

A terme, on est tous okay pour que le site soit mis à jour via le github en participatif ? Pour que le système interne du site reflète la structure interne de collaboration horizontale qui se cristallise en ce moment.

**Comment by softrevolter** [comment]
je crois que ce serrais le bon premier exemple d'une cristallisation et une acceptation de la methode github

**Comment by Ginsburg** [comment]
@zuperninja Ça semble intéressant l'idée de la mise à jour via github. Si on en arrive à ça + des liens vers les tarifs sur github aussi, que reste-t'il sur le site ?

Peut-être une simple landing page ? avec : 
- court texte de présentation
- bouton "inscription"
- galerie photo des réalisations avec filtre par machine, matériau, ...
- derniers news
- prochains events

Après, du contenu comme le parc machine n'est peut-être pas évident à mettre ailleurs que sur le site.

**Comment by zuperninja** [comment]
On a des pistes pour que le site soit mis à jour via github notamment avec les technologies flat CMS et GO (voir avec @dsmrs pour plus d'info, car je suis pas du tout à jour dessus et j'ai hâte de prendre du temps pour apprendre, et faire des beaux tutos)

Je pense ce que tu as listé @Ginsburg correspond parfaitement à la vision qu'on a pu avoir de l'évolution du site avec @nicolasdb. Donc si on est plusieurs à penser ça, c'est qu'on doit être sur la bonne voie ! J'ai vraiment envie de quitter wordpress car il est lourd et plus adapté.

Pour le parc machine, si un jour on fait un inventaire de ce qui se trouve à l'atelier avec gestion des stocks/entretien. On peut lier cette partie de github au site web aussi. (une idée :) )

De réalisable en quick&dirty :
- court texte V2 par @Ginsburg 
- bouton inscription qui renvoi vers formulaire google drive (on l'utilise toujours @nicolasdb ?)
- prochain event via pluggin facebook

## Proposition pour le reste :
Pour la galerie des réalisations, les étapes que j'ai pu observer :
1. Mettre en place un sourçage des projets collaboratifs (en cours via la création d'un repo par membre et des Crrr)
2. Quitter wordpress et passer à un flat CMS ou Go
3. Automatiser la publication sur le site web 
 
Pour les news, idem. On peut faire un repo "news" avec des issues. Quand une issue est accepté par plusieurs, la news est publiée.

**Comment by nicolasdb** [comment]
Après un petit test d'architecture et scénario dans twine, on s'est retrouvé bloqué à ça.
![screenshot 21](https://user-images.githubusercontent.com/12049360/27133234-ca15106a-5111-11e7-9066-3fa8b47c530d.jpg)

**Comment by looisjl** [comment]
Hello à tous, 

J'en ai déjà parlé à Nico mais je pourrais p-e faire profiter de mon expérience et des outils de ma coopérative de création de sites web pour le site d'OpenFab. On a créé une plateforme WordPress qui permet de faire des sites pros relativement simplement (vous pouvez check notre portfolio via le lien en bas de page http://cobea.coop/). Surtout, j'anime régulièrement des workshops pour accompagner des clients à structurer le contenu de leur site de manière collective (en général 3 workshops de +- 2h30 pour définir une architecture de contenu orientée expérience utilisateur) et depuis peu j'anime aussi des formations pour prendre en charge le design de son site (vous pouvez voir les derniers sites créés lors de notre dernière formation sur https://www.facebook.com/cobea.coop/). 

Faire un _bon_ site Internet prend énormément de temps et demande beaucoup d'expertise dans de nombreux domaines, c'est donc généralement un projet à aborder avec de bonnes méthodes et de bons outils si on veut éviter de créer un site inefficace, peu ergonomique et qui sera obsolète dans 2 ans.. 

Si ça vous dit, je suis disposé à faire une réunion pour en discuter. Je peux vous faire une démo et vous donner des détails sur nos méthodes. Je pourrais tout à fait animer des workshops pour réfléchir à la structure du site. Après pour la création du site, la formation, l'hébergement, le coût, etc je ne peux pas m'engager à ce stade mais je pourrais voir ce que je peux faire.

**Comment by nicolasdb** [comment]
@zuperninja est-ce que ça te parle ceci Anca? C'est un truc pour gérer et afficher ce qu'on veut comme statistique github. (enfin si j'ai bien compris)
https://github.com/keen/dashboards

ça serait sympa d'avoir une page qui donne des stats d'activité. Et je pense aussi que ça peut aider à la mesure des contributions.

**Comment by zuperninja** [comment]
C'est pas mal le dashboard. On part sur un git pages alors ?
Qui est motivé ?

**Comment by nicolasdb** [comment]
voir issues #88 et PR #120 
@zuperninja  check tes mails, je t'ai ajouté dans la team website, j'attend que les autres se manifestent s'il veulent pour les ajouter aussi. Ils ont déjà accès mais on apprned à jongler avec les teams et c'est plus poli, non? :)

**Comment by Ginsburg** [comment]
J'ai eu une piste de structure dans le train hier donc j'ai tenté de la mettre sur un [doc](https://github.com/openfab-lab/openfab/blob/website/_network/proposition-structure-site.md). Mais j'avoue que je cale un peu pour aboutir à une structure finie.

L'idée est de partir du Homepage qui dès le début parle de la réalisation du projet du visiteur (donc avec le parti pris que seulement des personnes avec projets viennent sur le site) et aiguille vers les 2 possibilités, sous forme de bouton cliquable, à savoir :
- Do it Together (parcours membre : amener petit à petit vers une potentielle implication forte dans la communauté)
- On fait pour toi (parcours client : merci de participer au financement du projet et d'aider les entrepreneurs bruxellois)

**Comment by zuperninja** [comment]
J'aime bien ta structure ! Je sais pas quand je vais réussir à me libérer du temps pour vous aider j'en suis méga désolée. Je passe au fablab début novembre. On pourra en discuter :)

**Comment by milenasonneveld** [comment]
https://pages.github.com
J'ai expérimenté un peu avec github pages, mais je ne suis pas arrivée loin. Voir https://milenasonneveld.github.io/velom2/
Après l'investissement demande beaucoup plus https://jekyllrb.com/docs/quickstart/
(ceci juste parce que le site de velom2.be devrait être updated)

**Comment by nicolasdb** [comment]
Ouais, il faudrait avancer sur un setup de base qu'on aime bien et se le partager. 
On a le même problème de mise à jour du site et on a personne de dispo pour travailler sur le sujet.
PH semblait intéressé, faudrait formaliser le besoin et clairement faire une demande au groupe.


Mais je trouve que ce que tu as fait est déjà pas mal, c'est clean.

**Comment by nicolasdb** [comment]
Avec Chic, et en croisant les idées sorties du projet de fablab mobile, j'ai proposé à CHIC,  3 niveaux de site web. 
- niveau 1, le site de plaine commune (FR) avec du contenu corporate avec les enjeux du projet,
   ça touche le tout publique. ça informe.
- niveau  2, le site web github avec mise en page web, pour du contenu technique qui peut évoluer et qui reste lisible par les non-initiés. On y consomme le commun en opensource.
- niveau  3, le compte github. Plus technique et brut, nécessite un compréhension de la logique mais c'est là qu'on peut contribuer au commun. 

![image](https://user-images.githubusercontent.com/12049360/33240248-7624a186-d2b3-11e7-8740-70ac4466f70d.png)

1. On s’informe.
http://www.chic-europecreative.eu/
2. On consomme.
https://chic-europecreative.github.io/
3. On contribue.
https://github.com/chic-europecreative

Et il est évident que la quantité de gens concernés va diminuer vers le bas, 
contribuer demande un effort mais on peut utiliser cet entonnoir pour amener plus de gens à contribuer. 
J'aimerai faire la même chose pour Openfab et pourquoi pas pour Cuman.cc

**Comment by zuperninja** [comment]
Bonne idée !

On envoie les gens vers le niveau inférieur/+complexe via des liens ?

**Comment by nicolasdb** [comment]
oui voilà, comme dans Diablo, y a un escalier 
une fois que t'as buté tout les monstres de l'étage, t'es invité a découvrir la suite.

![stairs](http://sirian.warpcore.org/diablo2/ribinak-8.jpg)

**Comment by milenasonneveld** [comment]
Oui je vois las avantages de la structure ! On a maintenant pour Vélo M² :

   1. On s’informe.
   velom2.be
   2. On consomme.
   https://ciklic.wordpress.com/category/osh/
   3. On contribue.
   https://ciklic.wordpress.com/2017/07/31/openfab-and-wikifab/


--
Milena Sonneveld

M • info@velom2.be
T • +32 (0) 497 253 918
[image: http://www.velom2.be] <http://www.velom2.be>
Project Vélo M² <http://www.velom2.be> - feeling renewable energy

2017-11-27 14:59 GMT+01:00 Nicolas de Barquin <notifications@github.com>:
