### ISSUE TITLE
Aquaponie @buro274

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#35]
# Test Quest 0001
## what?
Could be cool to have an aquaponic system at the lab, as an exemple of what we can do, as an ecosystem we can explore with, as a nice refreshing decorative and source of green for cooking or drinking.

How to start?
http://www.aquaponie.biz/fabriquer-un-super-kit-aquaponique-pour-moins-de-200e/

What I want to try first?
http://www.aquaponie.biz/fabriquer-siphon-cloche-automatique/
## How?

https://github.com/openfab-lab/openfab/blob/master/Gamification/Quests/testquest0001.md

**Comment by nicolasdb** [comment]
Cool, la fiche projet est initiée. 
Comment on fait pour savoir qui est chaud pour y participer?
(*L'exemple est valable aussi pour la Jacqueline*)

**Comment by nicolasdb** [comment]
je viens de recevoir un mail avec ça:
> Would you like to have an Aquaponics Kit in your Fab Lab ?
![_uglylr-qak8_h2or3xu02rc_tmiiexksyfo3ckuncolosimaz8qhvva5uhfevvadcto9zdu2edcvukpy8grnnlsjpztybnkdlrkkjdik8hgqa5dznsjmtcho6rm70td-rfka_bxkmwg2yk-zhq59ex4gpau-evinrif6vm s0-d-e1-ft](https://user-images.githubusercontent.com/12049360/27141613-f8a3a790-5128-11e7-80d3-a47b636864d2.gif)

**Comment by nicolasdb** [comment]
Massimo d'aquaponiebxl viendra nous voir jeudi pour discuter.  https://www.aquaponiebxl.be/
Je l'ai rencontré au fablab'ke où ils ont installé un système avec les gamins, je l'ai recroisé lors de la démo fablab velom² à StJoseph.

> C'est Massimo d'Aquaponiebxl, nous nous sommes rencontré la semaine passé à l’école de mes enfants et aussi au Fablab-Ke de Molenbeek.
> Qu'est-ce que t'en pense si on se rencontrait pour discuter d'une collaboration entre votre fablab et notre association?

(ha ben, va y en avoir du monde jeudi.... jacqueline, arduinoDjem, aquaponie,.... c'est cool)

**Comment by softrevolter** [comment]
Et bon pour discuter a propos du mobile fablab. Une utilisation en plus. Je voix qu ils font deja des trucs avec molenbike

_Sent from my HUAWEI M2-A01L using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolasdb** [comment]
Bien, hé ben c'est installé à l'entrée, 
Après achat du syphon à Aquaponiebxl. 
Les plantes pousses.
