### ISSUE TITLE
Organigrame et workflow gamification

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#36]
# FlowChart
## Contexte :
Recherche de fluidité dans les étapes de la gamification. 
Je trouve qu'on a actuellement fort tendance à attaquer des problèmes trop haut, ou trop ambitieux et c'est frustrant parce qu'on est confronté très rapidement à des questionnements non résolu. C'est frustrant.
## Objectifs :
Repartir de la base, de zero, des projets/tâches mono-mission, avec zero skill nécessaire, qui prennent pas de tps. 
Mais avant ça, repartir même de l'arrivée à Openfab et du processus logique d'inscription, mode superUser et la première mission. 
## Proposition :
J'aimerai proposer à qui veut participer, un moment de travail sur base de Twinery.org (logiciel d'écriture de scénario non linéraire, idéal pour les scénarios à choix multiple)
Ce serai une mise en situation (jeu de role) de l'arrivée d'une personne. 
1. tu veux faire par toi même? 
2. tu préfèrerai que quelqu'un le fasse pour toi? 
Puis suite logique des étapes. 
Est-ce que l'information est claire? Oui? Non? Est-ce que le contenu tuto existe? Oui? Non? Si non, alors quoi? -> issues
Step by step jusqu'au première mission. 
Je pense que ça donnera la structure logique pour 
1. vérifier si toute les questions sont couvertes et répondues. 
2. logique permettant d'identifier une nouvelle situation, -> itération.
3. Squelette logique pour les aventutoriaux
## Inspirations : 
Histoire à choix multiple écrite avec Twinery:
http://birdland.camp/
Et un aperçu de sa structure narrative, ouais, c'est un peu compliqué mais pas besoin d'aller jusque là :)
![screenshot 18](https://user-images.githubusercontent.com/12049360/27041334-fb6fb52c-4f93-11e7-9f25-6bbe615affd6.jpg)

**Comment by nicolasdb** [comment]
https://nicolasdb.github.io/Flow.html

Petit test de boucle sur twinery. 
On a subit un faux départ avec Paul mais j'ai compris pourquoi ça bugait. 
J'ai publié le scénario sur ma github-page pour tester. 
ça a l'air de fonctionner aussi 👍

**Comment by nicolasdb** [comment]
![screenshot 19](https://user-images.githubusercontent.com/12049360/27097676-453bcfe2-5075-11e7-9fb5-7aa29e3bc194.jpg)

**Comment by nicolasdb** [comment]
![screenshot 20](https://user-images.githubusercontent.com/12049360/27097698-5c7aea44-5075-11e7-803c-99f62b919fe9.jpg)

**Comment by zuperninja** [comment]
Du coup il nous faut une liste des tâches ? Avec les scénarios qui vont ensemble ? Puis une page qui rassemble toutes les questions ?

**Comment by nicolasdb** [comment]
J'ai fait un nouveau projet.
https://github.com/openfab-lab/openfab/projects/6

On y crée des colonnes, on y ajoute nos idées, on en crée des tâches et tout ça?

**Comment by softrevolter** [comment]
#85 résolut ceci aussi
