### ISSUE TITLE
Cleaning - Mais où on range 

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#38]
Fichier.md en cours d'édition sur:    
https://github.com/openfab-lab/openfab/blob/master/Task/Cleaning-buro274.md

## contexte
après avoir passé le coup d'aspi dans le buro, j'étais motivé pour passer un coup à l'eau et tout ça. 
mais le sceau est par là, la raclette est ailleurs et faisait même chier pour passer l'aspi. Où est le savon SolCarlus?
## objectif
Trouver une place bien identifiée avec tout le kit qui va bien pour nettoyer par terre. 
## proposition
En tout cas, tout réunir. 
Peut-être dans le couloir d'entrée mais je ne suis pas 100% convaincu. 
Je vais aussi aller chercher un torchon plus grand, il est trop petit, il ne tient pas bien sur la raclette et c'est une peine au cul de nettoyer.
Pareil, je vais en profiter pour mesurer le tps que ça prend pour nettoyer à l'eau. 
Attention que nettoyer à l'eau requiert la tâche aspirateur avant. Sinon, c'est encore plus chiant avec les moutons, les crasses dans l'eau et les fils et les bouts de découpe, les papiers, et les poils de tout ces barbus. 
## inspirations
![m propre-terrebattue](https://user-images.githubusercontent.com/12049360/27119720-4077f0d2-50e1-11e7-9094-e4f4abe52da7.jpg)  
Et Sol Carlus qui n'est pas jeté aux lions.  
https://youtu.be/oT3Mf0UI29A

**Comment by zuperninja** [comment]
Dans les toilettes ? :)

**Comment by nicolasdb** [comment]
non, trop petit. 

Xavier à vendu la moto, j'ai fait un coin dans le couloir de notre côté.
