### ISSUE TITLE
Couture - j'ai reçu de la pub 

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#39]
# contexte
L'aspect couture était porté par ma soeur Fabienne, et les soirées coutures remportait tjs son petit succès. 
Maintenant qu'elle est partie, on n'a plus que la grosse machine Pfaff et une petite dont je ne pense pas en tirer grand chose. 
Surtout il manque quelqu'un pour porter cette thématique, qqu'un qui s'y connaisse au moins un peu et qui a envie d'animer ça pour en apprendre plus aussi. 

J'ai reçu un mail avec ce lien.
https://coursdecouture.org/atelier-apprendre-machine-a-coudre/

Dans leur mail, il proposait aussi de les contacter si on voulais accueillir un cour. .. 
Peut-être un jour.

**Comment by nicolasdb** [comment]
Est-ce qu'on ferai pas un fichier avec une liste des opportunités?

**Comment by softrevolter** [comment]
est-ce que ce fichier opportunités à été crée?

**Comment by nicolasdb** [comment]
nope, pas encore

**Comment by nicolasdb** [comment]
vieux dossier. 
@DewiBrunet  avance sur une colab textile avec Macocoi
