### ISSUE TITLE
Mieux connaitre la communauté

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#41]
fichier.md :  
https://github.com/openfab-lab/openfab/blob/master/Community/v1-mieux-compr-comm.md

# Issue
## contexte
Depuis quelques jours, j'essaye de me mettre dans la peau d'un nouvel arrivant chez OpenFab, j'essaye d'imaginer les questions qu'il peut se poser, comment il en arrive jusqu'au FabLab. Mais nous avons plu de 100 inscrits, autant leur demander directement.

## objectif
L'objectif est de mieux connaitre la communauté, connaitre les questions qu'elle a pu se poser en arrivant. C'est peut-être l'occasion de faire un "gros" sondage pour en savoir plus sur les impressions du moment, leurs envies (machines, formations, ...) ?

## proposition
Réalisation d'un sondage (via typeform). Il faut vérifier donc comment faire un sondage pertinent, je vais essayer de retrouver mes vieux cours et/ou voir ce que je trouve sur le net.

"Cours" qu'on m'a partagé : [User research, quick and dirty](https://library.gv.com/user-research-quick-and-dirty-1fcfa54c91c4)

## inspirations
_[Sondage](https://docs.google.com/forms/d/e/1FAIpQLSd5qQK8B2HAMIt4f_5b47O876vOgeZEGui6tkFGWcb76ZjDjg/viewform?c=0&w=1) réalisé pour une communauté WordPress, comprendre leur utilisation de l'outil, pourquoi, ... Le [pourquoi du comment](https://wpfr.net/grand-sondage-mieux-connaitre-communaute/) de ce sondage
_On est dans l'esprit Design Thinking et la phase "d'empathie".
_Coconstruction
_UX

# Travail
Voici le [sondage](https://malo13.typeform.com/to/k36rdb)
Voici la [documentation complète](https://github.com/openfab-lab/openfab/blob/master/Community/v1-mieux-compr-comm.md)

**Comment by Ginsburg** [comment]
fix #41

**Comment by softrevolter** [comment]
@Ginsburg et @nicolasdb est-ce que tu pense que le document qui est maintenant en community pourrais pas être construit dans une missions sous Tasks
Donc dans l'idée d'avoir aussi dans cette structure: 

**Préparation**
Contexte
Objectif
Proposition
Inspiration 
Participation

**Protocol**
Dorée
Skills
Resource
Remarque
Résultat -> mettre ici le résultat

Comme ça tous ça devient une mission et peu être refaite plusieurs fois?

**Comment by softrevolter** [comment]
je met la question ici, car si je le fait, personne verra le changement, donc c'est avant qu'on met en place la méthodo pull request

**Comment by Ginsburg** [comment]
On avait abordé l'idée la dernière fois, ça me va bien. J'aurai peut-être un soucis sur le protocole car la V2 aura sûrement pour objectif de réinventer le protocole, du moins de le dépasser très largement car la V1 n'est pas satisfaisante.

Mon envie par le dossier community est de rassembler toutes les informations sur les membres, sur notre compréhension de la communauté, les résultats de sondages, ... (si c'est pertinent ?). Mais peut-être ne faut-il pas séparer le processus (tâche) des résultats et juste tout mettre dans task.

Enfin, ce sont peut-être trop de questions alors qu'un bon "quick&dirty" fera le travail.

**Comment by Ginsburg** [comment]
Une espèce d'issue dans l'issue

## contexte
En passant #41 en task, j'ai eu pas mal de difficultés à faire rentrer tout ça dans la structure, notamment de la partie Protocole, surtout que la V1 n'est pas satisfaisante et je n'ai pas envie d'encrer un protocole qui est faible. La v2 passera par une réinvention de ce protocole.

## objectif
Faire rentrer #41 dans la bonne case.

## propositions
_Soit avoir une structure "task" plus adaptée.
_Soit avoir une structure "task" plus flexible.
_Soit faire apparaitre une nouvelle notion dans notre glossaire : le sondage est un outil perfectible, utilisable à l'avenir pour "Mieux comprendre la communauté" (tâche) le sondage créé, est un outil (utilisable si on le veut) et pas une tâche --> créer un dossier pour réunir les différents outils ou créer un dossier backoffice pour réunir tout ce qui concerne le sujet.
_Soit créer des statuts de tâche différent :  
- tâches récurrentes, vouées à rester les même, plus ou moins. ex : laver l'atelier.  
- tâches "évolutives", changeantes en fonction de la situation. ex : [mieux comprendre la communauté](https://github.com/openfab-lab/openfab/blob/master/Task/empathy-users.md)   

_Soit un mélange de tout ça.
