### ISSUE TITLE
Mobilier buro274 - Maker Library

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#42]
## contexte
Un mec est passé hier, il bosse dans l'édition de bouquin libre ou en tout cas, il est branché libre. 

(OMG, un **libr**aire! CQFD) 
![9701620](https://user-images.githubusercontent.com/12049360/27320342-181d3750-5596-11e7-91f4-3f9d67bb87b0.jpg)

Bref, Il est accompagné par nos copains de chez VP, il passe aussi par Atrium il cherche un lieu de 200m² et bosse donc pour ouvrir quelque chose comme une "MakerLibrary", 
Pour le consommateur, c'est un lieu où tu peux pécho des bouquins mais d'une nouvelle manière. Quelques livres papiers bien sur mais aussi accès aux livres numériques (epub, kindle, pdf, etc...) et pouvoir les imprimer sur place et pourquoi pas faire des ateliers reliure etc... 
Du côté maker, c'est un lieu où tu peux trouver toute l'aide pour écrire et éditer à petit tirage tes poèmes, ta fan fiction voir pourquoi pas un super concept d'aventutoriel : )

Il m'a fait découvrir ceci:
http://design.britishcouncil.org/projects/makerlibraries/
> The Maker Library Network was a British Council project that connected designers and makers around the world. It facilitated knowledge and skills exchange amongst professionals and encouraged public engagement with making. 
> A Maker Library combines three elements of a makespace, a library and a gallery. These spaces are connected online and through a programme of travel exchanges, exhibitions and events. People use them to make things, show things, get inspired and connect with like-minded people.  
![slide1 jpg 580x386_q85](https://user-images.githubusercontent.com/12049360/27320750-da315be0-5597-11e7-8840-2680aeb4f781.jpg)

Site où ils partagent les designs en opensource bien sur. 
http://design.britishcouncil.org/projects/makerlibraries/resources/

## objectif
Il n'y connait rien en menuiserie mais aimerai trouver de l'aide pour la construction de l'aménagement intérieur de son shop. 
Moi, voyant ça, ça me plairait de tester ces designs pour continuer et améliorer l'aménagement du buro274. 
De plus, ça me fait penser à ce qu'on met doucement en place avec les espaces scolaires. On pourrait s'inspirer du format, voir mixer un peu les 2 mondes. Enfants et bouquins, ça va bien ensemble en fait. :)

## proposition
J'aimerai lancer une mission à ce sujet, juste pour tester avec un meuble (stabilité, faisabilité, solidité). 
J'aimerai modéliser en 3D dans fusion les plans, pour pouvoir automatiser les dimensions hauteur, longueur, largeur en fonction aussi des sections de bois qu'on trouvera chez les fournisseurs ou pourquoi pas sur base de récup. C'est que des sections carrées 33*33mm, je pense que ça peut facilement se trouver en fin de chantier (même des petits chantier) ça s'utilise pour faire les structures (murs, parois, rénovation) avant de mettre du placo
Voir comment facilité la prod avec un ou deux gabarit et la défonceuse.
Et le mec après, aura 200m² à aménager. Je pense que ça peut être un bon partenaire (il connait Michel qui lui a déjà proposé de faire un speech lorsqu'il ouvrira!)

## inspirations
Il m'a laissé un bouquin sur le sujet. 
Aussi, j'ai déjà imprimé le pdf de ceci
http://design.britishcouncil.org/projects/makerlibraries/resources/maker-library-shelving-open-design-kit/
![img_4658 jpg 940x528_q85_upscale](https://user-images.githubusercontent.com/12049360/27321136-630b1edc-5599-11e7-8825-9b101c7f62cd.jpg)

Mais j'irai peut-être plus sur cette idée là, une évolution sur roulette, pour rester modulaire dans l'atelier.
http://design.britishcouncil.org/projects/makerlibraries/resources/atolye-istanbul-hack-mln-shelving-kit/
![maker_library_screenshot7-crop png 280x280_q85_crop_upscale](https://user-images.githubusercontent.com/12049360/27321004-f3286386-5598-11e7-89db-91c4c3db6638.png)
![image](https://user-images.githubusercontent.com/12049360/27321027-0e579424-5599-11e7-8e31-5de45cf18719.png)

**Comment by nicolasdb** [comment]
tiens, je vais tester de pré-écrire le .md ici. 
L'ajout des photos et l'édition y est plus simple. 

# MakerLib - test production
ref to file.md or #issue : #42
## Contexte
Suite à la visite de Vincent Demuliere qui cherche à ouvrir une librairie en mode maker et opensource via le concept de [maker librairies](http://design.britishcouncil.org/projects/makerlibraries/)
ça ma donné bien envie d'essayer.
## objectif
Ils nous manquent tjs pas mal de mobilier pratique pour ranger, afficher, présenter clairement où sont les tools, les consommables, les projets en cours, ce qu'on peut acheter et à quel prix.
J'aimerai tester ce système pour le Buro274.
Les avantages sont multiple: 
- c'est modulable, 
- c'est pas cher (uniquement vis, colle et bois en section carrée 3cm)
- c'est réalisable sans machine numérique, 
- s'assemble n'importe où,
- c'est léger.
## Proposition
- [x] Je vais modéliser une box selon le pdf fournis
- [x] tester sur un petit modèle. basé sur une petite cagette plastique bleu (400x295x200mm)
- [x] acheter du bois chez Brico (7.78€)
- [x] Découpe en longueur ad-hoc
- [x] ~~Tenon à la scie radiale ~~ nope,bad idea
- [x] Tenon à la défonceuse (mèche 8mm)
- [x] assemblage à la colle + vis 
### Ressources
#### Bois: 
- [Gedebois](http://www.gedebois.be/catalogue-2017/bois/sapin-rabote.html): section rabotée 27x27mm = 1.95€/m, 35x35mm = 2.60€/m
- Brico: section rabotée 34x34mm = 3,89€/1.8m
#### software
Fusion360
## Résultats
![screenshot 28](https://user-images.githubusercontent.com/12049360/27784836-e394a3a6-5fdb-11e7-9873-bc405016bf94.jpg)

[Le modèle](http://a360.co/2sDIXWT) est paramétrique et peut être facilement modifié pour
  - hauteur x longueur x largueur 
  - section bois  

Ce qui donne plus facilement une idée précise des longueurs bois nécessaire. Reste à faire un plan de découpe en fonction des longueurs disponibles au shop.  
**Durée: 2h**

![img_20170702_145003_800_600](https://user-images.githubusercontent.com/12049360/27784782-a7e08668-5fdb-11e7-928a-002a1971500b.jpg)

[Production et assemblage proto01]()
**Durée: 3h**  
Ouais, j'ai un peu galéré, c'est le premier... 
### Rewards
Je vais passer ce projet en mission et si ça fonctionne bien, que j'arrive à automatiser et faciliter la production avec des gabarits malin:
- J'aimerai valider mes badges (nécessite encore un processus et des logos. Voir plus en détail openbadge)
  - [ ] Fusion360 - "habile"
  - [ ] 3Dprint - "habile"
  - [ ] Défonceuse - "bon"
  - [ ] Astuce - "habile"
  - [ ] Foreuse - "habile"
  - [ ] Visseuse - "habile"
- Je serai super content de pouvoir résoudre un problème de plus dans l'amélioration du buro274. **= 2dèbières**
- Et j'aimerai ajouter cette solution au catalogue avec la capacité à sa réalisation.

**Comment by nicolasdb** [comment]
# MakerLib - test production
ref to file.md or #issue : #42
## Objectif
- [x] Je vais modéliser une box selon le pdf fournis
- [x] tester sur un petit modèle. basé sur une petite cagette plastique bleu (400x295x200mm)
- [x] acheter du bois chez Brico (7.78€)
- [x] Découpe en longueur ad-hoc
J'ai testé à la scie à main à onglet, le résultat n'est terrible, c'est pas très clean. Si possible, préférer la scie radial électrique.
- [x] ~~Tenon à la scie radiale ~~ nope, bad idea!
![img_20170702_120057_800_600](https://user-images.githubusercontent.com/12049360/27786267-c5f6ca22-5fe0-11e7-8d49-d5d0c006f3d1.jpg)
Par contre, j'ai tenté de faire les tenons à la scie radiale aussi. Il y a un arrêt réglable pour ne pas couper plus profond qu'un certain niveau mais l'ensemble est trop lourd et trop souple. Le niveau n'est pas respecté et change de trop en fonction de la force qu'on applique sur la machine.
- [x] Tenon à la défonceuse (mèche 8mm)
![img_20170702_122347_800_600](https://user-images.githubusercontent.com/12049360/27786384-356acffc-5fe1-11e7-83cf-dd89c6cceef2.jpg)
Mesure de l'écart max pour creuser une battée de (dans ce cas 17mm).   
Demi largueur de la défonceuse (55mm) - rayon de la mèche (4mm)= 51mm.
+ Éloignement du bord de 17mm = 68mm
J'utilise une languette que j'ai trouvé pour graduellement enlever la matière. Environ 6mm à la fois jusqu'au 17mm.
 ![img_20170702_122520_800_519](https://user-images.githubusercontent.com/12049360/27786912-53b39b18-5fe3-11e7-95a2-083dfbad4b90.jpg)
Fuuuuuuuuu.... Attention à la fin de la défonce. 
![img_20170702_124007_800_600](https://user-images.githubusercontent.com/12049360/27786949-73e55336-5fe3-11e7-92c0-b04001ea1548.jpg)
Comme ça c'est mieux.

![img_20170702_130517_800_600](https://user-images.githubusercontent.com/12049360/27786969-8760e646-5fe3-11e7-8c46-c2848cfcde1d.jpg)
J'ai du coup, découpé deux guides selon les dimensions calculée plus haut. 
L'un à 68mm et l'autre à 85.

![img_20170702_122309_800_600](https://user-images.githubusercontent.com/12049360/27787011-afa6b3ec-5fe3-11e7-887b-83daed3062a4.jpg)
J'aligne et je garde en place avec les pinces le temps de placer le guide avec les serre-joint.

![img_20170702_124004_800_600](https://user-images.githubusercontent.com/12049360/27787120-180a1f3c-5fe4-11e7-87eb-c30c6a3bbcf6.jpg)
Nice!

- [x] assemblage à la colle + vis 

![img_20170702_141811_800_600](https://user-images.githubusercontent.com/12049360/27787154-30ecd49a-5fe4-11e7-9ebe-7d79905a19af.jpg)
Pour l'assemblage, je pré fore les éléments suivant le type de vis. Ici, j'ai du trou de 2.5mm et en entrée j'ai fait du 3.5 pour laisser passer la vis.   
Idéalement, il faudrait des vis non filetée jusqu'au bout (oublié le nom, quelque chose comme ça) pour bien serrer à la fin.
![9279337005086](https://user-images.githubusercontent.com/12049360/27787405-ecf8ab96-5fe4-11e7-942f-d35345066737.jpg)

![img_20170702_142508_800_600](https://user-images.githubusercontent.com/12049360/27787478-2aa42254-5fe5-11e7-8326-27fe69dcb35c.jpg)
il y a moyen de trouver une routine ici. D'abord les éléments de hauteur puis on reporte les trous sur longueur et largeur, on encolle et on visse. 
![img_20170702_141452_800_600](https://user-images.githubusercontent.com/12049360/27787531-558ca3b0-5fe5-11e7-8ac8-6cff6fdd546a.jpg)

Zoupla.
![img_20170702_145003_800_600](https://user-images.githubusercontent.com/12049360/27787533-59b73716-5fe5-11e7-8b3d-8a067397e683.jpg)

**Comment by nicolasdb** [comment]
https://github.com/openfab-lab/openfab/blob/master/Gamification/Missions/maker-library.md

this close this test

**Comment by zuperninja** [comment]
Je cherche le fichier pour faire les petites boites de rangement à la découpeuse laser. C'est par où ?

**Comment by nicolasdb** [comment]
Sur le NAS, ...\000WORK\3 teams\Openfab.lab\R&D\boxes rangement lasercut
