### ISSUE TITLE
Présentoir à semences - Minga Paname

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#45]
Le fichier.md est en cours de rédaction ici:  
https://github.com/openfab-lab/openfab/blob/master/Minga.md
## contexte
Minga est un de nos partenaires CHIC2.0

> Nous souhaiterions te solliciter à propos d'un projet de conception, lié à la campagne des "Graines d'un Paris d'avenir" que nous sommes entrain d'organiser pour promouvoir le métier d'artisan-semencier.
> Nous lançons pour l'occasion une collection de graines destinée à être diffusée dans une 50aine de commerces, restaurants, bistrots, librairies... partenaires de l'opération, et nous aurions besoin d'un présentoir à graines.
> **Il s'agirait de concevoir et fabriquer 60 présentoirs (pour contenir 50 sachets de graines + 10 livrets qui présentent la collection) pour le 15 septembre (ou au moins une partie, pour commencer à les distribuer).**
> Nous n'arrivons pas à trouver un "standard" qui nous convienne et de toute façon, j'avoue que depuis notre visite à Bruxelles, on préférerait nettement faire appel à ton ingéniosité. Sans compter que ce travail pourrait aussi être présenté dans le cadre de CHIC, et bien illustrer le propos. On est typiquement face à un besoin de production d'un objet en petite série, en phase avec de nouveaux besoins et usages...
> Est-ce que tu crois que ça pourrait t'intéresser ? Et si oui, nous **proposer un devis** ?
> Tu trouveras ci-joint une présentation de la campagne, avec l'affiche qui va accompagner ces présentoirs dans les points de vente et inspirer les autres visuels (du dossier de presse, du livret...). Ainsi qu'une tentative de cahier des charges, à discuter... tout reste ouvert !
> Si le côté "fabrication/reproduction" du présentoir ne te semble pas réalisable à l'Openfab, on peut aussi imaginer de créer juste un prototype (si tant est qu'on puisse tout de même le fabriquer ici dans les délais...).

## objectif
- Design d'un présentoir à semence et production de 60pcs pour le 15sept.
- Proposer un devis.

## proposition
Je propose de m'en occuper tout en testant le processus github, de mission, de fiche projet, etc...
## inspirations

**Comment by nicolasdb** [comment]
![aaa226159cf15018930956d78ae63c01](https://user-images.githubusercontent.com/12049360/27438860-c36a439c-5766-11e7-8cfc-8a4e16d0c414.jpg)
![image](https://user-images.githubusercontent.com/12049360/27438899-da7b1db8-5766-11e7-9ad3-88f2973fd348.png)
![71034c5dbe4e4d4d8aa417e06c559658](https://user-images.githubusercontent.com/12049360/27438962-f421f7b4-5766-11e7-988c-6bdc93d06a2c.jpg)
![8b2a273fa5d0fc5af3836db8e3949d41](https://user-images.githubusercontent.com/12049360/27438992-079d16de-5767-11e7-98d0-e5d6dcc99b92.jpg)

**Comment by zuperninja** [comment]
Ils sont comment leur sachet de graines ? A la grainothèque de mon patelin ils ont fait un meuble avec plein de petits tiroirs et réglettes pour contenir ce type là de sachet : 

[http://www.sandrawillauer.com/portfolio-item/sachet-graines/](![image](https://user-images.githubusercontent.com/25099826/27443111-6ac34d7c-5772-11e7-9505-4c9393761678.png))

**Comment by softrevolter** [comment]
j'ai crée le fichier .md donc je ferme ici

voici le lien: https://github.com/openfab-lab/openfab/blob/master/Task/creation-devit.md

**Comment by nicolasdb** [comment]
Objet : Ré-inventer un présentoir à graines.
Concevoir et fabriquer 60 présentoirs à livrer à partir du 15 septembre 2017
Données techniques :
1/ Contenu des présentoirs :
• 50 sachets de graines / format : 85 mm x 145 mm
◦ 12 variétés différentes issues du patrimoine agricole parisien
◦ + 1 variété d'origine plus lointaine (le piment boule de Turquie, pour l'Europe !)
• 10 "livrets de campagne" / format : 105 x 150 mm (30 pages max)
•
2/ Forme des présentoirs :
Ces présentoirs sont destinés à être posés sur une table ou sur un comptoir, près des caisses ou à
l'acceuil de différents types de commerces (épiceries, restaurants, bars à boire et à manger,
librairies, étals de marché...).
Vu leur usage et destination, ils doivent :
- être livrés à plat, à déplier/monter soi-même, sur le lieu de distribution,
- être solides et stables une fois montés (pour que les gens puissent aisément choisir leur graines),
- ne pas prendre trop de surface d’encombrement (jouer plutôt sur la hauteur ?)
- montrer de suite qu'il y a le choix entre différentes variétés de semences (pévoir au moins 3
compartiments/rangées de sachets ? et/ou un système sur plusieurs niveaux/étages ? ...)
- prévoir un endroit où écrire "Les Graines d'un Paris d'avenir" (imprimé ? gravé ?..)
- rappeler le visuel de l'affiche, soit par la forme, soit par la couleur du materiau... soit en prevoyant que
toute la surface soit imprimable (le graphiste peut concevoir une déclinaison de l'affiche d'après un
gabarit)...
3/ Matériau des présentoirs :
Plutôt léger et rigide (solide, donc) : carton ? autre ? ...
Globalement tout se discute !
Nous souhaiterions juste des présentoirs plutôt élégants, sobres et pratiques.
Aisément reproductibles.
