### ISSUE TITLE
Hohoooo reste plus que 5 Maes. 

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#46]
=> Fichier MD:  https://github.com/openfab-lab/openfab/blob/master/Gamification/Missions/Mission%20BackOffice:%20Bi%C3%A8res%20ou%20es-tu%3F.md

Alerte

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by softrevolter** [comment]
j'essaye de tester la boucle, sans la solution, donc je fait un  #commit 

_Sent from my HUAWEI M2-A01L using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by softrevolter** [comment]
Fichier MD crée, maintenant il faut trouver quelquun qui est chaud pour le test
Prix atribué: 1D Bières: gagne 0,1,2,3 bières_

**Comment by nicolasdb** [comment]
tu t'es assigné, t'es chaud? 
ha, question donc. 
Comment assigne t'on une personne à la tâche? 
Je propose de créer une note dans le projet gestion dans TODO. 
Je vais le faire parce qu'à tout les coups, c'est moi demain matin qui vais aller.

**Comment by nicolasdb** [comment]
il est où le 1desbières? Est-ce qu'il se joue aussi au Lancédédé?
:D

**Comment by nicolasdb** [comment]
J'ai mis à jour le fichier.md et j'ai créé une tache d'aller chercher. 
Attention avec les noms de fichier avec espace et caractères spéciaux, ça fait des adresses web à la con.

Ceci fix pour l'instant cette issue.
