### ISSUE TITLE
Où je peux mettre mes CRRR

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#47]
bon,

on doit commencer à créer un endroit ou on peut repertorier les CRRR, je sais que tu peux les mettres sor ton passport maker, mais vu que j'en ai pas et je suis plus sur github qu'au OpenFab, que fait on ? 

On sait déjà ceci pour le WIKI

ecrire une issue: 1 CRRR
créer un .md avec Titre / Context / Objectif / Inspiration /Proposition: 5 CRRR

Donc quand j'aurais crée le .md pour la mission bière, j'aurais 6 CRRR

**Comment by nicolasdb** [comment]
yes,
j'y pense aussi. 

actuellement, il y a 
- le passeport, feuille crédits  
- les cartes Dx, carte magic modifiée. (contrainte, c'est sur place, avantage, c'est sur place... ^^ )
- .... est-ce qu'on n'aurait pas un endroit, un fichier à se créer à la racine de son compte github pour y relever l'état de son portefeuille? Quid de la transparence? c'est aussi un peu le but. 
Chaque modification donc chaque transaction se retrouve versionnée. (blockchain)

**Comment by zuperninja** [comment]
J'aime bien le fichier à la racine du compte github. Ca fait une application de plus pour prendre en main github à l'arrivée d'un nouveau membre. 
Un autre membre peut faire un pull request aussi pour lui ajouter ou enlever des CRRR.

**Comment by nicolasdb** [comment]
J'ai créé des cartes 1Desbières :)
https://github.com/openfab-lab/openfab/blob/master/Gamification/ValueCard.md#carte-1desbi%C3%A8res

**Comment by nicolasdb** [comment]
J'ai changé le status parce qu'en fait, ça reste une question constante. 
Faut la mettre en oeuvre.

**Comment by nicolasdb** [comment]
haha, voilà mon nouveau compte openfab
https://github.com/nicolasdb/crrr/blob/master/README.md

**Comment by softrevolter** [comment]
J 	ime bien la fiche. Mais comment ca marche en pratique?

_Sent from my HUAWEI M2-A01L using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolasdb** [comment]
Je sais pas encore :) 
Qui a des crédits? 

Je pense qu'on pourra l'utiliser comme un compte en banque. 
Quelqu'un peut y ajouter ou prélever (= virement) des crrr sur base d'un pull request documenté (= communication) qui sera validé par le propriétaire et toute l'info sur les opérations sera versionnée donc enregistrée. (= extrait de compte)

C'est plus simple de tester le repo Crrr (ou peut-être le renommer WalletCrrr ou Crrwallet .... Idonknow) que de tester avec un fork du repo passeport.

**Comment by nicolasdb** [comment]
**EVOLUTION/**
je suis passé de Crrr à Lootcrate, pour loger tout mon loot!

J'ai plein de carte D et j'ai oublié en échange de quoi. 
J'ai maintenant mon coffre où je peux stocker mon butin et ne plus oublier. 

https://github.com/nicolasdb/lootcrate

**Comment by softrevolter** [comment]
ok est-ce qu'il y a un loocrate template quelque part?

**Comment by nicolasdb** [comment]
non, pas encore, j'ai juste testé quelque chose chez moi. 
on peut en faire un si ça plait comme structure

**Comment by nicolasdb** [comment]
https://github.com/nicolasdb/lootcrate

j'avance sur l'usage.
je pense que ça pourrait bientôt faire l'object d'un template.

Faudrait peut-être encore un peu jouer sur la mise en page, j'suis pas encore convaincu.

**Comment by softrevolter** [comment]
c'est la partie badge qu'on va devoir améliorer je pense, le reste c'est bien

**Comment by nicolasdb** [comment]
en lien avec #20 

J'ai avancé sur mon lootcrate
https://github.com/nicolasdb/lootcrate/blob/master/README.md

Je dois bientôt pouvoir arriver à une forme de template facile à éditer.

**Comment by nicolasdb** [comment]
J'aimerai maintenant l'ajouter en tant que page sur mon site github. 
La question est de voir aussi avec le tps comment standardiser ça et faire le lien avec le badge numérique rfid et le check de permission en ligne lorsque le badge est scanné.
