### ISSUE TITLE
Création d'une guilde à OpenFab

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#55]
pour rester dans la thématique du jeu, je me demandais ce que ça couterais de créer une guilde chez OpenFab. 
Pour exemple: Vélo M2 recherche un endroit pour faire ces discovery days une fois par mois et de lancer des quests à la communauté + si tout marche bien avec Jacqueline ça serait intéressant de regrouper les ressources local. 
Ce que Vélo M2 peut apporter: 

une imprimante 3D, un projecteur, une sono, un vélo cargo, 2 module énergétique. 

Ce que vélo m2 a besoin

Parfois des machines pendant les discovery days, un endroit pour reunonier et des gens pour participer au quests. 

Qui peut m'aider a créer un appel à offre pour ceci?

**Comment by nicolasdb** [comment]
J'suis chaud :)
**Mais!** suite à ce que je viens de lire ici https://opensource.guide/how-to-contribute/#opening-an-issue
Je propose de tester le développement et la résolution de cette issue au travers des "pull requests". l'onglet à droite des "Issues"

**Comment by nicolasdb** [comment]
bon en fait, c'est super chiant leur tuto

**Comment by nicolasdb** [comment]
Est-ce que les guildes ne créerait pas un compte "organisation" sur github. 
Comme pour Openfab. 

ça donnerait aussi une cohésion logique à l'ensemble. 
Et je pense qu'il faudra arriver à un logo à afficher tel "intel inside" mais avec "powered by Openfab" ou "gamified by OF" je sais pas trop.
Mais il sera cool d'avoir un lien visuel entre les guildes.

**Comment by nicolasdb** [comment]
On en est où niveau Guilde. 

On réunit les idées quelques parts?

**Comment by nicolasdb** [comment]
J'ai créé une branche et un fichier .md spécifique. 
https://github.com/openfab-lab/openfab/blob/guildOF/_space/guildes-openfab.md
Dont voici le PR (pull request) pour en discuter et y travailler ensemble. 
https://github.com/openfab-lab/openfab/pull/108

issue à clore. 
+1 crrr @softrevolter 
+5 crrr @nicolasdb

**Comment by zuperninja** [comment]
![image](https://user-images.githubusercontent.com/25099826/29308830-84dac672-81a7-11e7-8d67-dced5196f591.png)
On avait fait ça pour la cuman

**Comment by nicolasdb** [comment]
c'est vrai > mais on ne parle encore que des guildes, pas de coop. Une fois que ça roule avec des guildes, on aura une meilleure XP pour passer en coop.
ça ce discute ici >>>>> PR #108

**Comment by nicolasdb** [comment]
Est-ce que on peut concidéré que le fichier.md est créé via le pull request démaré? 

issue à clore.
+1 crrr @softrevolter
+5 crrr @nicolasdb

**Comment by nicolasdb** [comment]
très vieux dossier. On a une proposition plus avancée ici. 
https://github.com/openfab-lab/openfab/blob/master/_space/guildes-openfab.md
