### ISSUE TITLE
Structuration du wiki

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#56]
ref: https://github.com/openfab-lab/openfab/blob/master/structure-wiki.md

## contexte
Parfois dur de savoir pour où commencer quand on s'attaque au github, à la gamification, ... Je me dis que la mise en place du Wiki peut être un bon fil à tirer, sa structure, les sous-parties peuvent devenir des tiroirs de sujets à traiter les uns après les autres.

@nicolasdb & @softrevolter : Ça peut également servir dans vos réflexions de jeudi pour retracer le parcours d'un nouvel arrivant.

## objectif
Avancer vers une première ossature du wiki pour déterminer ce qui doit être fait

## proposition
"Quick & Dirty" comme toujours, voir ce qui se fait ailleurs et copier/adapter. Sûrement tester plusieurs ossatures sur papier et voir laquelle mettre en place par la suite.

## inspirations
_[Projects with great wikis](https://github.com/showcases/projects-with-great-wikis)
Quelques wikis sympas avec un beau travail sur la Home Page pour certains avec une partie "Quick Navigation" comme ici : [lettuce](https://github.com/lettuce-io/lettuce-core/wiki)

_[Wikipedia](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal), ça reste le wiki le plus visité, tout n'est pas bon à prendre mais on voit vite 3 points intéressants : 
-Présentation
-Règles
-Comment contribuer ?

Sinon on voit aussi, plus discrètement, mais lien vers "Principes Fondateurs", "Wikipedia en bref"

**Comment by Ginsburg** [comment]
J'ai fait quelques tests assez désorganisés de la structure d'un futur wiki mais j'ai l'impression que ça ne marche pas et me bloque dans mon avancée : https://github.com/openfab-lab/openfab/blob/Ginsburg-structure-wiki/structure-wiki.md

Peut-être, faudrait-il une homepage très simplifiée, qui résume un peu tout ça + une navigation rapide (table des matières) comme j'ai commencé à le faire en test sur un repo de test : https://github.com/Ginsburg/malo/wiki

Qu'en pensez-vous ?

**Comment by nicolasdb** [comment]
ha ben voilà, c'est super :)

non mais, j'aime bien l'idée de garder la même boucle de fiche (context, observation, proposition, résultat). 
Pour le site, faut pas oublier le principe d'arborescence. 

On peut se contenter de
- [context] (cliquable/lien)
   - une image
   - une phrase 
- [observation] (cliquable/lien)
   - une image
   - une phrase 
- [proposition] (cliquable/lien)
   - une image
   - une phrase 
- [illustration] (cliquable/lien)
   - des images - plus de visuels
   - résumés très court et toujours liens vers minisite (par exemple)

**Comment by nicolasdb** [comment]
on abandonne le wiki, redirection vers le repo RTFM et une publication avec gitbook
