### ISSUE TITLE
Choix de la licence

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#57]
Ref : https://github.com/openfab-lab/openfab/blob/Ginsburg-choix-licence/choix-licence.md

## contexte
En lien avec #52 et le guide https://opensource.guide/, il est recommandé (fortement) de trouver une licence pour OpenFab.

## objectif
Pour être opensource, il faut une licence : "By definition, every open source project must have an open source license. If the project does not have a license, it is not open source."

## proposition
S'appuyer sur le [guide](https://opensource.guide/), s'appuyer sur [choosealicense.com](https://choosealicense.com/), regarder quels sont le choix d'autres organisations.

## inspiration
_Licence utilisée par Sensorica d'après leur site : [Creative Commons Attribution-ShareAlike 3.0 Unported License](https://creativecommons.org/licenses/by-sa/3.0/) : CC BY-SA 3.0
_Licence actuellement mise en avant sur openfab.fr : [Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) : CC BY-NC-SA 4.0

**Comment by Ginsburg** [comment]
Qu'en pensez-vous ? On prend laquelle ?

Perso j'utilise la **CC-BY-4.0** pour mes articles Medium.
La seule condition est de nommer l'auteur du taf, possibilité de l'adapter, en faire une utilisation commerciale, un peu de tout finalement.

**Comment by nicolasdb** [comment]
Perso, je me pose des questions sur l'aspect commercial ou pas. Après l'annonce de Transforma, ça me ferai quand même chier que quelqu'un de plus rapide, plus friqué et surtout plus opportuniste vende le truc ailleurs, se fasse bien voir et puis grille le concept parce qu'il n'avait rien compris en fait. 

J'aime bien l'idée qu'il existe des licences de type copy-far-left où l'usage commercial n'est pas tout noir ou tout blanc aussi. c'est ok pour une structure qui apporte au commun, mais royalties si pas d'apport au commun. 

après, je ne m'y connais pas bien dans les détails.
y a pas un doc "les licences libres pour les noobs"

**Comment by Ginsburg** [comment]
C'est vrai que j'intégrais assez peu la dimension commerciale dans ma réflexion, je vais creuser plus en gardant ça en tête.

On dirait que ça existe : [Creative Commons pour les nuls](http://davidlatapie.blogspot.fr/2012/08/creative-commons-pour-les-nuls.html) Bon ok, ce ne sont que les CC.

**Comment by nicolasdb** [comment]
Vous avez vu, y a un moyen d'inscrire le CC dans une blockchain 
http://creativecommons.fr/ascribe/comprendre/

**Comment by Ginsburg** [comment]
Il y a un petit "simulateur" sur le site de CC aussi : https://creativecommons.org/choose/
Sachant que le fait de laisser l'utilisation commerciale fait basculer la licence de : 
"Ceci n'est pas une licence "Free Culture""
à "C'est une Licence "Free Culture""

La Free Culture est définie ici : https://creativecommons.org/share-your-work/public-domain/freeworks

Si on veut limiter l'utilisation commercial + share alike, on arrive là-dessus : https://creativecommons.org/licenses/by-nc-sa/4.0/ (justement non "free culture", est-ce un problème ?)

Après, il y a pas que les CC mais j'arrive pas à appréhender les autres licences, le système a l'air plus complexe.

**Comment by nicolasdb** [comment]
Qu'est-ce que vous pensez de CC-BY-SA? 
le BY est évident mais j'aime l'idée de quand même contraindre les autres qui s'en inspire ou qui vont remixer de devoir continuer en CC-BY-SA aussi. 
De plus, on s'aligne à Sensorica. Et ils ont certainement plus d'expérience que nous à ce sujet.

**Comment by softrevolter** [comment]
CC-BY-SA est aussi ce que on utilise à Vélo M2. 
Moi je suis pour

**Comment by Ginsburg** [comment]
J'aime bien cette licence aussi, j'ai pas intégré toutes les options, notamment les GNU mais celle-ci semble assez pertinente.

Oui, on devrait pouvoir afficher le label "free culture" cette fois.

**Comment by nicolasdb** [comment]
ok, je passe le repo en CC-By-SA.

Zoupzoup

**Comment by nicolasdb** [comment]
Done
