### ISSUE TITLE
mise en forme - syntaxe markdown

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#6]
openfab/events/BrainCandy.markdown 

@softrevolter 
If you want to create some "return to next ligne",   
markdown permet de le signaler par l'ajout d'un minimum de 2 espaces en fin de ligne.   
Sans ça il prend ton texte comme un paragraphe entier sans retour à la ligne.

**Comment by softrevolter** [comment]
thanks, tu vois je commence aussi a comprendre les issues
