### ISSUE TITLE
Bibliotheque en open design

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#63]
# Bibliotheque en open design
ref to file.md or #issue :
## contexte

Mission construction pour la communauté. 
Je suis en train de chercher des plans et de l'aide a construction pour un meuble de bibliotheque simple à réaliser et coût matériel vers les 400 euros. 2m30 sur 4m50

Si quelqu'un est chaud pour m'aider je met 12DBières à disposition :) 

ça devrais contenir ceci: https://www.facebook.com/photo.php?fbid=10159034347495249&set=a.238912695248.280541.699115248&type=3&theater

J'avais essayé ceci: https://www.ronen-kadushin.com/italic-shelf mais j'ai peur que la structure ne tiens pas le poids du livre

## objectif

2m30 sur 4m50
ça devrais contenir ceci: https://www.facebook.com/photo.php?fbid=10159034347495249&set=a.238912695248.280541.699115248&type=3&theater

## proposition

400 euro de matos et temps machine + 12DBières

### rewards

 12DBières

**Comment by nicolasdb** [comment]
Voir issue #42 
:)

**Comment by softrevolter** [comment]
ok je vient sur issue #42 et je ferme celle si
