### ISSUE TITLE
OpenBadge

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#67]
ref to file.md or #issue :
## contexte
Je surfe un peu sur l'internet et repasse sur cette histoire d'Openbadge. 
https://openbadges.org/get-started/issuing-badges/
Je viens de m'inscrire à https://badgr.io qui est une des options pour gérer une collec de badges mais ensuite je sais pas trop quoi faire...
## objectif
ça a l'air parfait comme système, c'est proche de ce que fait CC avec les licences opensource avec 3 niveau de lecture (légale, humaine et machine) mais avec des badges de compétences.
![bryan-mathers-open-badges-peeled](https://user-images.githubusercontent.com/12049360/27827400-5f198114-60b7-11e7-90ae-1c8bfc2b984c.png)
ça semble super pour pouvoir gérer nos propres badges en interne mais comment ça marche?
## proposition
Je pense que c'est un sujet à creuser et mieux comprendre mais faut rentrer dans le gras du site et s'approprier la matière.
Est-ce que quelqu'un se sens de faire cet effort? 
Idéalement, ce sera pour aider à implémenter ce système et ensuite être un peu le modérateur badge ou apprendre à qqu'un d'autre. 
De toutes façons -> documentation du parcours!

**Comment by Ginsburg** [comment]
Les quelques questions à se poser pour mettre sur pied un système de badges : http://dpdproject.info/files/2014/03/DPD-Project-Cards-Handout.pdf
À peu près la même chose mais sous forme de jeu de cartes, 1 question par carte, 40 cartes, 40 questions : http://dpdproject.info/files/2016/04/DPD-card-deck-frontback-draft7.pdf

**Comment by softrevolter** [comment]
Openbadge et #69 devrait pas merger?

**Comment by nicolasdb** [comment]
Si, mais surtout la création d'un repository badges pack fablab ou Openfab. Avec tout ce qui concerne la création de badge, la liste, les conditions d'acquisition, validation et support physique. 

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolasdb** [comment]
https://thenounproject.com/thiyagus15/collection/badges/?oq=badges&cidx=0

**Comment by nicolasdb** [comment]
Ce soir, si pas de reaction, je merge le pull #75 
https://github.com/openfab-lab/openfab/pull/75

Ce qui permettra d'avancer sur la création de 2 nouveau REPO :
- gamification
- badges

ok?

**Comment by softrevolter** [comment]
ok done!
