### ISSUE TITLE
Commande de bières 

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#7]
Xavier:
> On a une note de credit de 25 euros!
> Si tu recommande je veux bien que tu prennes 2 bacs de Delta et un bac de Grosse Bertha pour moi stp

Chez BxlBeerProject,
Faut leur commander et voir comment se faire livrer ou en allant chercher. 
On a un tarif à 1€/bouteille htva + vidange.
http://www.beerproject.be/en/sections/9-contact
Sébastien Morvan <sebastien@beerproject.be> 
Alix Thiran <alix@beerproject.be>

**Comment by nicolasdb** [comment]
Je suis passé direct chez eux le samedi. 
J'ai pris 2 bacs (capacité max de mon vélo) 1 Delta, 1 Soleil levant
Ils font un bon d'enlèvement et la facture est éditée, envoyée et payée par après, au tarif négocié. 

easy.

**Comment by softrevolter** [comment]
est-ce que ça pourrais devenir une missions récurrente?
