### ISSUE TITLE
B&P Aquaponie à la rentrée?

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#70]
ref to file.md or #issue :
## contexte
Massimo d'aquaponiebxl.eu aimerai programmer un bricole&picole à la rentrée pour annoncer une série de workshop R&D sur les techniques de vidange de bac de culture (siphon cloche, siphon U)
![image](https://user-images.githubusercontent.com/12049360/28063011-13d27d04-6630-11e7-86af-e0668f5e5ce0.png)

Massimo fait sa programmation et aimerai fixer une date rapidement. 
Perso, j'suis chaud !
## objectif
Explorer et développer une solution de siphon pour aquaponie, facile à régler voir automatique (le top) ET avec une production locale via le réseau partenaire à BXL.
## proposition
Commencer la boucle avec un B&P  et tester un process comme Artisan2.0 du CqD avec une série de petit workshop découverte technique d'un jour puis sélection du MVP le plus prometteur et finir avec un workshop hackaton de plusieurs jours pour fabriquer un système complet et mettre en test la solution développée.

**Comment by softrevolter** [comment]
chaud pour venir à ce B&P

**Comment by nicolasdb** [comment]
Ouais, je check ça demain

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolasdb** [comment]
Check. 
Présentation d'un kit aquaponie lors des portes ouvertes en septembre. Le 17. 
Annonce d'un b&p en soirée ou dans la semaine après la porte ouverte.

**Comment by nicolasdb** [comment]
Voici les disponibilités de Massimo pour le b&p en September. 

> Lundi 4 au Samedi 9 (sauf jeudi 7)
> Lundi 18
> Vendredi 22
> Lundi 25 au Samedi 30 (sauf jeudi 28)
> Au niveau des dimanches : le 3 et le 24 c bon.



_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by softrevolter** [comment]
tous ça me donne envie de créer un issue autour de l'agenda collectif pour avoir une vue global de ce qui ce passe dans le fablab?

**Comment by nicolasdb** [comment]
Mise à jour et confirmation d'agenda. 
17 sept, présentation avec massimo
22 sept, Bricole et picole de 20 à 22h. Faudra faire un meetup d'ailleurs.

**Comment by Ginsburg** [comment]
Est-ce qu'on ne fait pas une nouvelle issue pour le meetup ? (dans l'idée de ZenHub avec un vrai découpage des tâches, ça ressemble assez à une tâche facile à assigner à une personne).

J'en envie de tester comme ça pour voir, ça sera plus facile à repérer que de devoir retourner ici.

**Comment by nicolasdb** [comment]
si, voilà, super 👍

**Comment by Ginsburg** [comment]
![b p 22sept17](https://user-images.githubusercontent.com/7775797/29831049-3e139c4e-8ce4-11e7-899f-52dd17f11f08.png)

Ça convient ? Peut-être plus sous forme de question au lieu du basique "Aquaponie & Hydroponie" ?

**Comment by nicolasdb** [comment]
Ha oui, attention à la typo. C'est du roboto via google font. Tu l'as pas sur ton ordi et donc elle n'apparait pas comme il faut. 

Pour l'image, je préfèrerai une image du concept plus qu'un truc 3D fake, les gens s'attendent tjs à quelques choses sinon. Et sont déçu parce qu'on a pas le bidule qu'on montre en image. 

un truc comme ça par ex.
![image](https://user-images.githubusercontent.com/12049360/29832108-662c4e76-8ce7-11e7-8df2-9d9c99d5b5bf.png)


j'ai tjs bien aimé aussi ça: 
![image](https://user-images.githubusercontent.com/12049360/29832166-98e5bf96-8ce7-11e7-8b30-f744f8ff9acd.png)

C'est ultra simplifié et très abordable pour tout le monde et surtout très visuel.

**Comment by Ginsburg** [comment]
Ça peut donner ça : 
![b p 22sept17-v1](https://user-images.githubusercontent.com/7775797/29867197-13a7210a-8d7b-11e7-8554-85031f51e335.png)
ou ça :
![b p 22sept17-v2](https://user-images.githubusercontent.com/7775797/29867404-c32e8578-8d7b-11e7-855a-b2ba46465932.png)

**Comment by nicolasdb** [comment]
ho, j'aime bien la première, c'est joli avec l'image qui prend de la place plus haut.

**Comment by softrevolter** [comment]
c'est fait vendredi, je cloture
