### ISSUE TITLE
licence libre

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#79]
Mieux comprendre les licences libres. 

ref to file.md or #issue : 
Une ébauche est sur la branche new-files-order:
[/new-files-order/xx-src/choix-licences-OS.md](https://github.com/openfab-lab/openfab/blob/new-files-order/xx-src/choix-licences-OS.md)
## contexte
en lisant le post de Loois sur le groupe FB sur la licence des fabriques de mobilités, je me suis dis que ça serait bien d'avoir une page sur les descriptions et ressources concernant les types de licences. 
## objectif
Regrouper les contenus touchant la documentation du choix de tel ou tel licences libres quelque part de centralisé.
## proposition
Faire un fichier .md dans Ressources concernant ce sujet.

**Comment by nicolasdb** [comment]
Bon ben le fichier.md est créé, il n'y a plus qu'à le compléter au fur et à mesure.
Si vous êtes ok. J'empoche 5crrr et le prochain peut clore cette issue.

**Comment by softrevolter** [comment]
ok
