### ISSUE TITLE
Le biome (FR) - leur github

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#80]
https://github.com/LeBiome

Je suis tombé là dessus via un post trouvé sur facebook. 
Ils utilisent github et github page pour [leur site](https://lebiome.github.io/)

Et bien, je trouve ça un bel exemple de ce qu'il faudrait éviter. 
C'est pas très clair et pas invitant à participer alors que le sujet semble super.

**Comment by softrevolter** [comment]
c'est pas très user friendly en tous cas...

**Comment by nicolasdb** [comment]
bon, je clos, c'est pas vraiment quelque chose de remarquable.
