### ISSUE TITLE
nettoyage buro 

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#81]
ref to file.md or #issue : https://github.com/openfab-lab/openfab/blob/new-files-order/_space/Task/Cleaning-buro274.md
## contexte
c'est crade
## objectif
mise en pratique de la tâche complète aspi + eau
## proposition
- j'ai l'énergie, je m'en occupe, je chronomètre
- Est-ce qu'on créerai un badge "fée du logis" (cleaning fairy), unité badge: une action nettoyage, vaisselle ou poubelle.
![14703795](https://user-images.githubusercontent.com/12049360/28257263-b16c626c-6ac9-11e7-8674-ea0e591a83d1.jpg)

### rewards
j'empoche les 2D6 et les points de tps pour mon badge **timelord**

**Comment by nicolasdb** [comment]
Done in 1h24
Et j'ai fait les toilettes et les poubelles.
**reward sup.**  
Toilette, je prend 1d12, houuuuuuu risky. 
1d6 pour les poubelles.

et je me note 4 pts pour le badge "fée du logis" 
https://github.com/nicolasdb/crrr/edit/master/README.md


Le prochain qui lit ceci peut clore cette issue. (test de validation par les pairs)

**Comment by softrevolter** [comment]
nice le lootcrate! :)
