### ISSUE TITLE
Mission bike boombox prototype

### ISSUE THREAD

**Issue by looisjl** [openfab-lab/openfab#83]
# Mission bike boombox prototype 
ref to https://github.com/openfab-lab/openfab/blob/master/2repo/Gamification/Missions/bike-boombox.md 

## contexte
* Après la création de la fiche mission (cf. .md), est-il possible de planifier une/des dates pour la création du prototype avant le 28/07?  
* Se pose la question de comment inviter d'autres joueurs à la mission? 

## objectif
* Evaluer la faisabilité de la création du boombox avant le 28/07 
* Inviter plus de joueurs à la mission 
 
## proposition
* Chaque partie prenante du projet ou nouveau joueur propose des disponibilités entre le 21/07 et le 27/07? Via un Doodle?

**Comment by nicolasdb** [comment]
Je serai là du 21 au 27 excepté le mercredi matin pour l'IJV14

**Comment by nicolasdb** [comment]
### Update velom2 + makeLib 
Voici pour les quantités en bois section 35x35 (Gedebois)
Pour une structure de 650x450mm (dimension extérieure) avec un panneau couvrant de 3mm (matière au choix)
Le fichier est ici: http://a360.co/2gUBbHy
Avec la hauteur, la section carrée du bois et l'épaisseur des panneaux extérieur comme variable. Attention que c'est la structure intérieur qui s'adapte aux dimensions fixée à 650 et 450mm.
![image](https://user-images.githubusercontent.com/12049360/28499857-9b739f7a-6fbf-11e7-9cce-ce111ac894c4.png)

**Comment by nicolasdb** [comment]
**Jacqueline Box00**
![image](https://user-images.githubusercontent.com/12049360/28516550-e661ba92-7061-11e7-8363-55dcbf294978.png)

Environ 5.8kg

**Jacqueline Box01**
![image](https://user-images.githubusercontent.com/12049360/28516580-ff7c9588-7061-11e7-9fc7-302de1808f0b.png)

Environ 3.3kg

**Comment by nicolasdb** [comment]
holalala, les vieux dossiers.
