### ISSUE TITLE
La boucle de jeu

### ISSUE THREAD

**Issue by softrevolter** [openfab-lab/openfab#85]
# La boucle de jeu: comment bien l'expliquer et où le poster
ref to file.md or #issue :
## contexte  
j'ai un concept pour bien expliquer la boucle de jeu, mais je ne sais pas ou la mettre, quelqu'un pourrais m'aider
## objectif
Arriver à l'ajouter au bon endroit
## proposition

Suivre la logic: Declic - Routine - Reward  

| Declic      | Routine     | Reward |
| ------------- |:-------------:| -----:|
| Problem      | |  |  
| Remarque    | write in an issue    |   1D2 |  
| Opportunity|      |    |  
| ------------- |:-------------:| -----:|
|    | Créer task récurrante| 1D3 |
| issue    | Réponse + fichier MD       |  1D6 |
|  | Réponse et cloture  |  1DBière |                   
| ------------- |:-------------:| -----:|
|task   | finir task      |  reward task |
| ------------- |:-------------:| -----:|
|    | Finir mission + documentation| 2D6 + Mission reward + Loot |
|Fichier.md   | Finir mission      |  Mission reward + Loot |
 
                                            

- Fichier.md                         - Finir mission + documentation  -  2D6 + Reward Mission + Loot
                                             -  Finir mission                               - Reward Mission + Loot

**Comment by nicolasdb** [comment]
le bon endroit, pour moi c'est si c'est un sujet "transversal" qui touche d'autres sujets, comme la boucle ou les références fournisseurs. 

je mettrai ça dans le dossier source ou faire un dossier procédure, peut-être dans un dossier backoffice. On a pas encore la 6ème catégories.

**Comment by nicolasdb** [comment]
ok, la boucle est bonne mais elle a vachement évolué depuis. 
Et l'histoire des Dé est trop poussée, elle reviendra un jour mais les gens ne sont pas encore prêts. 
On doit construire les bases avant. 

https://github.com/nicolasdb/nicolasdb.github.io/issues/28
