### ISSUE TITLE
Différence "branch" vs. "fork"

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#86]
# Différence "branch" vs. "fork"
ref to file.md or #issue : 
## contexte 
Pas toujours simple de faire la différence entre "branch" et "fork", pourquoi l'un plus que l'autre.
## objectif
Comprendre la différence et savoir lequel utilisé au bon moment.
## ressources
Guide qui présente la différence entre les 2 : https://blog.gitprime.com/forks-branches-in-git-the-definitive-guide

## Resultats

`Forks are best used: when the intent of the ‘split’ is to create a logically independent project, which may never reunite with its parent.`

`Branches are best used: when they are created as temporary places to work through a feature, with the intent to merge the branch with the origin.`

**Comment by softrevolter** [comment]
Test: crée une page FAQ et ajoute déjà ceci, 

Suite: si tu le fait, tu cloture le issue @Ginsburg
