### ISSUE TITLE
Rédaction du fichier read.me du repo OpenFab

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/openfab#87]
# Rédaction du fichier read.me du repo OpenFab
ref to file.md or #issue : https://github.com/openfab-lab/openfab/blob/master/README.md

## contexte 
C'est le premier fichier sur lequel arrive un visiteur.

## objectif
Avoir un read.me qui claque, simple et efficace pour guider les visiteurs, contributeurs, membres, ...

## proposition
Template:
_what
_how
_why
_help

## ressources
Guide Open Source : https://opensource.guide/starting-a-project/#writing-a-readme
Template:
_What does this project do?
_Why is this project useful?
_How do I get started?
_Where can I get more help, if I need it?

**Comment by nicolasdb** [comment]
Je pense aussi qu'une table des matières serrait pertinante quelque part dans le readme.
Je ne retrouve pas facilement ce que j'ai déplacé :p

**Comment by nicolasdb** [comment]
Quote du docu COSMOS 
" One adventure, many heroes"

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolasdb** [comment]
You're welcome
![rug-funny-doormats](https://user-images.githubusercontent.com/12049360/28679170-a1a2e276-72f2-11e7-8e62-30f7a687909c.jpg)

**Comment by Ginsburg** [comment]
Voili voilou, j'ai assez envie de faire cette issue dans pas trop longtemps pour dire que ça cloture la première itération dans l'idée dans refaire une nouvelle quand on aura envie de l'améliorer.

En [anglais]( https://github.com/openfab-lab/openfab/blob/master/README.md), sûrement avec plein de fautes.
En [français](https://github.com/openfab-lab/openfab/blob/master/README-FR.md), sûrement avec un peu de fautes mais pas trop. 

Y-a-t'il des modifs à faire avant fermeture ?

**Comment by nicolasdb** [comment]
@openfab-lab/website-modo

**Comment by nicolasdb** [comment]
C'est top la timeline. :)
Il y a des trucs qui passent pas par contre. 
comme les termes USER dans un titre FR, ça cloche. idem avec METAUSER. ça se lit bisarement dans le titre. 
Mais faut quelqu'un de plus litéraire et graphiste pour affiner la com. c'est sur.

**Comment by Ginsburg** [comment]
Effectivement, j'ai tellement en tête le mot anglais que j'en oublie que ça peut être un mot français qui n'a pas franchement la même signification !

Je sais pas trop si la timeline est à sa place ici mais je me disais que pouvoir communiquer facilement ce parcours membre, cette possibilité d'évolution pouvait servir de fil conducteur pour introduire la gamification aux membres potentiels comme à ceux déjà présents.

**Comment by nicolasdb** [comment]
Done. 
ET pull request fusionné. 

+6crrr à @Ginsburg
