### ISSUE TITLE
Fichier source svg logo OpenFab

### ISSUE THREAD

**Issue by looisjl** [openfab-lab/openfab#89]
# Fichier source svg logo OpenFab

## contexte
* On voudrait intégrer le logo OpenFab dans les designs de la laser pour la mission du bike boombox Jacqueline
## objectif
* Pouvoir télécharger le logo OpenFab (et ses déclinaisons) en fichier vectoriel 
## proposition
* Placer les fichiers qqpart sur GitHub

**Comment by nicolasdb** [comment]
okok, je vois qu'on m'assigne du boulot. :)

Alors je propose de ranger ça dans /xx-src/visuel

1crrr pour Loois, 5crrr pour moi #loooot
sujet à fermer
