### ISSUE TITLE
Fichier source svg logo guildes

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#91]
ref to file.md or #issue :
## contexte
Tant qu'à réunir les logo. 
## objectif
Organiser dans un lieu unique les sources des logos nécessaire à nos communications.
## proposition
Velom2, jacqueline, si vous avez des logos en svg et/ou en png (fond transparent) ready à être utilisé, vous pouvez les ajouter dans xx-src/visuel
J'ai déjà mis des versions openfab en format vertical et horizontal, en svg et en png grande taille et petite taille.

**Comment by looisjl** [comment]
cool thanks @nicolasdb

**Comment by nicolasdb** [comment]
heuuu, vous avez des logos? sont-ils quelque part?
Il faudrait ajouter le lien du dossier. 
Qu'on ferme cette issue si c'est fait.

**Comment by nicolasdb** [comment]
je pense que cette issue est morte toute seule. 

On réunit aujourd'hui les documents visuels dans le TeamDrive/OF-LeGriffe
