### ISSUE TITLE
stockage librairie digitale

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#93]
ref to file.md or #issue : 
https://github.com/openfab-lab/openfab/blob/master/_space/mediatheque.md

## contexte
J'ai convertis en mp3 quelques audiobooks, j'ai aussi quelques pdfs mais c'est pas trop légal au partage.
## objectif
Avoir un lieu de stockage pour une bibliothèque accessibles qu'aux membres pour y partager des lectures, films et autres ressources intéressantes dans nos contextes.
## proposition
- Actuellement, j'ai un dossier sur le NAS. 
- On peut passer par un dossier partager sur Drive, mais bof. 
- Dropbox, pareil, bof. 
- à un certain niveau, on peut aussi se partager un dossier via "syncthings" similaire à la logique dropbox mais opensource et sans cloud. direct entre le NAS et l'usager. Mais demande une installation et gestion minimum.
- J'ai un compte 50Go sur MEGA, je pourrai y droper quelques trucs et partager les liens. Mais bof, pareil... 
- il y a aussi les livres en vrai?
- avoir un compte asbl partagé entre nous chez kindle et audible?

**Comment by nicolasdb** [comment]
En fait. J'aime bien l'idée que la bibliothèque soit numérique mais locale.
Comme un "dead drop", faut bouger son cul et venir sur place avec son Tupperware USB pour avoir sa copie numérique du livre. 
Cool. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolasdb** [comment]
j'ai une partition MEDIA sur le NAS en local
\\MEDIAHUB\media\Books

![image](https://user-images.githubusercontent.com/12049360/28682733-51c68788-72fe-11e7-9cd9-108b5288dbbb.png)

**Comment by nicolasdb** [comment]
oups, sorry

sujet à fermer.

**Comment by softrevolter** [comment]
On retrouve cette info dans un wiki ou un .md?

**Comment by nicolasdb** [comment]
Yup, Le lien est au début de l'issue. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
