### ISSUE TITLE
promo Stickers

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/openfab#96]
ref to file.md or #issue :
## contexte
J'ai déja commandé des stickers chez Yetistickers. Les petits rond OF sont plutôt bien réussi et de bonne qualité. J'ai aussi eu des petits badges github spécial textile (à repasser) j'ai pas encore essayé mais c'est l'occasion. 
Et il y a une promo de 15% jusqu'au 6 Aout
## objectif
C'est plus une question. 
Est-ce qu'on recommanderai des stickers? Si oui, quel taille et de quel design?
VéloM²? Jacqueline? autres?

**Comment by softrevolter** [comment]
moi je suis partant pour des stickers. C'est quoi le prix et tu as besoin de quel file pour vélo m2?

**Comment by nicolasdb** [comment]
Les petits qu'on a là, je pense avoir payé 60 +-. 
Pour 500 si je me rappelle bien.

Il faut un visuel, idéalement en vectoriel pdf ou une image de bonne résolution. 
La commande, la mise en place et la taille, tout se fait en ligne.

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicolasdb** [comment]
bon, j'ai un peu oublié cette histoire et je pars maintenant pour le week-end. 
http://zvje.r.a.d.sendibm1.com/3kdj4o0czojf.html

Voici ce que j'ai reçu et le code de réduction. plus que 2jours. 
Mais bon, c'est pas la première promo que je reçois, c'est tout les 3 ou 4 mois sans doute. La dernière était d'avril avec -10%

**Comment by Ginsburg** [comment]
Fin de la promo !
